// BranCHAT Figure 拡張（P5: 「まだ無い図」の追加）
// 既存の表の型に足した type: column の density / ridgeline / raincloud、grouped の radar / dot-cat、xy の xy-density、
// roc の pr / calibration / dca、survival の cif、forest の funnel、heatmap の hic / profile、multi の scatter3d、swimmer の gantt、importance の wordcloud、
// omics の circos / cnv / trajectory / lollipop。新しい kind: sets（UpSet）、nomogram、tracks（ゲノムトラック）。
// figure-omics.js の P4 フックの先頭から figAutoKindP5 / figBuildDataP5 / figRenderP5 / figStatsP5 として呼ばれる。見本は figSampleP5（figure-gallery.js が先に呼ぶ）。
'use strict';

FIG_TYPES.column.push(['density','密度曲線（KDE）'],['ridgeline','リッジライン（列ごとの分布を段に）'],['raincloud','レインクラウド（雲＋箱＋点）']);
FIG_TYPES.grouped.push(['radar','レーダー（行＝軸、列＝系列）'],['dot-cat','ドットプロット（Cleveland 型）']);
FIG_TYPES.xy.push(['xy-density','2 次元密度・等高線']);
FIG_TYPES.roc.push(['pr','Precision–Recall 曲線'],['calibration','キャリブレーション曲線（予測確率, Class）'],['dca','決定曲線（DCA、予測確率, Class）']);
FIG_TYPES.survival.push(['cif','競合リスクの累積発生（Event 0/1/2）']);
FIG_TYPES.forest.push(['funnel','ファンネルプロット（メタ解析）']);
FIG_TYPES.heatmap.push(['hic','Hi-C 接触行列'],['profile','プロファイルヒートマップ（行＝領域、列＝ビン）']);
FIG_TYPES.multi.push(['scatter3d','3D 散布（x, y, z）']);
FIG_TYPES.swimmer.push(['gantt','ガントチャート（Task, Start, End）']);
FIG_TYPES.importance.push(['wordcloud','ワードクラウド（Word, Weight）']);
FIG_TYPES.omics.push(['circos','Circos（染色体間のリンク）'],['cnv','コピー数（Chr, Start, End, log2）'],['trajectory','UMAP の軌跡（x, y, pseudotime）'],['lollipop','ロリポップ（Position, Value）']);
Object.assign(FIG_TYPES,{sets:[['upset','UpSet（集合の重なり）']],nomogram:[['nomogram','ノモグラム（Variable, Coef, Min, Max）']],tracks:[['tracks','ゲノムトラック（Track, Start, End, …）']]});
const FIG_KINDS_P5=[['sets','集合（列＝集合、1/0 の所属）'],['nomogram','ノモグラム（Variable, Coef, Min, Max）'],['tracks','ゲノムトラック（Track, Start, End, Value/Name）']];
document.addEventListener('DOMContentLoaded',()=>{const sel=document.querySelector('#figKind');if(sel)FIG_KINDS_P5.forEach(([v,l])=>{const op=document.createElement('option');op.value=v;op.textContent=l;sel.appendChild(op);});});
const FIG_DEF_P5={kdeBw:'1',kdeFill:true,ridgeOverlap:'1.8',rainJitter:true,radarFill:true,radarMax:'',d2Levels:'8',d2Points:true,calBins:'10',dcaXmax:'1',cifAll:false,funnelEgger:true,hicLog:true,hicScheme:'wr',profSort:true,s3dAz:'35',s3dEl:'25',ganttNow:'',wcMax:'44',cxLabels:true,cnvThr:'0.3',trajBins:'20',lolTop:'5',upsetN:'15',nomoPts:'100',trackH:'0.35'};
Object.assign(FIG_DEF,FIG_DEF_P5);FIG_STYLE_KEYS.push(...Object.keys(FIG_DEF_P5));
Object.assign(FIG_TOOLS_MORE,{
  density:[{k:'kdeBw',t:'select',l:'帯域幅（Silverman ×）',o:[['0.5','狭い（0.5）'],['1','標準（1）'],['2','広い（2）']]},{k:'kdeFill',t:'check',l:'曲線の下を塗る'}],
  ridgeline:[{k:'kdeBw',t:'select',l:'帯域幅（Silverman ×）',o:[['0.5','狭い'],['1','標準'],['2','広い']]},{k:'ridgeOverlap',t:'select',l:'重なり',o:[['1','なし'],['1.8','ふつう'],['3','大きい']]}],
  raincloud:[{k:'rainJitter',t:'check',l:'点を横に散らす'},{k:'kdeBw',t:'select',l:'雲の帯域幅',o:[['0.5','狭い'],['1','標準'],['2','広い']]}],
  radar:[{k:'radarFill',t:'check',l:'多角形を塗る'},{k:'radarMax',t:'text',l:'軸の最大（空なら自動）'}],
  'xy-density':[{k:'d2Levels',t:'select',l:'等高線の本数',o:[['5','5'],['8','8'],['12','12']]},{k:'d2Points',t:'check',l:'点も重ねる'}],
  calibration:[{k:'calBins',t:'select',l:'区間の数',o:[['5','5'],['10','10'],['20','20']]}],
  dca:[{k:'dcaXmax',t:'select',l:'しきい値確率の上限',o:[['0.5','0.5'],['0.8','0.8'],['1','1.0']]}],
  cif:[{k:'cifAll',t:'check',l:'競合イベント（2）の曲線も破線で描く'}],
  funnel:[{k:'funnelEgger',t:'check',l:'Egger の検定を書く'}],
  hic:[{k:'hicLog',t:'check',l:'log10(1+値) で色付け'},{k:'hicScheme',t:'select',l:'色',o:[['wr','白→赤'],['wb','白→青'],['viridis','Viridis']]}],
  profile:[{k:'profSort',t:'check',l:'行を平均の大きい順に並べる'}],
  scatter3d:[{k:'s3dAz',t:'select',l:'回転（方位）',o:[['20','20°'],['35','35°'],['50','50°'],['65','65°']]},{k:'s3dEl',t:'select',l:'仰角',o:[['15','15°'],['25','25°'],['40','40°']]}],
  gantt:[{k:'ganttNow',t:'text',l:'現在の位置に線（数値、空なら無し）'}],
  wordcloud:[{k:'wcMax',t:'select',l:'最大の文字 (pt)',o:[['32','32'],['44','44'],['60','60']]}],
  circos:[{k:'cxLabels',t:'check',l:'染色体名を書く'}],
  cnv:[{k:'cnvThr',t:'select',l:'増幅・欠失のしきい値 |log2|',o:[['0.2','0.2'],['0.3','0.3'],['0.5','0.5']]}],
  trajectory:[{k:'trajBins',t:'select',l:'軌跡の滑らかさ（区間数）',o:[['10','粗い'],['20','ふつう'],['40','細かい']]}],
  lollipop:[{k:'lolTop',t:'select',l:'名前を書く上位 n',o:[['0','なし'],['5','5'],['10','10']]}],
  upset:[{k:'upsetN',t:'select',l:'組み合わせの上位 n',o:[['10','10'],['15','15'],['25','25']]}],
  nomogram:[{k:'nomoPts',t:'select',l:'最大の点数',o:[['100','100'],['10','10']]}],
  tracks:[{k:'trackH',t:'select',l:'トラックの高さ (in)',o:[['0.25','0.25'],['0.35','0.35'],['0.5','0.5']]}]});

FIG_PROMPT+=`
さらに使える type: column の density（密度曲線）/ ridgeline / raincloud、grouped の radar（行＝軸、列＝系列）/ dot-cat、xy の xy-density（2 次元密度と等高線）、roc の pr（Precision–Recall）/ calibration / dca（列＝予測確率 0–1 と Class）、survival の cif（Event 0=打ち切り 1=対象 2=競合）、forest の funnel、heatmap の hic / profile、multi の scatter3d、swimmer の gantt（Task, Start, End, Group）、importance の wordcloud（Word, Weight）、omics の circos（From, FromPos, To, ToPos）/ cnv（Chr, Start, End, log2）/ trajectory（x, y, pseudotime, lineage 任意）/ lollipop（Position, Value, Label 任意）。
kind "sets": 列＝集合、各行が 1/0 で所属 → type upset。kind "nomogram": Variable, Coef（対数オッズ）, Min, Max（連続）か Variable, Level, Coef（カテゴリ）、Intercept の行 → type nomogram。kind "tracks": Track, Start, End, Value（シグナル）または Name（遺伝子・ピーク）, Strand 任意 → type tracks。`;

/* ---------- 共通 ---------- */
const figLC5=c=>String(c.name||'').toLowerCase();
function figKDE(values,bwMul,n){const v=values.filter(x=>isFinite(x));if(v.length<2)return null;const s=sd(v),iqr=quantile(v,0.75)-quantile(v,0.25);const h=0.9*Math.min(s||1e9,iqr/1.34||1e9)*Math.pow(v.length,-0.2)*(+bwMul||1)||(s||1)*0.3;const lo=Math.min(...v)-3*h,hi=Math.max(...v)+3*h;const N=n||160;const xs=[],ys=[];for(let i=0;i<N;i++){const x=lo+(hi-lo)*i/(N-1);let d=0;for(const u of v)d+=Math.exp(-0.5*((x-u)/h)**2);ys.push(d/(v.length*h*2.5066282746));xs.push(x);}return {xs,ys,h,lo,hi,max:Math.max(...ys)};}
// 独自 SVG の仕上げ（題名・注釈・返り値）
function figWrap5(spec,st,W,H,body,plot){const {o,fs,txt}=st;const title=figTitle1(txt,W/2,fs*1.3,spec.title,W-fs,fs);const notes=plot?figNotesSVG(o,plot.x0,plot.y0,plot.w,plot.h,fs,o.font,st.fw):'';return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/>${body}${title}${notes}</svg>`,w:W,h:H,plot};}
const FIG_CHR_LEN={1:248956422,2:242193529,3:198295559,4:190214555,5:181538259,6:170805979,7:159345973,8:145138636,9:138394717,10:133797422,11:135086622,12:133275309,13:114364328,14:107043718,15:101991189,16:90338345,17:83257441,18:80373285,19:58617616,20:64444167,21:46709983,22:50818468,X:156040895,Y:57227415}; // GRCh38
const figChrKey=s=>{let v=String(s||'').trim().replace(/^chr/i,'');if(/^x$/i.test(v))return 'X';if(/^y$/i.test(v))return 'Y';if(/^m$|^mt$/i.test(v))return 'M';return String(+v||v);};
const figChrOrder=(a,b)=>{const na=+a,nb=+b;if(isFinite(na)&&isFinite(nb))return na-nb;if(isFinite(na))return -1;if(isFinite(nb))return 1;return String(a).localeCompare(String(b));};
const figBp=v=>v>=1e6?(v/1e6).toFixed(v%1e6?2:0)+' Mb':v>=1e3?(v/1e3).toFixed(v%1e3?1:0)+' kb':String(v);

/* ---------- 表の型の判定・データ ---------- */
function figAutoKindP5(parsed){const cols=parsed.cols;const has=re=>cols.some(c=>re.test(figLC5(c)));
  if(has(/^(chr|chrom|chromosome)$/)&&has(/^(start|loc\.start)$/)&&has(/log2|seg\.?mean|segment_mean|ratio/))return 'omics';
  {const eC=cols.find(c=>/^(event|status|転帰|イベント)$/.test(figLC5(c)));const tC=cols.find(c=>/^(time|day|month|week|year|日|月|週|年|期間)/.test(figLC5(c)));if(eC&&tC&&eC.raw.every(v=>v===''||/^[0-9]$/.test(String(v).trim()))&&eC.raw.some(v=>+v>=2))return 'survival';}
  if(has(/^(variable|変数)$/)&&has(/^(coef|beta|係数|coefficient)$/))return 'nomogram';
  if(has(/^(track|トラック)$/)&&has(/^(start|開始)$/)&&has(/^(end|終了)$/))return 'tracks';
  const data=cols.filter(c=>c!==cols[0]||!parsed.firstColText);if(data.length>=3&&data.every(c=>c.raw.some(v=>v!=='')&&c.raw.every(v=>v===''||/^(0|1|true|false|yes|no)$/i.test(String(v).trim())))&&!has(/class|outcome|event|status/))return 'sets';
  return null;}
function figBuildDataP5(parsed,kind){const cols=parsed.cols;
  if(kind==='sets'){const sets=cols.filter(c=>(c!==cols[0]||!parsed.firstColText)&&c.raw.some(v=>v!==''));if(sets.length<2)return null;const n=cols[0].raw.length;const M=[];for(let i=0;i<n;i++){const row=sets.map(c=>/^(1|true|yes)$/i.test(String(c.raw[i]||'').trim())?1:0);if(row.some(Boolean))M.push(row);}return {kind:'sets',sets:sets.map(c=>c.name),M,groups:[]};}
  if(kind==='nomogram'){const find=re=>cols.find(c=>re.test(figLC5(c)))||null;const vC=find(/^(variable|変数)$/)||cols[0],cC=find(/^(coef|beta|係数|coefficient)$/),lC=find(/^(level|水準|category)$/),minC=find(/^(min|最小)$/),maxC=find(/^(max|最大)$/);if(!cC)return null;
    const vars=[];let intercept=0;for(let i=0;i<cC.raw.length;i++){const name=String(vC.raw[i]||'').trim();const coef=cC.vals[i];if(!name||coef===null)continue;if(/intercept|切片/i.test(name)){intercept=coef;continue;}let v=vars.find(x=>x.name===name);if(!v){v={name,levels:[],min:null,max:null,coef:null};vars.push(v);}const lv=lC?String(lC.raw[i]||'').trim():'';if(lv){v.levels.push({name:lv,coef});}else{v.coef=coef;v.min=minC?minC.vals[i]:null;v.max=maxC?maxC.vals[i]:null;}}
    return {kind:'nomogram',vars:vars.filter(v=>v.levels.length||(v.coef!==null&&v.min!==null&&v.max!==null)),intercept,groups:[]};}
  if(kind==='tracks'){const find=re=>cols.find(c=>re.test(figLC5(c)))||null;const tC=find(/^(track|トラック)$/)||cols[0],sC=find(/^(start|開始)$/),eC=find(/^(end|終了)$/),vC=find(/^(value|signal|score|値)$/),nC=find(/^(name|gene|feature|名前)$/),stC=find(/^(strand|鎖)$/),chrC=find(/^(chr|chrom|chromosome)$/);if(!sC||!eC)return null;
    const tracks=[];for(let i=0;i<sC.vals.length;i++){const s=sC.vals[i],e=eC.vals[i];if(s===null||e===null)continue;const name=String(tC.raw[i]||'track').trim();let t=tracks.find(x=>x.name===name);if(!t){t={name,items:[]};tracks.push(t);}t.items.push({s:Math.min(s,e),e:Math.max(s,e),v:vC?vC.vals[i]:null,label:nC?String(nC.raw[i]||'').trim():'',strand:stC?String(stC.raw[i]||'').trim():'',chr:chrC?String(chrC.raw[i]||'').trim():''});}
    tracks.forEach(t=>{t.signal=t.items.some(it=>it.v!==null)&&!t.items.some(it=>it.label);});return {kind:'tracks',tracks,groups:[]};}
  if(kind==='survival'){const base=figBuildSurvival(parsed);if(!base)return base;const eCol=cols.find(c=>/event|status|death|dead|died|イベント|死亡|転帰|censor/.test(figLC5(c)))||null;base.parsed=parsed;base.eventCol=eCol?eCol.name:null;base.codes=eCol?eCol.raw.map(v=>{const s=String(v).trim().toLowerCase();if(/^(0|no|false|alive|censored?|n|なし|無|生存|打ち切り)$/.test(s))return 0;const k=parseInt(s,10);return isFinite(k)?k:1;}):null;return base;}
  return undefined;}

/* ---------- 描画 ---------- */
function figRenderP5(spec){const d=spec.data,t=spec.type;if(!d)return null;
  if(d.kind==='sets')return figRenderUpset(spec);if(d.kind==='nomogram')return figRenderNomogram(spec);if(d.kind==='tracks')return figRenderTracks(spec);
  const map={density:figRenderDensity,ridgeline:figRenderRidge,raincloud:figRenderRain,radar:figRenderRadar,'dot-cat':figRenderDotCat,'xy-density':figRenderDensity2D,pr:figRenderPR,calibration:figRenderCalib,dca:figRenderDCA,cif:figRenderCIF,funnel:figRenderFunnel,hic:figRenderHiC,profile:figRenderProfile,scatter3d:figRender3D,gantt:figRenderGantt,wordcloud:figRenderWordCloud,circos:figRenderCircos,cnv:figRenderCNV,trajectory:figRenderTrajectory,lollipop:figRenderLollipop};
  const need={density:'column',ridgeline:'column',raincloud:'column',radar:'grouped','dot-cat':'grouped','xy-density':'xy',pr:'roc',calibration:'roc',dca:'roc',cif:'survival',funnel:'forest',hic:'heatmap',profile:'heatmap',scatter3d:'multi',gantt:'swimmer',wordcloud:'importance',circos:'omics',cnv:'omics',trajectory:'omics',lollipop:'omics'};
  if(map[t]&&need[t]===d.kind)return map[t](spec);return null;}

// 密度曲線
function figRenderDensity(spec){const d=spec.data;const gs=d.groups.filter(g=>g.values.length>=2);if(!gs.length)return {svg:'',w:0,h:0};const o=Object.assign({},FIG_DEF,spec.opts||{});
  const ks=gs.map(g=>figKDE(g.values,o.kdeBw));const xs=figAxisLin(Math.min(...ks.map(k=>k.lo)),Math.max(...ks.map(k=>k.hi)),5);const ys=figAxisLin(0,Math.max(...ks.map(k=>k.max))*1.08,5);
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Value',yTitle:o.yTitle||'Density',legend:gs.length>1?gs.map((g,i)=>({name:g.name,kind:'line',i})):[]});const {xOf,yOf,S}=F;
  let body='';ks.forEach((k,i)=>{const c=S(i).color;const pts=k.xs.map((x,j)=>`${xOf(x)},${yOf(k.ys[j])}`).join(' ');body+=`<g data-sel="series:${i}">${o.kdeFill?`<polygon points="${xOf(k.xs[0])},${yOf(0)} ${pts} ${xOf(k.xs[k.xs.length-1])},${yOf(0)}" fill="${c}" fill-opacity="0.22" stroke="none"/>`:''}<polyline points="${pts}" fill="none" stroke="${c}" stroke-width="${S(i).lineW*FIG_PT*1.5}"/></g>`;});
  const r=F.wrap(body);r.res={kde:ks.map((k,i)=>({name:gs[i].name,n:gs[i].values.length,h:k.h,mode:k.xs[k.ys.indexOf(k.max)]}))};return r;}
// リッジライン
function figRenderRidge(spec){const d=spec.data;const gs=d.groups.filter(g=>g.values.length>=2);if(!gs.length)return {svg:'',w:0,h:0};const o=Object.assign({},FIG_DEF,spec.opts||{});const n=gs.length;
  const ks=gs.map(g=>figKDE(g.values,o.kdeBw));const xs=figAxisLin(Math.min(...ks.map(k=>k.lo)),Math.max(...ks.map(k=>k.hi)),5);const ys={lo:0,hi:n,cat:true,ticks:gs.map((g,i)=>({v:n-i-0.5,l:g.name}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Value',hIn:figDefSize(spec,'hIn')?Math.max(1.5,n*0.45):0,padL:Math.max(0,Math.max(...gs.map(g=>figTW(g.name,F0(o))))-F0(o)*1.6)});const {xOf,yOf,S}=F;const rowH=yOf(0)-yOf(1);const ov=+o.ridgeOverlap||1.8;
  let body='';ks.forEach((k,i)=>{const base=yOf(n-i-1)-rowH*0.08;const sc=rowH*ov*0.95/k.max;const c=S(i).color;const pts=k.xs.map((x,j)=>`${xOf(x)},${base-k.ys[j]*sc}`).join(' ');body+=`<g data-sel="series:${i}"><polygon points="${xOf(k.xs[0])},${base} ${pts} ${xOf(k.xs[k.xs.length-1])},${base}" fill="${c}" fill-opacity="0.55" stroke="${c}" stroke-width="${FIG_PT}"/><line x1="${xOf(xs.lo)}" y1="${base}" x2="${xOf(xs.hi)}" y2="${base}" stroke="#444" stroke-width="${FIG_PT*0.5}"/></g>`;});
  const r=F.wrap(body);r.res={kde:ks.map((k,i)=>({name:gs[i].name,n:gs[i].values.length,h:k.h,median:median(gs[i].values)}))};return r;}
// レインクラウド（左に点、中央に箱、右に半分のバイオリン）
function figRenderRain(spec){const d=spec.data;const gs=d.groups.filter(g=>g.values.length>=2);if(!gs.length)return {svg:'',w:0,h:0};const o=Object.assign({},FIG_DEF,spec.opts||{});const n=gs.length;
  const all=gs.flatMap(g=>g.values);const pad=(Math.max(...all)-Math.min(...all))*0.08||1;const [ylo,yhi]=figYRange(o,Math.min(...all)-pad,Math.max(...all)+pad);const ys=figAxisLin(ylo,yhi,5);const xs={lo:0,hi:n,cat:true,ticks:gs.map((g,i)=>({v:i+0.5,l:g.name}))};
  const F=figFrame(spec,{x:xs,y:ys,yTitle:o.yTitle,xTitle:o.xTitle});const {xOf,yOf,S,sym,a}=F;const slot=xOf(1)-xOf(0);const R=figRng(7);let body='';
  gs.forEach((g,i)=>{const c=S(i).color;const cx=xOf(i+0.5);const k=figKDE(g.values,o.kdeBw);const v=g.values.slice().sort((p,q)=>p-q);const q1=quantile(v,0.25),q2=median(v),q3=quantile(v,0.75);const iqr=q3-q1;const wl=Math.min(...v.filter(x=>x>=q1-1.5*iqr)),wh=Math.max(...v.filter(x=>x<=q3+1.5*iqr));
    let s='';if(k){const w=slot*0.42/k.max;const pts=k.ys.map((y,j)=>`${cx+slot*0.06+y*w},${yOf(k.xs[j])}`);s+=`<polygon points="${cx+slot*0.06},${yOf(k.xs[0])} ${pts.join(' ')} ${cx+slot*0.06},${yOf(k.xs[k.xs.length-1])}" fill="${c}" fill-opacity="0.35" stroke="${c}" stroke-width="${FIG_PT*0.8}"/>`;}
    const bw=slot*0.1,bx=cx-slot*0.02;s+=`<line x1="${bx}" y1="${yOf(wl)}" x2="${bx}" y2="${yOf(wh)}" stroke="${c}" stroke-width="${a}"/><rect x="${bx-bw/2}" y="${yOf(q3)}" width="${bw}" height="${yOf(q1)-yOf(q3)}" fill="#fff" stroke="${c}" stroke-width="${a}"/><line x1="${bx-bw/2}" y1="${yOf(q2)}" x2="${bx+bw/2}" y2="${yOf(q2)}" stroke="${c}" stroke-width="${a*1.5}"/>`;
    v.forEach(val=>{const jx=o.rainJitter?(R.u()-0.5)*slot*0.26:0;s+=sym(cx-slot*0.28+jx,yOf(val),i,c,'solid');});body+=`<g data-sel="series:${i}">${s}</g>`;});
  const r=F.wrap(body);r.res={groups:gs.map(g=>({name:g.name,n:g.values.length,median:median(g.values),q1:quantile(g.values,0.25),q3:quantile(g.values,0.75)}))};return r;}
// レーダー（行＝軸、列＝系列。セルの平均）
function figRenderRadar(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,S,a}=st;const cats=d.cats,gs=d.groups;if(cats.length<3||!gs.length)return {svg:'',w:0,h:0};
  const vals=gs.map(g=>g.cells.map(c=>c.length?mean(c):0));const vmax=o.radarMax!==''&&isFinite(+o.radarMax)?+o.radarMax:figNiceTicks(0,Math.max(...vals.flat())*1.05||1,4).ticks.slice(-1)[0];const rings=4;
  const R=Math.min((+o.wIn||3),(+o.hIn||3))*FIG_IN*0.42;const labW=Math.max(...cats.map(c=>figTW(c,fs)));const legW=gs.length>1?Math.max(...gs.map(g=>figTW(g.name,fs)))+fs*2.5:0;const cx=labW+fs*1.5+R,cy=fs*2.2+R+fs*1.4;const W=cx+R+labW+fs*1.5+legW,H=cy+R+fs*2;
  const ang=i=>-Math.PI/2+2*Math.PI*i/cats.length;const P=(i,v)=>[cx+Math.cos(ang(i))*R*v/vmax,cy+Math.sin(ang(i))*R*v/vmax];let body='';
  const am=-Math.PI/2-Math.PI/cats.length;for(let k=1;k<=rings;k++){const v=vmax*k/rings;const rx=cx+Math.cos(am)*R*k/rings,ry=cy+Math.sin(am)*R*k/rings;body+=`<polygon points="${cats.map((_,i)=>P(i,v).join(',')).join(' ')}" fill="none" stroke="#bbb" stroke-width="${FIG_PT*0.5}"/>`+txt(rx-fs*0.15,ry+fs*0.25,figFmt(v),'end','fill="#666"',null,fs*0.7);}
  cats.forEach((c,i)=>{const [x,y]=P(i,vmax);body+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#999" stroke-width="${FIG_PT*0.6}"/>`;const [lx,ly]=P(i,vmax*1.17);const anc=Math.abs(Math.cos(ang(i)))<0.2?'middle':Math.cos(ang(i))>0?'start':'end';body+=txt(lx,ly+fs*0.35,c,anc);});
  let series='';gs.forEach((g,gi)=>{const c=S(gi).color;const pts=vals[gi].map((v,i)=>P(i,v));series+=`<g data-sel="series:${gi}"><polygon points="${pts.map(p=>p.join(',')).join(' ')}" fill="${c}" fill-opacity="${o.radarFill?0.18:0}" stroke="${c}" stroke-width="${S(gi).lineW*FIG_PT*1.5}"/>${pts.map(p=>st.sym(p[0],p[1],gi,c,'solid')).join('')}</g>`;});
  let leg='';if(gs.length>1)gs.forEach((g,gi)=>{const y=fs*2.2+gi*fs*1.5;leg+=`<rect x="${cx+R+labW+fs*0.6}" y="${y-fs*0.5}" width="${fs}" height="${fs*0.7}" fill="${S(gi).color}"/>`+txt(cx+R+labW+fs*1.9,y+fs*0.1,S(gi).name||g.name,'start');});
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${body}</g>${series}${leg?`<g data-sel="legend">${leg}</g>`:''}`,{x0:cx-R,y0:cy-R,w:2*R,h:2*R});r.res={vmax,table:gs.map((g,gi)=>({name:g.name,vals:vals[gi]}))};return r;}
// Cleveland 型ドットプロット（行＝カテゴリ、系列ごとの点を線で結ぶ）
function figRenderDotCat(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const cats=d.cats,gs=d.groups;const n=cats.length;if(!n||!gs.length)return {svg:'',w:0,h:0};
  const vals=gs.map(g=>g.cells.map(c=>c.length?mean(c):null));const flat=vals.flat().filter(v=>v!==null);const pad=(Math.max(...flat)-Math.min(...flat))*0.1||1;const xs=figAxisLin(Math.min(...flat)-pad,Math.max(...flat)+pad,5);const ys={lo:0,hi:n,cat:true,ticks:cats.map((c,i)=>({v:n-i-0.5,l:c}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Value',legend:gs.length>1?gs.map((g,i)=>({name:g.name,kind:'sym',i})):[],hIn:figDefSize(spec,'hIn')?Math.max(1.2,n*0.3):0,padL:Math.max(0,Math.max(...cats.map(c=>figTW(c,F0(o))))-F0(o)*1.6)});const {xOf,yOf,S,sym,a}=F;
  let body='';cats.forEach((c,i)=>{const y=yOf(n-i-0.5);const row=vals.map(v=>v[i]).filter(v=>v!==null);if(row.length>1)body+=`<line x1="${xOf(Math.min(...row))}" y1="${y}" x2="${xOf(Math.max(...row))}" y2="${y}" stroke="#999" stroke-width="${a}"/>`;else body+=`<line x1="${xOf(xs.lo)}" y1="${y}" x2="${xOf(xs.hi)}" y2="${y}" stroke="#ddd" stroke-width="${FIG_PT*0.5}" stroke-dasharray="${FIG_PT*2} ${FIG_PT*2}"/>`;});
  gs.forEach((g,gi)=>{let s='';vals[gi].forEach((v,i)=>{if(v!==null)s+=sym(xOf(v),yOf(n-i-0.5),gi,S(gi).color,'solid');});body+=`<g data-sel="series:${gi}">${s}</g>`;});
  const r=F.wrap(body);r.res={table:cats.map((c,i)=>({cat:c,vals:vals.map(v=>v[i])})),series:gs.map(g=>g.name)};return r;}
// 2 次元密度（格子を塗り、等高線を marching squares で描く）
function figRenderDensity2D(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const pts=d.groups.flatMap(g=>g.points.flatMap(p=>p.ys.map(y=>({x:p.x,y}))));if(pts.length<3)return {svg:'',w:0,h:0};
  const X=pts.map(p=>p.x),Y=pts.map(p=>p.y);const sx=sd(X)||1,sy=sd(Y)||1;const n=pts.length;const hx=sx*Math.pow(n,-1/6)*1.06,hy=sy*Math.pow(n,-1/6)*1.06;const G=44;const lo=[Math.min(...X)-2.5*hx,Math.min(...Y)-2.5*hy],hi=[Math.max(...X)+2.5*hx,Math.max(...Y)+2.5*hy];
  const Z=[];let zmax=0;for(let j=0;j<G;j++){const row=[];const y=lo[1]+(hi[1]-lo[1])*j/(G-1);for(let i=0;i<G;i++){const x=lo[0]+(hi[0]-lo[0])*i/(G-1);let s=0;for(const p of pts)s+=Math.exp(-0.5*(((x-p.x)/hx)**2+((y-p.y)/hy)**2));s/=n*hx*hy*2*Math.PI;row.push(s);if(s>zmax)zmax=s;}Z.push(row);}
  const xs=figAxisLin(lo[0],hi[0],5),ys=figAxisLin(lo[1],hi[1],5);const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||d.xname,yTitle:o.yTitle||(d.groups[0]&&d.groups[0].name)});const {xOf,yOf,S,sym}=F;const c=S(0).color;
  const gx=i=>lo[0]+(hi[0]-lo[0])*i/(G-1),gy=j=>lo[1]+(hi[1]-lo[1])*j/(G-1);let body='';const cw=xOf(gx(1))-xOf(gx(0)),ch=yOf(gy(0))-yOf(gy(1));
  for(let j=0;j<G-1;j++)for(let i=0;i<G-1;i++){const z=(Z[j][i]+Z[j][i+1]+Z[j+1][i]+Z[j+1][i+1])/4/zmax;if(z<0.03)continue;body+=`<rect x="${xOf(gx(i))}" y="${yOf(gy(j+1))}" width="${cw+0.3}" height="${ch+0.3}" fill="${figGrad(['#FFFFFF',c],Math.pow(z,0.7))}" stroke="none"/>`;}
  const L=+o.d2Levels||8;let lines='';for(let k=1;k<=L;k++){const lv=zmax*k/(L+1);for(let j=0;j<G-1;j++)for(let i=0;i<G-1;i++){const a=Z[j][i]>=lv,b=Z[j][i+1]>=lv,c2=Z[j+1][i+1]>=lv,dd=Z[j+1][i]>=lv;const idx=(a?8:0)|(b?4:0)|(c2?2:0)|(dd?1:0);if(idx===0||idx===15)continue;
      const ip=(v0,v1,p0,p1)=>p0+(lv-v0)/((v1-v0)||1e-12)*(p1-p0);const top=[ip(Z[j][i],Z[j][i+1],gx(i),gx(i+1)),gy(j)],bot=[ip(Z[j+1][i],Z[j+1][i+1],gx(i),gx(i+1)),gy(j+1)],lef=[gx(i),ip(Z[j][i],Z[j+1][i],gy(j),gy(j+1))],rig=[gx(i+1),ip(Z[j][i+1],Z[j+1][i+1],gy(j),gy(j+1))];
      const segs={1:[lef,bot],2:[bot,rig],3:[lef,rig],4:[top,rig],5:[top,lef,bot,rig],6:[top,bot],7:[top,lef],8:[top,lef],9:[top,bot],10:[top,rig,lef,bot],11:[top,rig],12:[lef,rig],13:[bot,rig],14:[lef,bot]}[idx];for(let q=0;q<segs.length;q+=2)lines+=`<line x1="${xOf(segs[q][0])}" y1="${yOf(segs[q][1])}" x2="${xOf(segs[q+1][0])}" y2="${yOf(segs[q+1][1])}" stroke="${c}" stroke-width="${FIG_PT*0.7}" stroke-opacity="${0.35+0.6*k/L}"/>`;}}
  body=`<g data-sel="series:0">${body}${lines}${o.d2Points?pts.map(p=>sym(xOf(p.x),yOf(p.y),0,'#000','solid')).join(''):''}</g>`;const r=F.wrap(body);r.res={n,hx,hy,levels:L};return r;}
// Precision–Recall
function figRenderPR(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});if(!d.groups.length)return {svg:'',w:0,h:0};
  const res=d.groups.map(g=>{const all=g.pos.map(v=>({v,y:1})).concat(g.neg.map(v=>({v,y:0}))).sort((a,b)=>b.v-a.v);const P=g.pos.length;let tp=0,fp=0,ap=0,prevR=0;const pts=[{r:0,p:1}];for(let i=0;i<all.length;i++){if(all[i].y)tp++;else fp++;if(i+1<all.length&&all[i+1].v===all[i].v)continue;const r=tp/P,p=tp/(tp+fp);ap+=(r-prevR)*p;prevR=r;pts.push({r,p});}return {name:g.name,pts,ap,prev:P/all.length};});
  const ticks=[0,0.2,0.4,0.6,0.8,1].map(v=>({v,l:v.toFixed(1)}));const sq=(spec.opts||{}).wIn==null&&(spec.opts||{}).hIn==null;const F=figFrame(spec,{x:{lo:0,hi:1,ticks},y:{lo:0,hi:1,ticks},xTitle:o.xTitle||'Recall',yTitle:o.yTitle||'Precision',wIn:sq?2.5:0,hIn:sq?2.5:0});const {xOf,yOf,S,txt,fs,x0,y0,dash}=F;
  let body=`<line x1="${xOf(0)}" y1="${yOf(res[0].prev)}" x2="${xOf(1)}" y2="${yOf(res[0].prev)}" stroke="#888" stroke-width="${FIG_PT}" stroke-dasharray="${dash}"/>`;res.forEach((r,i)=>{body+=`<g data-sel="series:${i}"><polyline points="${r.pts.map(p=>`${xOf(p.r)},${yOf(p.p)}`).join(' ')}" fill="none" stroke="${S(i).color}" stroke-width="${S(i).lineW*FIG_PT*1.5}"/></g>`;});
  let leg='';res.forEach((r,i)=>{leg+=txt(x0+fs*0.4,y0-fs*0.5-(res.length-1-i)*fs*1.2,`${res.length>1?r.name+': ':''}AP ${r.ap.toFixed(3)}`,'start',`fill="${S(i).color}"`,null,fs*0.85);});
  const r=F.wrap(body+`<g data-sel="text">${leg}</g>`);r.res={pr:res.map(x=>({name:x.name,ap:x.ap,prev:x.prev}))};return r;}
// キャリブレーション曲線（予測確率を区間に分け、観測割合と比べる）
function figRenderCalib(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});if(!d.groups.length)return {svg:'',w:0,h:0};const nb=+o.calBins||10;
  const res=d.groups.map(g=>{const all=g.pos.map(v=>({v,y:1})).concat(g.neg.map(v=>({v,y:0}))).filter(a=>a.v>=0&&a.v<=1).sort((a,b)=>a.v-b.v);if(all.length<nb)return null;const bins=[];for(let b=0;b<nb;b++){const sl=all.slice(Math.floor(all.length*b/nb),Math.floor(all.length*(b+1)/nb));if(!sl.length)continue;const n=sl.length,k=sl.filter(a=>a.y).length,p=k/n;const z=1.959964;const den=1+z*z/n,ctr=(p+z*z/(2*n))/den,hw=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;bins.push({pred:mean(sl.map(a=>a.v)),obs:p,lo:Math.max(0,ctr-hw),hi:Math.min(1,ctr+hw),n});}
    const brier=mean(all.map(a=>(a.v-a.y)**2));let slope=null,icpt=null;try{const X=all.map(a=>[1,Math.log(Math.min(0.9999,Math.max(1e-4,a.v))/(1-Math.min(0.9999,Math.max(1e-4,a.v))))]);const lr=logisticReg(X,all.map(a=>a.y),['b0','b1']);if(!lr.error){icpt=lr.beta[0];slope=lr.beta[1];}}catch(e){}return {name:g.name,bins,brier,slope,icpt,n:all.length};}).filter(Boolean);if(!res.length)return {svg:'',w:0,h:0};
  const ticks=[0,0.2,0.4,0.6,0.8,1].map(v=>({v,l:v.toFixed(1)}));const sq=(spec.opts||{}).wIn==null&&(spec.opts||{}).hIn==null;const F=figFrame(spec,{x:{lo:0,hi:1,ticks},y:{lo:0,hi:1,ticks},xTitle:o.xTitle||'Predicted probability',yTitle:o.yTitle||'Observed proportion',wIn:sq?2.5:0,hIn:sq?2.5:0,legend:res.length>1?res.map((r,i)=>({name:r.name,kind:'sym',i})):[]});const {xOf,yOf,S,sym,a,dash,txt,fs,x0,y0}=F;
  let body=`<line x1="${xOf(0)}" y1="${yOf(0)}" x2="${xOf(1)}" y2="${yOf(1)}" stroke="#888" stroke-width="${FIG_PT}" stroke-dasharray="${dash}"/>`;res.forEach((r,i)=>{const c=S(i).color;let s=`<polyline points="${r.bins.map(b=>`${xOf(b.pred)},${yOf(b.obs)}`).join(' ')}" fill="none" stroke="${c}" stroke-width="${S(i).lineW*FIG_PT*1.2}"/>`;r.bins.forEach(b=>{s+=`<line x1="${xOf(b.pred)}" y1="${yOf(b.lo)}" x2="${xOf(b.pred)}" y2="${yOf(b.hi)}" stroke="${c}" stroke-width="${a}"/>`+sym(xOf(b.pred),yOf(b.obs),i,c,'solid');});body+=`<g data-sel="series:${i}">${s}</g>`;});
  let leg='';res.forEach((r,i)=>{leg+=txt(x0+fs*0.4,F.padT+fs*1.0+i*fs*1.2,`${res.length>1?r.name+': ':''}Brier ${r.brier.toFixed(3)}${r.slope!=null?`, slope ${r.slope.toFixed(2)}`:''}`,'start',`fill="${S(i).color}"`,null,fs*0.8);});
  const r=F.wrap(body+`<g data-sel="text">${leg}</g>`);r.res={cal:res};return r;}
// 決定曲線（Net benefit vs しきい値確率）
function figRenderDCA(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});if(!d.groups.length)return {svg:'',w:0,h:0};const xmax=+o.dcaXmax||1;
  const N=d.groups[0].pos.length+d.groups[0].neg.length;const prev=d.groups[0].pos.length/N;const thr=[];for(let t=0.01;t<xmax-1e-9;t+=0.01)thr.push(+t.toFixed(2));
  const res=d.groups.map(g=>({name:g.name,nb:thr.map(t=>{const tp=g.pos.filter(v=>v>=t).length,fp=g.neg.filter(v=>v>=t).length;return tp/N-fp/N*t/(1-t);})}));const all=thr.map(t=>prev-(1-prev)*t/(1-t));
  const ymax=Math.max(prev,...res.flatMap(r=>r.nb))*1.1||0.1;const ys=figAxisLin(-ymax*0.25,ymax,5);const xs=figAxisLin(0,xmax,5);
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Threshold probability',yTitle:o.yTitle||'Net benefit',legend:res.map((r,i)=>({name:r.name,kind:'line',i})).concat([{name:'Treat all',kind:'line',i:res.length,color:'#888'},{name:'Treat none',kind:'line',i:res.length+1,color:'#000'}])});const {xOf,yOf,S,dash}=F;
  const clip=v=>Math.max(ys.lo,Math.min(ys.hi,v));let body=`<polyline points="${thr.map((t,i)=>`${xOf(t)},${yOf(clip(all[i]))}`).join(' ')}" fill="none" stroke="#888" stroke-width="${FIG_PT*1.2}"/><line x1="${xOf(0)}" y1="${yOf(0)}" x2="${xOf(xmax)}" y2="${yOf(0)}" stroke="#000" stroke-width="${FIG_PT}" stroke-dasharray="${dash}"/>`;
  res.forEach((r,i)=>{body+=`<g data-sel="series:${i}"><polyline points="${thr.map((t,k)=>`${xOf(t)},${yOf(clip(r.nb[k]))}`).join(' ')}" fill="none" stroke="${S(i).color}" stroke-width="${S(i).lineW*FIG_PT*1.5}"/></g>`;});
  const out=F.wrap(body);out.res={prev,n:N,dca:res.map(r=>{const k=r.nb.indexOf(Math.max(...r.nb));return {name:r.name,best:thr[k],nbMax:r.nb[k]};})};return out;}
// 競合リスクの累積発生（Aalen–Johansen）。Event: 0 打ち切り、1 対象、2 以上 競合
function figRenderCIF(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});if(!d.parsed||!d.codes)return {svg:'',w:0,h:0};const cols=d.parsed.cols;const tC=cols.find(c=>c.name===d.tname);const gC=cols.find(c=>d.groups.length>1&&d.groups.some(g=>c.raw.includes(g.name)));if(!tC)return {svg:'',w:0,h:0};
  const rows=[];tC.vals.forEach((t,i)=>{if(t===null||d.codes[i]==null)return;rows.push({t,e:d.codes[i],g:gC?String(gC.raw[i]).trim():'all'});});const gnames=gC?d.groups.map(g=>g.name):['all'];const causes=[...new Set(rows.map(r=>r.e).filter(e=>e>0))].sort((a,b)=>a-b);
  const aj=(rs,cause)=>{const ts=[...new Set(rs.map(r=>r.t))].sort((a,b)=>a-b);let S=1,F=0;const pts=[{t:0,f:0}];for(const t of ts){const n=rs.filter(r=>r.t>=t).length;const dk=rs.filter(r=>r.t===t&&r.e===cause).length,dAll=rs.filter(r=>r.t===t&&r.e>0).length;if(n>0){F+=S*dk/n;S*=1-dAll/n;}pts.push({t,f:F});}return pts;};
  const curves=[];gnames.forEach((g,gi)=>{const rs=rows.filter(r=>r.g===g);if(!rs.length)return;causes.forEach(cz=>{if(cz!==causes[0]&&!o.cifAll)return;curves.push({g,gi,cause:cz,pts:aj(rs,cz),n:rs.length,ev:rs.filter(r=>r.e===cz).length});});});if(!curves.length)return {svg:'',w:0,h:0};
  const maxT=Math.max(...rows.map(r=>r.t));const xs=figAxisLin(0,maxT||1,6);xs.lo=0;const pct=o.survY!=='fraction';const ymax=Math.max(...curves.map(c=>c.pts[c.pts.length-1].f));const ys={lo:0,hi:pct?100:1,ticks:(pct?[0,20,40,60,80,100]:[0,0.2,0.4,0.6,0.8,1]).map(v=>({v,l:figFmt(v)}))};if(ymax<0.5){ys.hi=pct?60:0.6;ys.ticks=ys.ticks.filter(t=>t.v<=ys.hi);}
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||d.tname,yTitle:o.yTitle||(pct?'Cumulative incidence (%)':'Cumulative incidence'),legend:curves.map((c,i)=>({name:(gnames.length>1?c.g:'')+(o.cifAll?(gnames.length>1?' ':'')+'event '+c.cause:''),kind:'line',i:c.gi}))});const {xOf,yOf,S}=F;
  let body='';curves.forEach(c=>{const pts=[];c.pts.forEach((p,k)=>{if(k)pts.push(`${xOf(p.t)},${yOf(c.pts[k-1].f*(pct?100:1))}`);pts.push(`${xOf(p.t)},${yOf(p.f*(pct?100:1))}`);});pts.push(`${xOf(maxT)},${yOf(c.pts[c.pts.length-1].f*(pct?100:1))}`);body+=`<g data-sel="series:${c.gi}"><polyline points="${pts.join(' ')}" fill="none" stroke="${S(c.gi).color}" stroke-width="${S(c.gi).lineW*FIG_PT*1.5}"${c.cause!==causes[0]?` stroke-dasharray="${FIG_PT*3} ${FIG_PT*2}"`:''}/></g>`;});
  const r=F.wrap(body);r.res={curves:curves.map(c=>({g:c.g,cause:c.cause,n:c.n,ev:c.ev,last:c.pts[c.pts.length-1].f})),causes};return r;}
// ファンネルプロット（横＝効果量、縦＝SE。擬似 95% CI と Egger の検定）
function figRenderFunnel(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const rows=d.items.filter(it=>it.kind==='row'&&it.est!==null&&it.lo!==null&&it.hi!==null);if(rows.length<2)return {svg:'',w:0,h:0};
  const log=rows.every(it=>it.est>0&&it.lo>0)&&/\bor\b|\bhr\b|\brr\b|ratio|odds|hazard/i.test(d.ename+' '+(o.xTitle||'')+' '+(spec.title||''));const tr=v=>log?Math.log(v):v;const st=rows.map(it=>({name:it.label,y:tr(it.est),se:(tr(it.hi)-tr(it.lo))/3.919928}));
  const w=st.map(s=>1/(s.se*s.se));const pooled=st.reduce((a,s,i)=>a+s.y*w[i],0)/w.reduce((a,b)=>a+b,0);const seMax=Math.max(...st.map(s=>s.se))*1.1;
  let egger=null;if(o.funnelEgger&&st.length>=3){const X=st.map(s=>[1,1/s.se]),y=st.map(s=>s.y/s.se);const lr=linReg(X,y,['b0','b1']);if(!lr.error)egger={icpt:lr.beta[0],p:lr.ps[0],t:lr.tvals[0]};}
  const xr=Math.max(Math.abs(Math.min(...st.map(s=>s.y))-pooled),Math.abs(Math.max(...st.map(s=>s.y))-pooled),1.96*seMax)*1.1;const xs=figAxisLin(pooled-xr,pooled+xr,5,log?v=>figFmt(+Math.exp(v).toPrecision(2)):null);const ys=figAxisLin(0,seMax,4);
  const F=figFrame(spec,{x:xs,y:{lo:ys.hi,hi:ys.lo,ticks:ys.ticks},xTitle:o.xTitle||(log?d.ename+'（対数軸）':d.ename),yTitle:o.yTitle||'Standard error'});const {xOf,yOf,S,sym,dash,a}=F;
  let body=`<line x1="${xOf(pooled)}" y1="${yOf(0)}" x2="${xOf(pooled)}" y2="${yOf(seMax)}" stroke="#444" stroke-width="${a}"/><polyline points="${xOf(pooled-1.96*seMax)},${yOf(seMax)} ${xOf(pooled)},${yOf(0)} ${xOf(pooled+1.96*seMax)},${yOf(seMax)}" fill="none" stroke="#888" stroke-width="${FIG_PT}" stroke-dasharray="${dash}"/>`;
  body+=`<g data-sel="series:0">${st.map(s=>sym(xOf(s.y),yOf(s.se),0,S(0).color,'solid')).join('')}</g>`;const r=F.wrap(body);r.res={pooled:log?Math.exp(pooled):pooled,log,n:st.length,egger};return r;}
// Hi-C 接触行列
function figRenderHiC(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt}=st;const rows=d.rows,cols=d.cols,M=d.m;if(!rows.length||!cols.length)return {svg:'',w:0,h:0};
  const T=v=>v===null?null:(o.hicLog?Math.log10(1+Math.max(0,v)):v);const vals=M.flat().map(T).filter(v=>v!==null);const vmax=Math.max(...vals)||1;const scheme=FIG_HM_SCHEMES[o.hicScheme]||FIG_HM_SCHEMES.wr;
  const size=(+o.wIn||3)*FIG_IN;const cw=size/cols.length,ch=size/rows.length;const labEvery=Math.max(1,Math.ceil(cols.length/6));const padL=fs*3.2,padT=fs*2.2,padB=fs*2.6,padR=fs*3.5;const W=padL+size+padR,H=padT+size+padB;let body='';
  M.forEach((r,i)=>r.forEach((v,j)=>{const t=T(v);if(t===null)return;body+=`<rect x="${padL+j*cw}" y="${padT+i*ch}" width="${cw+0.3}" height="${ch+0.3}" fill="${figGrad(scheme,t/vmax)}" stroke="none"/>`;}));
  let axes=`<rect x="${padL}" y="${padT}" width="${size}" height="${size}" fill="none" stroke="#000" stroke-width="${FIG_PT*0.75}"/>`;cols.forEach((c,j)=>{if(j%labEvery)return;axes+=txt(padL+(j+0.5)*cw,padT+size+fs*1.1,c,'middle','',null,fs*0.8);});rows.forEach((rname,i)=>{if(i%labEvery)return;axes+=txt(padL-fs*0.3,padT+(i+0.5)*ch+fs*0.3,rname,'end','',null,fs*0.8);});
  const gid='hic'+Math.random().toString(36).slice(2,7);const bx=padL+size+fs*0.8,bw=fs*0.7;axes+=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${scheme.map((c,i)=>`<stop offset="${i/(scheme.length-1)}" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${bx}" y="${padT}" width="${bw}" height="${size}" fill="url(#${gid})" stroke="#000" stroke-width="${FIG_PT*0.5}"/>`+txt(bx+bw+fs*0.3,padT+fs*0.4,figFmt(+(o.hicLog?Math.pow(10,vmax)-1:vmax).toPrecision(2)),'start','',null,fs*0.75)+txt(bx+bw+fs*0.3,padT+size,'0','start','',null,fs*0.75);
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${axes}</g><g data-sel="series:0">${body}</g>`,{x0:padL,y0:padT,w:size,h:size});r.res={n:rows.length,m:cols.length,max:Math.max(...M.flat().filter(v=>v!==null)),log:!!o.hicLog};return r;}
// プロファイルヒートマップ（上＝列ごとの平均の線、下＝行を平均順に並べたヒートマップ）
function figRenderProfile(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,a}=st;let rows=d.rows.map((name,i)=>({name,v:d.m[i]}));const cols=d.cols;if(!rows.length||cols.length<2)return {svg:'',w:0,h:0};
  const rowMean=r=>{const v=r.v.filter(x=>x!==null);return v.length?mean(v):-Infinity;};if(o.profSort)rows.sort((p,q)=>rowMean(q)-rowMean(p));const prof=cols.map((_,j)=>{const v=rows.map(r=>r.v[j]).filter(x=>x!==null);return v.length?mean(v):0;});
  const vals=rows.flatMap(r=>r.v).filter(v=>v!==null);const vmax=quantile(vals,0.98)||1,vmin=Math.min(0,Math.min(...vals));const W0=(+o.wIn||2.2)*FIG_IN,hTop=FIG_IN*1.1,hHm=(+o.hIn||3)*FIG_IN;const padL=fs*3.2,padT=fs*2,padB=fs*2.4,padR=fs*3.6;const W=padL+W0+padR,H=padT+hTop+fs*1.2+hHm+padB;
  const pmax=Math.max(...prof)*1.1||1;const ty=v=>padT+hTop-v/pmax*hTop;let body=`<polyline points="${prof.map((v,j)=>`${padL+(j+0.5)*W0/cols.length},${ty(v)}`).join(' ')}" fill="none" stroke="${st.S(0).color}" stroke-width="${FIG_PT*1.5}"/>`;
  let axes=`<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${padT+hTop}" stroke="#000" stroke-width="${a}"/><line x1="${padL}" y1="${padT+hTop}" x2="${padL+W0}" y2="${padT+hTop}" stroke="#000" stroke-width="${a}"/>`+txt(padL-fs*0.3,padT+fs*0.35,figFmt(+pmax.toPrecision(2)),'end','',null,fs*0.75)+txt(padL-fs*0.3,padT+hTop,'0','end','',null,fs*0.75);
  const y0=padT+hTop+fs*1.2;const ch=hHm/rows.length,cw=W0/cols.length;const scheme=FIG_HM_SCHEMES.wb;let cells='';rows.forEach((r,i)=>r.v.forEach((v,j)=>{if(v===null)return;cells+=`<rect x="${padL+j*cw}" y="${y0+i*ch}" width="${cw+0.3}" height="${Math.max(ch,0.6)+0.3}" fill="${figGrad(scheme,(v-vmin)/(vmax-vmin||1))}" stroke="none"/>`;}));
  axes+=`<rect x="${padL}" y="${y0}" width="${W0}" height="${hHm}" fill="none" stroke="#000" stroke-width="${FIG_PT*0.75}"/>`;[0,Math.floor(cols.length/2),cols.length-1].forEach(j=>{axes+=txt(padL+(j+0.5)*cw,y0+hHm+fs*1.1,cols[j],'middle','',null,fs*0.8)+`<line x1="${padL+(j+0.5)*cw}" y1="${y0+hHm}" x2="${padL+(j+0.5)*cw}" y2="${y0+hHm+fs*0.3}" stroke="#000" stroke-width="${a}"/>`;});
  axes+=txt(padL-fs*0.3,y0+fs*0.8,`${rows.length} regions`,'end',`transform="rotate(-90 ${padL-fs*0.3} ${y0+hHm/2})"`,null,fs*0.8);const gid='pf'+Math.random().toString(36).slice(2,7);const bx=padL+W0+fs*0.8,bw=fs*0.7;axes+=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${scheme.map((c,i)=>`<stop offset="${i/(scheme.length-1)}" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${bx}" y="${y0}" width="${bw}" height="${hHm}" fill="url(#${gid})" stroke="#000" stroke-width="${FIG_PT*0.5}"/>`+txt(bx+bw+fs*0.3,y0+fs*0.4,figFmt(+vmax.toPrecision(2)),'start','',null,fs*0.75)+txt(bx+bw+fs*0.3,y0+hHm,figFmt(+vmin.toPrecision(2)),'start','',null,fs*0.75);
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${axes}</g><g data-sel="series:0">${body}${cells}</g>`,{x0:padL,y0:padT,w:W0,h:hTop+fs*1.2+hHm});r.res={rows:rows.length,bins:cols.length,peak:cols[prof.indexOf(Math.max(...prof))],vmax};return r;}
// 3D 散布（正射影）
function figRender3D(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,S,sym}=st;if(d.vars.length<3)return {svg:'',w:0,h:0};const pick=(re,used)=>{const i=d.vars.findIndex((v,k)=>re.test(v.toLowerCase())&&!used.includes(k));return i>=0?i:d.vars.findIndex((v,k)=>!used.includes(k));};const ix=pick(/^x$|^x[ _]/,[]),iy=pick(/^y$|^y[ _]/,[ix]),iz=pick(/^z$|^z[ _]/,[ix,iy]);
  const az=(+o.s3dAz||35)*Math.PI/180,el=(+o.s3dEl||25)*Math.PI/180;const rng=k=>{const v=d.X.map(r=>r[k]);const lo=Math.min(...v),hi=Math.max(...v);const t=figNiceTicks(lo,hi,4);return {lo:Math.min(lo,t.ticks[0]),hi:Math.max(hi,t.ticks[t.ticks.length-1]),ticks:t.ticks};};const rx=rng(ix),ry=rng(iy),rz=rng(iz);
  const size=(+o.wIn||3)*FIG_IN;const cx=size*0.55+fs*2,cy=size*0.5+fs*1.6;const W=size*1.15+fs*4+(d.groups.length?fs*7:0),H=size*1.05+fs*3.2;const n=v=>(v-0.5);
  const proj=(x,y,z)=>{const X=n((x-rx.lo)/(rx.hi-rx.lo)),Y=n((y-ry.lo)/(ry.hi-ry.lo)),Z=n((z-rz.lo)/(rz.hi-rz.lo));const xr=X*Math.cos(az)-Y*Math.sin(az),yr=X*Math.sin(az)+Y*Math.cos(az);const px=cx+xr*size*0.8,py=cy-(Z*Math.cos(el)*size*0.75)+yr*Math.sin(el)*size*0.8;const depth=yr*Math.cos(el)+Z*Math.sin(el);return [px,py,depth];};
  const corner=(a,b,c)=>proj(a?rx.hi:rx.lo,b?ry.hi:ry.lo,c?rz.hi:rz.lo);let axes='';const edges=[[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1],[1,0,0,1,1,0],[1,0,0,1,0,1],[0,1,0,1,1,0],[0,1,0,0,1,1],[0,0,1,1,0,1],[0,0,1,0,1,1],[1,1,0,1,1,1],[1,0,1,1,1,1],[0,1,1,1,1,1]];
  edges.forEach(e=>{const p=corner(e[0],e[1],e[2]),q=corner(e[3],e[4],e[5]);const back=(p[2]+q[2])/2<0;axes+=`<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="${back?'#bbb':'#000'}" stroke-width="${FIG_PT*(back?0.5:0.9)}"${back?` stroke-dasharray="${FIG_PT*2} ${FIG_PT*2}"`:''}/>`;});
  rx.ticks.forEach(v=>{const p=proj(v,ry.lo,rz.lo);axes+=txt(p[0],p[1]+fs*1.1,figFmt(v),'middle','',null,fs*0.75);});ry.ticks.forEach(v=>{const p=proj(rx.hi,v,rz.lo);axes+=txt(p[0]+fs*0.4,p[1]+fs*0.4,figFmt(v),'start','',null,fs*0.75);});rz.ticks.forEach(v=>{const p=proj(rx.lo,ry.lo,v);axes+=txt(p[0]-fs*0.4,p[1]+fs*0.3,figFmt(v),'end','',null,fs*0.75);});
  const lx=proj((rx.lo+rx.hi)/2,ry.lo,rz.lo),ly=proj(rx.hi,(ry.lo+ry.hi)/2,rz.lo),lz=proj(rx.lo,ry.lo,(rz.lo+rz.hi)/2);axes+=txt(lx[0],lx[1]+fs*2.2,o.xTitle||d.vars[ix],'middle')+txt(ly[0]+fs*2.2,ly[1]+fs*0.4,d.vars[iy],'start')+txt(lz[0]-fs*2.4,lz[1],o.yTitle||d.vars[iz],'middle',`transform="rotate(-90 ${lz[0]-fs*2.4} ${lz[1]})"`);
  const gi=g=>d.groups.findIndex(x=>x.name===g);const pts=d.X.map((r,k)=>{const p=proj(r[ix],r[iy],r[iz]);return {p,g:d.group?gi(d.group[k]):0};}).sort((a,b)=>a.p[2]-b.p[2]);const series={};pts.forEach(q=>{const c=S(q.g).color;series[q.g]=(series[q.g]||'')+sym(q.p[0],q.p[1],q.g,c,S(q.g).fill);});
  let body='';Object.keys(series).forEach(g=>body+=`<g data-sel="series:${g}">${series[g]}</g>`);let leg='';d.groups.forEach((g,k)=>{const y=fs*2+k*fs*1.5;leg+=sym(W-fs*6,y-fs*0.2,k,S(k).color,'solid')+txt(W-fs*5.2,y+fs*0.15,S(k).name||g.name,'start');});
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${axes}</g>${body}${leg?`<g data-sel="legend">${leg}</g>`:''}`,{x0:cx-size*0.5,y0:cy-size*0.45,w:size,h:size*0.9});r.res={n:d.X.length,vars:[d.vars[ix],d.vars[iy],d.vars[iz]]};return r;}
// ガントチャート（swimmer のデータ: Task, Start, End, Group）
function figRenderGantt(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const items=d.items.slice().sort((p,q)=>p.start-q.start||p.end-q.end);const n=items.length;if(!n)return {svg:'',w:0,h:0};
  const tmin=Math.min(...items.map(it=>it.start)),tmax=Math.max(...items.map(it=>it.end));const xs=figAxisLin(tmin,tmax+(tmax-tmin)*0.05||1,6);const ys={lo:0,hi:n,cat:true,ticks:items.map((it,i)=>({v:n-i-0.5,l:it.id}))};
  const legend=d.groups.map((g,i)=>({name:g.name,kind:'rect',i}));const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||d.tname,legend,hIn:figDefSize(spec,'hIn')?Math.max(1.2,n*0.24):0,padL:Math.max(0,Math.max(...items.map(it=>figTW(it.id,F0(o))))-F0(o)*1.6),xAxisAt:null});const {xOf,yOf,S,a,fs,txt}=F;const rowH=yOf(0)-yOf(1),bh=rowH*0.62;
  let body='';items.forEach((it,i)=>{const gi=Math.max(0,d.groups.findIndex(g=>g.name===it.group));const c=S(gi).color;const y=yOf(n-i-0.5)-bh/2;body+=`<g data-sel="series:${gi}"><rect x="${xOf(it.start)}" y="${y}" width="${Math.max(1,xOf(it.end)-xOf(it.start))}" height="${bh}" fill="${c}" stroke="#333" stroke-width="${FIG_PT*0.4}" rx="${FIG_PT}"/>${it.events.map(e=>`<line x1="${xOf(e.t)}" y1="${y}" x2="${xOf(e.t)}" y2="${y+bh}" stroke="#000" stroke-width="${a*1.5}"/>`).join('')}</g>`;});
  if(o.ganttNow!==''&&isFinite(+o.ganttNow))body+=`<line x1="${xOf(+o.ganttNow)}" y1="${yOf(n)}" x2="${xOf(+o.ganttNow)}" y2="${yOf(0)}" stroke="#DC2626" stroke-width="${FIG_PT}" stroke-dasharray="${FIG_PT*3} ${FIG_PT*2}"/>`;
  const r=F.wrap(body);r.res={n,span:[tmin,tmax],groups:d.groups.map(g=>({name:g.name,n:items.filter(it=>it.group===g.name).length}))};return r;}
// ワードクラウド（螺旋に置き、矩形で重なりを避ける）
function figRenderWordCloud(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,S}=st;const items=d.items.filter(it=>it.v>0).sort((p,q)=>q.v-p.v).slice(0,120);if(!items.length)return {svg:'',w:0,h:0};
  const W=(figDefSize(spec,'wIn')?5.5:+o.wIn)*FIG_IN,H=(figDefSize(spec,'hIn')?3.4:+o.hIn)*FIG_IN;const vmax=items[0].v,vmin=items[items.length-1].v;const fmax=Math.min((+o.wcMax||44)*FIG_PT,H/3.5),fmin=Math.min(9*FIG_PT,fmax*0.5);const sizeOf=v=>fmin+(fmax-fmin)*Math.sqrt((v-vmin)/(vmax-vmin||1));
  const placed=[];const hit=(x,y,w,h)=>placed.some(p=>!(x+w<p.x||p.x+p.w<x||y+h<p.y||p.y+p.h<y))||x<0||y<fs*1.5||x+w>W||y+h>H;let body='';const R=figRng(3);
  items.forEach((it,k)=>{let size=sizeOf(it.v);const a0=R.u()*6.28;for(let shrink=0;shrink<4;shrink++){const w=figTW(it.name,size)*1.05,h=size*1.05;let ok=false;for(let t=0;t<2400&&!ok;t+=1){const r=t*0.5,ang=a0+t*0.25;const x=W/2+Math.cos(ang)*r-w/2,y=H/2+fs*0.6+Math.sin(ang)*r*0.6-h/2;if(!hit(x,y,w,h)){placed.push({x,y,w,h});body+=txt(x+w/2,y+h*0.78,it.name,'middle',`fill="${S(k%6).color}"`,null,size);ok=true;}}if(ok)break;size*=0.8;}});
  const r=figWrap5(spec,st,W,H,`<g data-sel="series:0">${body}</g>`,{x0:0,y0:fs*1.5,w:W,h:H-fs*1.5});r.res={n:items.length,placed:placed.length,top:items.slice(0,5)};return r;}
// Circos（染色体の円環とリンク）
function figRenderCircos(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,S}=st;const cols=d.parsed.cols;const f=re=>cols.find(c=>re.test(figLC5(c)))||null;const c1=f(/^(from|chr1|chr_?a|source|from_?chr)$/)||cols[0],p1=f(/^(from_?pos|pos1|start1|frompos|bp1)$/),c2=f(/^(to|chr2|chr_?b|target|to_?chr)$/),p2=f(/^(to_?pos|pos2|start2|topos|bp2)$/),vC=f(/^(value|weight|count|n|support)$/);if(!c1||!p1||!c2||!p2)return figOmEmpty('From, FromPos, To, ToPos の列が必要です');
  const links=[];for(let i=0;i<p1.vals.length;i++){if(p1.vals[i]===null||p2.vals[i]===null)continue;links.push({a:figChrKey(c1.raw[i]),pa:p1.vals[i],b:figChrKey(c2.raw[i]),pb:p2.vals[i],v:vC?vC.vals[i]:1});}if(!links.length)return figOmEmpty('リンクがありません');
  const chrs=[...new Set(links.flatMap(l=>[l.a,l.b]))].sort(figChrOrder);const len={};chrs.forEach(c=>{len[c]=FIG_CHR_LEN[c]||Math.max(...links.flatMap(l=>[l.a===c?l.pa:0,l.b===c?l.pb:0]))*1.1||1;});const total=chrs.reduce((a,c)=>a+len[c],0);const gap=0.012;const start={};let acc=0;chrs.forEach(c=>{start[c]=acc;acc+=len[c]/total*(1-gap*chrs.length)+gap;});
  const R=Math.min(+o.wIn||3,+o.hIn||3)*FIG_IN*0.46;const cx=R+fs*3,cy=R+fs*3;const W=2*cx,H=2*cy;const ang=(c,pos)=>-Math.PI/2+2*Math.PI*(start[c]+pos/len[c]*(len[c]/total*(1-gap*chrs.length)));const pt=(a,r)=>[cx+Math.cos(a)*r,cy+Math.sin(a)*r];
  const pal=FIG_PAL20||FIG_DEF.colors;let ideo='';chrs.forEach((c,i)=>{const a0=ang(c,0),a1=ang(c,len[c]);const o1=pt(a0,R),o2=pt(a1,R),i1=pt(a0,R*0.92),i2=pt(a1,R*0.92);const big=a1-a0>Math.PI?1:0;ideo+=`<path d="M${o1[0]},${o1[1]} A${R},${R} 0 ${big} 1 ${o2[0]},${o2[1]} L${i2[0]},${i2[1]} A${R*0.92},${R*0.92} 0 ${big} 0 ${i1[0]},${i1[1]} Z" fill="${pal[i%pal.length]}" stroke="#333" stroke-width="${FIG_PT*0.4}"/>`;if(o.cxLabels){const am=(a0+a1)/2;const l=pt(am,R*1.07);ideo+=txt(l[0],l[1]+fs*0.3,String(c),'middle','',null,fs*0.8);}});
  const vmax=Math.max(...links.map(l=>l.v||1));let body='';links.forEach(l=>{const A=pt(ang(l.a,l.pa),R*0.9),B=pt(ang(l.b,l.pb),R*0.9);const ci=chrs.indexOf(l.a);body+=`<path d="M${A[0]},${A[1]} Q${cx},${cy} ${B[0]},${B[1]}" fill="none" stroke="${pal[ci%pal.length]}" stroke-width="${FIG_PT*(0.6+1.6*(l.v||1)/vmax)}" stroke-opacity="0.6"/>`;});
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${ideo}</g><g data-sel="series:0">${body}</g>`,{x0:cx-R,y0:cy-R,w:2*R,h:2*R});r.res={links:links.length,inter:links.filter(l=>l.a!==l.b).length,chrs:chrs.length};return r;}
// コピー数（セグメント）
function figRenderCNV(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const f=re=>cols.find(c=>re.test(figLC5(c)))||null;const chrC=f(/^(chr|chrom|chromosome|染色体)$/),sC=f(/^(start|loc\.start|開始)$/),eC=f(/^(end|loc\.end|終了)$/),vC=f(/log2|ratio|seg\.?mean|segment_mean|cn|copy|値/);if(!chrC||!sC||!vC)return figOmEmpty('Chr, Start, End, log2 の列が必要です');
  const segs=[];for(let i=0;i<sC.vals.length;i++){if(sC.vals[i]===null||vC.vals[i]===null)continue;segs.push({c:figChrKey(chrC.raw[i]),s:sC.vals[i],e:eC&&eC.vals[i]!==null?eC.vals[i]:sC.vals[i],v:vC.vals[i]});}if(!segs.length)return figOmEmpty('セグメントがありません');
  const chrs=[...new Set(segs.map(s=>s.c))].sort(figChrOrder);const len={};chrs.forEach(c=>{len[c]=FIG_CHR_LEN[c]||Math.max(...segs.filter(s=>s.c===c).map(s=>s.e))*1.02;});const off={};let acc=0;chrs.forEach(c=>{off[c]=acc;acc+=len[c];});const thr=+o.cnvThr||0.3;
  const vmax=Math.max(1,...segs.map(s=>Math.abs(s.v)))*1.1;const ys=figAxisLin(-vmax,vmax,5);const xs={lo:0,hi:acc,ticks:chrs.map(c=>({v:off[c]+len[c]/2,l:String(c)}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Chromosome',yTitle:o.yTitle||vC.name,wIn:figDefSize(spec,'wIn')?6:0,hIn:figDefSize(spec,'hIn')?1.8:0});const {xOf,yOf,a,dash}=F;
  let body=`<line x1="${xOf(0)}" y1="${yOf(0)}" x2="${xOf(acc)}" y2="${yOf(0)}" stroke="#444" stroke-width="${FIG_PT*0.6}"/>`;[thr,-thr].forEach(t=>body+=`<line x1="${xOf(0)}" y1="${yOf(t)}" x2="${xOf(acc)}" y2="${yOf(t)}" stroke="#aaa" stroke-width="${FIG_PT*0.5}" stroke-dasharray="${dash}"/>`);chrs.forEach((c,i)=>{if(i)body+=`<line x1="${xOf(off[c])}" y1="${yOf(ys.lo)}" x2="${xOf(off[c])}" y2="${yOf(ys.hi)}" stroke="#ccc" stroke-width="${FIG_PT*0.5}"/>`;});
  let s='';segs.forEach(sg=>{const col=sg.v>=thr?'#DC2626':sg.v<=-thr?'#1D4ED8':'#555';s+=`<line x1="${xOf(off[sg.c]+sg.s)}" y1="${yOf(sg.v)}" x2="${xOf(off[sg.c]+Math.max(sg.e,sg.s+acc/600))}" y2="${yOf(sg.v)}" stroke="${col}" stroke-width="${a*2.2}" stroke-linecap="round"/>`;});
  const r=F.wrap(body+`<g data-sel="series:0">${s}</g>`);r.res={n:segs.length,gain:segs.filter(x=>x.v>=thr).length,loss:segs.filter(x=>x.v<=-thr).length,thr};return r;}
// UMAP の軌跡（pseudotime で色、区間平均をつないだ曲線に矢印）
function figRenderTrajectory(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const f=re=>cols.find(c=>re.test(figLC5(c)))||null;const X=d.x||f(/^x$|_1$/),Y=d.y||f(/^y$|_2$/),T=f(/pseudotime|time|order|擬似時間/),L=f(/^(lineage|branch|path|trajectory)$/);if(!X||!Y||!T)return figOmEmpty('x, y, pseudotime の列が必要です');
  const pts=[];X.vals.forEach((x,i)=>{const y=Y.vals[i],t=T.vals[i];if(x===null||y===null||t===null)return;pts.push({x,y,t,l:L?String(L.raw[i]||'').trim():''});});if(pts.length<4)return figOmEmpty('点が足りません');
  const tmin=Math.min(...pts.map(p=>p.t)),tmax=Math.max(...pts.map(p=>p.t));const xp=(Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x)))*0.08||1,yp=(Math.max(...pts.map(p=>p.y))-Math.min(...pts.map(p=>p.y)))*0.08||1;const xs=figAxisLin(Math.min(...pts.map(p=>p.x))-xp,Math.max(...pts.map(p=>p.x))+xp,5),ys=figAxisLin(Math.min(...pts.map(p=>p.y))-yp,Math.max(...pts.map(p=>p.y))+yp,5);
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||X.name,yTitle:o.yTitle||Y.name,padR:F0(o)*3.5});const {xOf,yOf,fs,txt,x0,plotW,padT,plotH}=F;const lut=FIG_LUTS.viridis;const r0=FIG_PT*1.6;
  let body='';pts.forEach(p=>body+=`<circle cx="${xOf(p.x)}" cy="${yOf(p.y)}" r="${r0}" fill="${figGrad(lut,(p.t-tmin)/(tmax-tmin||1))}" fill-opacity="0.8"/>`);
  const lines=[...new Set(pts.map(p=>p.l))];const nb=+o.trajBins||20;let curves='';lines.forEach(ln=>{const ps=pts.filter(p=>p.l===ln).sort((a,b)=>a.t-b.t);if(ps.length<4)return;const bins=[];for(let b=0;b<nb;b++){const sl=ps.slice(Math.floor(ps.length*b/nb),Math.floor(ps.length*(b+1)/nb));if(sl.length)bins.push({x:mean(sl.map(p=>p.x)),y:mean(sl.map(p=>p.y))});}const sm=bins.map((b,i)=>{const w=bins.slice(Math.max(0,i-1),i+2);return {x:mean(w.map(q=>q.x)),y:mean(w.map(q=>q.y))};});
    curves+=`<polyline points="${sm.map(b=>`${xOf(b.x)},${yOf(b.y)}`).join(' ')}" fill="none" stroke="#000" stroke-width="${FIG_PT*1.6}" stroke-linejoin="round"/>`;const e=sm[sm.length-1],q=sm[sm.length-2];const ang=Math.atan2(yOf(e.y)-yOf(q.y),xOf(e.x)-xOf(q.x));const hl=fs*0.8;curves+=`<polygon points="${xOf(e.x)},${yOf(e.y)} ${xOf(e.x)-hl*Math.cos(ang-0.4)},${yOf(e.y)-hl*Math.sin(ang-0.4)} ${xOf(e.x)-hl*Math.cos(ang+0.4)},${yOf(e.y)-hl*Math.sin(ang+0.4)}" fill="#000"/>`;if(ln)curves+=txt(xOf(e.x)+fs*0.5,yOf(e.y),ln,'start','',null,fs*0.85);});
  const gid='tj'+Math.random().toString(36).slice(2,7);const bx=x0+plotW+fs*0.8,bw=fs*0.6;const bar=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${lut.map((c,i)=>`<stop offset="${i/(lut.length-1)}" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${bx}" y="${padT}" width="${bw}" height="${plotH*0.6}" fill="url(#${gid})" stroke="#000" stroke-width="${FIG_PT*0.5}"/>`+txt(bx+bw+fs*0.3,padT+fs*0.4,figFmt(+tmax.toPrecision(2)),'start','',null,fs*0.75)+txt(bx+bw+fs*0.3,padT+plotH*0.6,figFmt(+tmin.toPrecision(2)),'start','',null,fs*0.75)+txt(bx+bw/2,padT+plotH*0.6+fs*1.2,T.name,'middle','',null,fs*0.75);
  const r=F.wrap(`<g data-sel="series:0">${body}${curves}</g>`,bar);r.res={n:pts.length,lineages:lines.filter(Boolean),tRange:[tmin,tmax]};return r;}
// ロリポップ（Position, Value, Label, Type）
function figRenderLollipop(spec){const d=spec.data;const o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const f=re=>cols.find(c=>re.test(figLC5(c)))||null;const pC=f(/^(position|pos|x|aa|residue|位置)$/)||cols.find(c=>c.vals.some(v=>v!==null)),vC=f(/^(value|count|n|height|value|y|頻度|値)$/)||cols.find(c=>c!==pC&&c.vals.some(v=>v!==null)),lC=f(/^(label|name|mutation|名前|変異)$/),tC=f(/^(type|class|group|種類)$/);if(!pC||!vC)return figOmEmpty('Position, Value の列が必要です');
  const numeric=pC.vals.filter(v=>v!==null).length>=pC.raw.filter(v=>v!=='').length*0.8;const items=[];for(let i=0;i<vC.vals.length;i++){if(vC.vals[i]===null)continue;items.push({p:numeric?pC.vals[i]:i,pl:String(pC.raw[i]||''),v:vC.vals[i],label:lC?String(lC.raw[i]||''):'',type:tC?String(tC.raw[i]||''):''});}if(!items.length)return figOmEmpty('データがありません');
  const types=[...new Set(items.map(it=>it.type))];const vmax=Math.max(...items.map(it=>it.v));const ys=figAxisLin(Math.min(0,...items.map(it=>it.v)),vmax*1.15||1,5);const xs=numeric?figAxisLin(Math.min(...items.map(it=>it.p)),Math.max(...items.map(it=>it.p)),6):{lo:0,hi:items.length,cat:true,ticks:items.map((it,i)=>({v:i+0.5,l:it.pl}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||pC.name,yTitle:o.yTitle||vC.name,legend:types.length>1?types.map((t,i)=>({name:t,kind:'sym',i})):[],xRot:numeric?0:(items.length>8?45:0)});const {xOf,yOf,S,sym,a,fs,txt}=F;
  const top=+o.lolTop||0;const topSet=new Set(items.slice().sort((p,q)=>q.v-p.v).slice(0,top));let body='';items.forEach((it,i)=>{const gi=Math.max(0,types.indexOf(it.type));const c=S(gi).color;const x=xOf(numeric?it.p:i+0.5);body+=`<g data-sel="series:${gi}"><line x1="${x}" y1="${yOf(0)}" x2="${x}" y2="${yOf(it.v)}" stroke="#777" stroke-width="${a}"/>${sym(x,yOf(it.v),gi,c,'solid')}${topSet.has(it)&&it.label?txt(x,yOf(it.v)-fs*0.8,it.label,'middle','',null,fs*0.75):''}</g>`;});
  const r=F.wrap(body);r.res={n:items.length,top:items.slice().sort((p,q)=>q.v-p.v).slice(0,5).map(it=>({label:it.label||it.pl,v:it.v}))};return r;}
// UpSet
function figRenderUpset(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,a,S}=st;const sets=d.sets,M=d.M;if(!M.length)return {svg:'',w:0,h:0};
  const sizes=sets.map((_,j)=>M.filter(r=>r[j]).length);const order=sets.map((_,j)=>j).sort((p,q)=>sizes[q]-sizes[p]);const combos={};M.forEach(r=>{const k=r.join('');combos[k]=(combos[k]||0)+1;});let list=Object.entries(combos).map(([k,n])=>({mask:k.split('').map(Number),n})).sort((p,q)=>q.n-p.n||p.mask.reduce((s,v)=>s+v,0)-q.mask.reduce((s,v)=>s+v,0)).slice(0,+o.upsetN||15);
  const nS=sets.length,nC=list.length;const cell=fs*1.5;const labW=Math.max(...sets.map(s=>figTW(s,fs)))+fs*0.6;const setBarW=fs*5;const barH=(+o.hIn||2)*FIG_IN*0.55;const padT=fs*3;const x0=labW+setBarW+fs*1.5,y0=padT+barH+fs*0.8;const W=x0+nC*cell+fs,H=y0+nS*cell+fs*0.8;
  const nmax=Math.max(...list.map(c=>c.n));const t=figNiceTicks(0,nmax,4);const bmax=t.ticks[t.ticks.length-1]||nmax;const by=v=>y0-fs*0.8-v/bmax*barH;let body='',axes=`<line x1="${x0-fs*0.3}" y1="${by(0)}" x2="${x0-fs*0.3}" y2="${by(bmax)}" stroke="#000" stroke-width="${a}"/>`;t.ticks.forEach(v=>{axes+=`<line x1="${x0-fs*0.3}" y1="${by(v)}" x2="${x0-fs*0.6}" y2="${by(v)}" stroke="#000" stroke-width="${a}"/>`+txt(x0-fs*0.75,by(v)+fs*0.35,figFmt(v),'end','',null,fs*0.8);});axes+=txt(x0-fs*2.6,(by(0)+by(bmax))/2,'Intersection size','middle',`transform="rotate(-90 ${x0-fs*2.6} ${(by(0)+by(bmax))/2})"`,null,fs*0.85);
  list.forEach((c,i)=>{const x=x0+i*cell;body+=`<rect x="${x+cell*0.15}" y="${by(c.n)}" width="${cell*0.7}" height="${by(0)-by(c.n)}" fill="${S(0).color}"/>`+txt(x+cell/2,by(c.n)-fs*0.3,String(c.n),'middle','',null,fs*0.75);const on=order.map((j,k)=>c.mask[j]?k:-1).filter(k=>k>=0);if(on.length>1)body+=`<line x1="${x+cell/2}" y1="${y0+(on[0]+0.5)*cell}" x2="${x+cell/2}" y2="${y0+(on[on.length-1]+0.5)*cell}" stroke="#000" stroke-width="${a*2}"/>`;order.forEach((j,k)=>{body+=`<circle cx="${x+cell/2}" cy="${y0+(k+0.5)*cell}" r="${cell*0.26}" fill="${c.mask[j]?'#000':'#ddd'}"/>`;});});
  const smax=Math.max(...sizes);order.forEach((j,k)=>{const y=y0+(k+0.5)*cell;if(k%2)axes+=`<rect x="${labW+setBarW+fs*0.9}" y="${y-cell/2}" width="${nC*cell+fs*0.6}" height="${cell}" fill="#f3f3f3"/>`;body+=`<rect x="${labW+setBarW-sizes[j]/smax*setBarW}" y="${y-cell*0.3}" width="${sizes[j]/smax*setBarW}" height="${cell*0.6}" fill="#777"/>`+txt(labW-fs*0.3,y+fs*0.35,sets[j],'end','',null,fs*0.9);});axes+=txt(labW+setBarW/2,H-fs*0.1,'Set size','middle','',null,fs*0.8);
  const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${axes}</g><g data-sel="series:0">${body}</g>`,{x0,y0:by(bmax),w:nC*cell,h:H-by(bmax)});r.res={n:M.length,sizes:sets.map((s,j)=>({name:s,n:sizes[j]})),top:list.slice(0,8).map(c=>({sets:sets.filter((_,j)=>c.mask[j]).join(' ∩ '),n:c.n}))};return r;}
// ノモグラム（ロジスティック回帰の係数から点数の目盛を作る）
function figRenderNomogram(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,a}=st;const vars=d.vars;if(!vars.length)return {svg:'',w:0,h:0};const maxPts=+o.nomoPts||100;
  const contrib=v=>v.levels.length?{min:Math.min(...v.levels.map(l=>l.coef)),max:Math.max(...v.levels.map(l=>l.coef))}:{min:Math.min(v.coef*v.min,v.coef*v.max),max:Math.max(v.coef*v.min,v.coef*v.max)};const ranges=vars.map(contrib);const span=Math.max(...ranges.map(r=>r.max-r.min))||1;const ptsPer=maxPts/span;
  const labW=Math.max(fs*5,...vars.map(v=>figTW(v.name,fs)))+fs*0.6;const axW=(+o.wIn||4.5)*FIG_IN;const rowH=fs*2.9;const padT=fs*2.2;const W=labW+axW+fs*2,H=padT+rowH*(vars.length+3)+fs;const x0=labW+fs*0.5;let body='';
  const axis=(y,label,lo,hi,ticks,fmt)=>{let s=`<line x1="${x0}" y1="${y}" x2="${x0+axW}" y2="${y}" stroke="#000" stroke-width="${a}"/>`+txt(x0-fs*0.5,y+fs*0.35,label,'end');ticks.forEach(t=>{const x=x0+(t-lo)/(hi-lo||1)*axW;s+=`<line x1="${x}" y1="${y}" x2="${x}" y2="${y-fs*0.4}" stroke="#000" stroke-width="${a}"/>`+txt(x,y-fs*0.6,fmt?fmt(t):figFmt(t),'middle','',null,fs*0.75);});return s;};
  let y=padT+rowH*0.5;body+=axis(y,'Points',0,maxPts,figNiceTicks(0,maxPts,10).ticks,null);
  vars.forEach((v,i)=>{y=padT+rowH*(i+1.5);const r=ranges[i];if(v.levels.length){body+=`<line x1="${x0}" y1="${y}" x2="${x0+(r.max-r.min)*ptsPer/maxPts*axW}" y2="${y}" stroke="#000" stroke-width="${a}"/>`+txt(x0-fs*0.5,y+fs*0.35,v.name,'end');v.levels.forEach((l,k)=>{const x=x0+(l.coef-r.min)*ptsPer/maxPts*axW;body+=`<line x1="${x}" y1="${y}" x2="${x}" y2="${y-fs*0.4}" stroke="#000" stroke-width="${a}"/>`+txt(x,y+(k%2?fs*1.2:-fs*0.6),l.name,'middle','',null,fs*0.75);});}
    else{const lo=v.coef>=0?v.min:v.max,hi=v.coef>=0?v.max:v.min;const t=figNiceTicks(Math.min(v.min,v.max),Math.max(v.min,v.max),6).ticks.filter(x=>x>=Math.min(v.min,v.max)-1e-9&&x<=Math.max(v.min,v.max)+1e-9);body+=`<line x1="${x0}" y1="${y}" x2="${x0+(r.max-r.min)*ptsPer/maxPts*axW}" y2="${y}" stroke="#000" stroke-width="${a}"/>`+txt(x0-fs*0.5,y+fs*0.35,v.name,'end');t.forEach(tv=>{const x=x0+Math.abs(v.coef)*(tv-lo)/(hi-lo||1)*ptsPer*(hi-lo>0?1:1)/maxPts*axW*Math.sign(hi-lo)*(v.coef>=0?1:-1);const xx=x0+(v.coef*tv-r.min)*ptsPer/maxPts*axW;body+=`<line x1="${xx}" y1="${y}" x2="${xx}" y2="${y-fs*0.4}" stroke="#000" stroke-width="${a}"/>`+txt(xx,y-fs*0.6,figFmt(tv),'middle','',null,fs*0.75);});}});
  const totalMax=ranges.reduce((s,r)=>s+(r.max-r.min),0)*ptsPer;y=padT+rowH*(vars.length+1.5);body+=axis(y,'Total points',0,totalMax,figNiceTicks(0,totalMax,8).ticks.filter(t=>t<=totalMax),null);
  const lpMin=d.intercept+ranges.reduce((s,r)=>s+r.min,0);const risk=p=>1/(1+Math.exp(-(lpMin+p/ptsPer)));y=padT+rowH*(vars.length+2.5);let rt=[0.01,0.05,0.1,0.2,0.3,0.5,0.7,0.8,0.9,0.95,0.99].filter(p=>p>risk(0)&&p<risk(totalMax)).map(p=>(Math.log(p/(1-p))-lpMin)*ptsPer);{const minGap=fs*2.4*totalMax/axW;const keep=[];rt.forEach(t=>{if(!keep.length||t-keep[keep.length-1]>=minGap)keep.push(t);});rt=keep;}body+=axis(y,'Risk',0,totalMax,rt,t=>risk(t).toFixed(2));
  const r=figWrap5(spec,st,W,H,`<g data-sel="series:0">${body}</g>`,{x0,y0:padT,w:axW,h:H-padT});r.res={ptsPer,vars:vars.map((v,i)=>({name:v.name,pts:(ranges[i].max-ranges[i].min)*ptsPer})),intercept:d.intercept,riskRange:[risk(0),risk(totalMax)]};return r;}
// ゲノムトラック
function figRenderTracks(spec){const d=spec.data;const st=figStyle(spec);const {o,fs,txt,a,S}=st;const tracks=d.tracks;if(!tracks.length)return {svg:'',w:0,h:0};
  const all=tracks.flatMap(t=>t.items);const lo=Math.min(...all.map(it=>it.s)),hi=Math.max(...all.map(it=>it.e));const W0=(+o.wIn||5)*FIG_IN;const labW=Math.max(...tracks.map(t=>figTW(t.name,fs)))+fs*0.8;const th=(+o.trackH||0.35)*FIG_IN;const padT=fs*2.2;const x0=labW+fs*0.5;const xOf=v=>x0+(v-lo)/(hi-lo||1)*W0;
  let y=padT;let body='';tracks.forEach((t,ti)=>{const c=S(ti).color;let h=th;let rows=[];if(!t.signal){t.items.slice().sort((p,q)=>p.s-q.s).forEach(it=>{let k=rows.findIndex(r=>r<=it.s);if(k<0){k=rows.length;rows.push(0);}rows[k]=it.e+(hi-lo)*0.01;it.row=k;});h=Math.max(th,rows.length*fs*2.1+fs*0.3);}
    body+=txt(x0-fs*0.4,y+h/2+fs*0.35,t.name,'end')+`<line x1="${x0}" y1="${y+h}" x2="${x0+W0}" y2="${y+h}" stroke="#ccc" stroke-width="${FIG_PT*0.5}"/>`;
    if(t.signal){const vmax=Math.max(...t.items.map(it=>it.v))||1;let s='';t.items.forEach(it=>{const bh=Math.max(0,it.v)/vmax*(h-fs*0.2);s+=`<rect x="${xOf(it.s)}" y="${y+h-bh}" width="${Math.max(0.8,xOf(it.e)-xOf(it.s))}" height="${bh}" fill="${c}"/>`;});body+=`<g data-sel="series:${ti}">${s}</g>`+txt(x0+W0+fs*0.3,y+fs*0.6,figFmt(+vmax.toPrecision(2)),'start','',null,fs*0.7);}
    else{let s='';t.items.forEach(it=>{const ry=y+fs*0.3+it.row*fs*2.1,rh=fs*0.9;const x1=xOf(it.s),x2=xOf(it.e);s+=`<rect x="${x1}" y="${ry}" width="${Math.max(1.5,x2-x1)}" height="${rh}" fill="${c}" stroke="#333" stroke-width="${FIG_PT*0.3}"/>`;if(it.strand==='+'||it.strand==='-'){const dir=it.strand==='+'?1:-1;for(let x=x1+fs*0.6;x<x2-fs*0.3;x+=fs*1.2)s+=`<polyline points="${x-dir*fs*0.2},${ry+rh*0.2} ${x+dir*fs*0.2},${ry+rh/2} ${x-dir*fs*0.2},${ry+rh*0.8}" fill="none" stroke="#fff" stroke-width="${FIG_PT*0.6}"/>`;}if(it.label)s+=txt((x1+x2)/2,ry+rh+fs*0.8,it.label,'middle','',null,fs*0.7);});body+=`<g data-sel="series:${ti}">${s}</g>`;}
    y+=h+fs*0.5;});
  const ticks=figNiceTicks(lo,hi,6).ticks.filter(v=>v>=lo&&v<=hi);let axes=`<line x1="${x0}" y1="${y}" x2="${x0+W0}" y2="${y}" stroke="#000" stroke-width="${a}"/>`;ticks.forEach(v=>{axes+=`<line x1="${xOf(v)}" y1="${y}" x2="${xOf(v)}" y2="${y+fs*0.4}" stroke="#000" stroke-width="${a}"/>`+txt(xOf(v),y+fs*1.4,figBp(v),'middle','',null,fs*0.8);});const chr=all.find(it=>it.chr);axes+=txt(x0+W0/2,y+fs*2.6,o.xTitle||(chr?chr.chr+'（'+figBp(hi-lo)+'）':figBp(hi-lo)),'middle');
  const H=y+fs*3.2,W=x0+W0+fs*3;const r=figWrap5(spec,st,W,H,`<g data-sel="axes">${axes}</g>${body}`,{x0,y0:padT,w:W0,h:y-padT});r.res={tracks:tracks.map(t=>({name:t.name,n:t.items.length,signal:t.signal})),range:[lo,hi]};return r;}

/* ---------- 結果表 ---------- */
function figStatsP5(data,st){if(!data)return null;const r=st.res||{};const t=st.type;const esc=figEsc;const f3=v=>v==null||!isFinite(v)?'–':(+v).toFixed(3);
  if(data.kind==='sets')return `<div class="hint">要素 ${r.n}、集合 ${(r.sizes||[]).length}</div><table><tr><th>集合</th><th>n</th></tr>${(r.sizes||[]).map(s=>`<tr><td>${esc(s.name)}</td><td>${s.n}</td></tr>`).join('')}</table><table><tr><th>組み合わせ（上位）</th><th>n</th></tr>${(r.top||[]).map(c=>`<tr><td>${esc(c.sets)}</td><td>${c.n}</td></tr>`).join('')}</table>`;
  if(data.kind==='nomogram')return `<div class="hint">1 点 = 対数オッズ ${(1/(r.ptsPer||1)).toFixed(4)}、切片 ${f3(r.intercept)}、リスクの範囲 ${f3(r.riskRange&&r.riskRange[0])}–${f3(r.riskRange&&r.riskRange[1])}</div><table><tr><th>変数</th><th>最大点数</th></tr>${(r.vars||[]).map(v=>`<tr><td>${esc(v.name)}</td><td>${f3(v.pts)}</td></tr>`).join('')}</table><div class="hint">係数は対数オッズ（ロジスティック回帰）。点数は寄与の最大幅が ${st.opts.nomoPts||100} 点になるよう換算。</div>`;
  if(data.kind==='tracks')return `<table><tr><th>トラック</th><th>要素数</th><th>種類</th></tr>${(r.tracks||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.n}</td><td>${x.signal?'シグナル':'領域'}</td></tr>`).join('')}</table><div class="hint">範囲 ${figBp(r.range?r.range[0]:0)}–${figBp(r.range?r.range[1]:0)}</div>`;
  if(t==='density'||t==='ridgeline')return `<table><tr><th>群</th><th>n</th><th>帯域幅</th><th>${t==='density'?'最頻値':'中央値'}</th></tr>${(r.kde||[]).map(k=>`<tr><td>${esc(k.name)}</td><td>${k.n}</td><td>${f3(k.h)}</td><td>${f3(t==='density'?k.mode:k.median)}</td></tr>`).join('')}</table><div class="hint">ガウスカーネル、Silverman の帯域幅 × 設定の倍率。</div>`;
  if(t==='raincloud')return `<table><tr><th>群</th><th>n</th><th>Q1</th><th>中央値</th><th>Q3</th></tr>${(r.groups||[]).map(g=>`<tr><td>${esc(g.name)}</td><td>${g.n}</td><td>${f3(g.q1)}</td><td>${f3(g.median)}</td><td>${f3(g.q3)}</td></tr>`).join('')}</table>`;
  if(t==='radar')return `<div class="hint">軸の最大 ${figFmt(r.vmax)}。値は各セルの平均。</div>`;
  if(t==='dot-cat')return `<table><tr><th>カテゴリ</th>${(r.series||[]).map(s=>`<th>${esc(s)}</th>`).join('')}</tr>${(r.table||[]).map(row=>`<tr><td>${esc(row.cat)}</td>${row.vals.map(v=>`<td>${v==null?'–':figFmt(+v.toPrecision(4))}</td>`).join('')}</tr>`).join('')}</table>`;
  if(t==='xy-density')return `<div class="hint">n = ${r.n}、帯域幅 x ${f3(r.hx)} / y ${f3(r.hy)}（Scott）、等高線 ${r.levels} 本</div>`;
  if(t==='pr')return `<table><tr><th>マーカー</th><th>AP（平均精度）</th></tr>${(r.pr||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${f3(x.ap)}</td></tr>`).join('')}</table><div class="hint">破線＝陽性割合（${f3(r.pr&&r.pr[0]&&r.pr[0].prev)}）。</div>`;
  if(t==='calibration')return (r.cal||[]).map(c=>`<div class="hint"><b>${esc(c.name)}</b>: n = ${c.n}、Brier ${f3(c.brier)}${c.slope!=null?`、キャリブレーション slope ${f3(c.slope)}、intercept ${f3(c.icpt)}`:''}</div><table><tr><th>区間</th><th>予測の平均</th><th>観測割合</th><th>95% CI</th><th>n</th></tr>${c.bins.map((b,i)=>`<tr><td>${i+1}</td><td>${f3(b.pred)}</td><td>${f3(b.obs)}</td><td>${f3(b.lo)}–${f3(b.hi)}</td><td>${b.n}</td></tr>`).join('')}</table>`).join('')+'<div class="hint">区間は予測確率の分位、CI は Wilson。slope は logit(予測) に対するロジスティック回帰。</div>';
  if(t==='dca')return `<div class="hint">n = ${r.n}、陽性割合 ${f3(r.prev)}</div><table><tr><th>モデル</th><th>Net benefit 最大</th><th>そのしきい値</th></tr>${(r.dca||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${f3(x.nbMax)}</td><td>${f3(x.best)}</td></tr>`).join('')}</table>`;
  if(t==='cif')return `<table><tr><th>群</th><th>イベント</th><th>n</th><th>件数</th><th>最終の累積発生</th></tr>${(r.curves||[]).map(c=>`<tr><td>${esc(c.g)}</td><td>${c.cause}</td><td>${c.n}</td><td>${c.ev}</td><td>${f3(c.last)}</td></tr>`).join('')}</table><div class="hint">Aalen–Johansen 推定。Event は 0＝打ち切り、1＝対象、2 以上＝競合。Gray の検定は未実装。</div>`;
  if(t==='funnel')return `<div class="hint">研究 ${r.n}、固定効果の統合推定 ${f3(r.pooled)}${r.log?'（対数尺度で統合）':''}${r.egger?` ／ Egger の検定: 切片 ${f3(r.egger.icpt)}、P = ${r.egger.p<0.0001?'<0.0001':r.egger.p.toFixed(4)}`:''}</div>`;
  if(t==='hic')return `<div class="hint">${r.n} × ${r.m}、最大 ${figFmt(r.max)}${r.log?'、log10(1+値) で色付け':''}</div>`;
  if(t==='profile')return `<div class="hint">領域 ${r.rows}、ビン ${r.bins}、平均のピーク: ${esc(r.peak)}</div>`;
  if(t==='scatter3d')return `<div class="hint">n = ${r.n}、軸: ${(r.vars||[]).map(esc).join(' / ')}（正射影）</div>`;
  if(t==='gantt')return `<div class="hint">${r.n} 件、${figFmt(r.span&&r.span[0])}–${figFmt(r.span&&r.span[1])}</div>`+((r.groups||[]).length?`<table><tr><th>群</th><th>n</th></tr>${r.groups.map(g=>`<tr><td>${esc(g.name)}</td><td>${g.n}</td></tr>`).join('')}</table>`:'');
  if(t==='wordcloud')return `<div class="hint">${r.placed} / ${r.n} 語を配置</div><table><tr><th>語</th><th>重み</th></tr>${(r.top||[]).map(w=>`<tr><td>${esc(w.name)}</td><td>${figFmt(w.v)}</td></tr>`).join('')}</table>`;
  if(t==='circos')return `<div class="hint">リンク ${r.links}（染色体間 ${r.inter}）、染色体 ${r.chrs}。長さは GRCh38。</div>`;
  if(t==='cnv')return `<div class="hint">セグメント ${r.n}、増幅（log2 ≥ ${r.thr}）${r.gain}、欠失（≤ −${r.thr}）${r.loss}</div>`;
  if(t==='trajectory')return `<div class="hint">n = ${r.n}${r.lineages&&r.lineages.length?'、系統: '+r.lineages.map(esc).join(', '):''}、pseudotime ${figFmt(r.tRange[0])}–${figFmt(r.tRange[1])}</div>`;
  if(t==='lollipop')return `<table><tr><th>上位</th><th>値</th></tr>${(r.top||[]).map(x=>`<tr><td>${esc(x.label)}</td><td>${figFmt(x.v)}</td></tr>`).join('')}</table>`;
  return null;}

/* ---------- 見本（図の一覧用） ---------- */
function figSampleP5(kind,type){const R=figRng(5+type.length*31);const nrm=(m,s)=>m+s*R.n();const f1=v=>(+v).toFixed(1),f2=v=>(+v).toFixed(2);const J=(h,rows)=>[h.join('\t')].concat(rows.map(r=>r.join('\t'))).join('\n');const rep=(n,fn)=>Array.from({length:n},(_,i)=>fn(i));const sp=(data,extra)=>Object.assign({kind,type,data},extra||{});
  if(kind==='column'&&(type==='density'||type==='ridgeline'||type==='raincloud'))return sp(J(['Control','Low','High'],rep(type==='raincloud'?18:40,()=>[f1(nrm(10,1.6)),f1(nrm(12,2)),f1(nrm(15.5,2.4))])));
  if(kind==='grouped'&&type==='radar')return sp(J(['Domain','Before','After'],[['Physical',48,70],['Role',40,66],['Emotional',55,72],['Social',50,75],['Pain',45,68],['Fatigue',38,64]]));
  if(kind==='grouped'&&type==='dot-cat')return sp(J(['Country','2015','2025'],[['Japan',71,80],['Korea',63,77],['Taiwan',58,72],['Singapore',66,78],['Thailand',40,58],['Vietnam',32,51]]));
  if(kind==='xy'&&type==='xy-density')return sp(J(['LDH','CRP'],rep(160,()=>{const z=R.n();return [f1(220+70*z+nrm(0,40)),f2(Math.max(0.05,1.2+0.9*z+nrm(0,0.7)))];})));
  if(kind==='roc'&&(type==='pr'||type==='calibration'||type==='dca'))return sp(J(['Model A','Model B','Class'],rep(200,i=>{const pos=i<70;const a=Math.min(0.99,Math.max(0.01,nrm(pos?0.62:0.3,0.2))),b=Math.min(0.99,Math.max(0.01,nrm(pos?0.55:0.35,0.22)));return [f2(a),f2(b),pos?1:0];})));
  if(kind==='survival'&&type==='cif'){const rows=[];[['Control',10],['Drug',16]].forEach(([g,sc])=>rep(40,()=>{const t=-sc*Math.log(1-R.u()*0.98);const u=R.u();rows.push([f1(Math.min(t,36)),t>36||u<0.2?0:u<0.65?1:2,g]);}));return sp(J(['Time','Event','Group'],rows),{xtitle:'Months'});}
  if(kind==='forest'&&type==='funnel')return sp(J(['Study','OR','Lower','Upper'],rep(14,i=>{const se=0.12+R.u()*0.45;const e=Math.exp(Math.log(0.75)+nrm(0,se)+(se>0.4?-0.25:0));return ['S'+(i+1),f2(e),f2(e*Math.exp(-1.96*se)),f2(e*Math.exp(1.96*se))];})));
  if(kind==='heatmap'&&type==='hic'){const n=24;return sp(J(['bin',...rep(n,i=>(i*0.5).toFixed(1)+'Mb')],rep(n,i=>[(i*0.5).toFixed(1)+'Mb',...rep(n,j=>Math.round(400*Math.exp(-Math.abs(i-j)/3)+(Math.floor(i/8)===Math.floor(j/8)?60:0)+R.u()*20))])));}
  if(kind==='heatmap'&&type==='profile'){const bins=rep(31,i=>i===0?'-3kb':i===15?'TSS':i===30?'+3kb':'b'+i);return sp(J(['region',...bins],rep(40,i=>['r'+(i+1),...rep(31,j=>f2(Math.max(0,(3-i*0.06)*Math.exp(-(((j-15)/4)**2))+nrm(0.2,0.12))))])));}
  if(kind==='multi'&&type==='scatter3d')return sp(J(['Id','x','y','z','Group'],rep(36,i=>{const g=i%3;return ['s'+i,f2(nrm(g*2,0.8)),f2(nrm(g===1?3:1,0.8)),f2(nrm(g*1.5,0.7)),'G'+(g+1)];})));
  if(kind==='swimmer'&&type==='gantt')return sp(J(['Task','Start','End','Group'],[['Protocol',0,3,'Planning'],['IRB approval',2,5,'Planning'],['Enrollment',5,17,'Conduct'],['Follow-up',8,24,'Conduct'],['Data cleaning',22,26,'Analysis'],['Analysis',25,29,'Analysis'],['Manuscript',28,34,'Analysis']]),{xtitle:'Month',style:{ganttNow:'12'}});
  if(kind==='importance'&&type==='wordcloud')return sp(J(['Word','Weight'],[['lymphoma',42],['CD20',38],['rituximab',30],['relapse',26],['B cell',24],['survival',22],['immunotherapy',18],['CAR-T',17],['mutation',15],['SPIB',14],['transcription',12],['resistance',12],['antibody',11],['remission',10],['biopsy',8],['PET',8],['cohort',7],['dose',6],['toxicity',6],['phase 2',5]]));
  if(kind==='omics'&&type==='circos'){const chrs=['1','3','7','8','11','14','17','18','22','X'];return sp(J(['From','FromPos','To','ToPos','Value'],rep(24,()=>{const a=chrs[Math.floor(R.u()*chrs.length)],b=chrs[Math.floor(R.u()*chrs.length)];return ['chr'+a,Math.round(R.u()*FIG_CHR_LEN[a]),'chr'+b,Math.round(R.u()*FIG_CHR_LEN[b]),Math.round(1+R.u()*9)];})));}
  if(kind==='omics'&&type==='cnv'){const rows=[];[1,2,3,5,7,8,9,11,13,17,'X'].forEach(c=>{const L=FIG_CHR_LEN[c];let p=0;while(p<L){const len=Math.min(L-p,Math.round(L*(0.08+R.u()*0.3)));const v=R.u()<0.25?nrm(0.6,0.2):R.u()<0.3?nrm(-0.7,0.2):nrm(0,0.06);rows.push(['chr'+c,p,p+len,f2(v)]);p+=len;}});return sp(J(['Chr','Start','End','log2'],rows));}
  if(kind==='omics'&&type==='trajectory')return sp(J(['UMAP_1','UMAP_2','pseudotime','lineage'],rep(240,i=>{const t=R.u();const ln=i%2?'A':'B';const x=t*8+nrm(0,0.5),y=ln==='A'?Math.sin(t*2.5)*2+t*2+nrm(0,0.4):-t*3+nrm(0,0.4);return [f2(x),f2(y),f2(t*20),ln];})));
  if(kind==='omics'&&type==='lollipop')return sp(J(['Position','Value','Label','Type'],[[27,3,'G12','Missense'],[52,14,'G12C','Missense'],[61,6,'Q61','Missense'],[117,2,'K117','Missense'],[146,4,'A146','Missense'],[175,1,'R175','Nonsense'],[213,3,'R213','Nonsense'],[248,8,'R248','Missense'],[273,9,'R273','Missense'],[306,2,'R306','Nonsense']]),{xtitle:'Amino acid position'});
  if(kind==='sets')return sp(J(['Item','RNA-seq','Proteome','Phospho','ChIP'],rep(80,i=>['g'+i,...[0.6,0.45,0.35,0.3].map((p,k)=>R.u()<p+(i%5===0?0.3:0)?1:0)])));
  if(kind==='nomogram')return sp(J(['Variable','Level','Coef','Min','Max'],[['Intercept','',-4.2,'',''],['Age','',0.045,30,90],['LDH ratio','',0.9,0.5,4],['Stage','I–II',0,'',''],['Stage','III–IV',0.8,'',''],['ECOG PS','0–1',0,'',''],['ECOG PS','≥2',1.1,'','']]));
  if(kind==='tracks')return sp(J(['Track','Start','End','Value','Name','Strand'],[...rep(60,i=>['H3K27ac',i*500,i*500+500,f1(Math.max(0,20*Math.exp(-(((i-22)/5)**2))+10*Math.exp(-(((i-45)/4)**2))+R.u()*2)),'','']),...rep(60,i=>['ATAC',i*500,i*500+500,f1(Math.max(0,15*Math.exp(-(((i-22)/3)**2))+R.u()*1.5)),'','']),['Genes',3000,14000,'','GENE1','+'],['Genes',16000,27000,'','GENE2','-'],['Genes',20000,29500,'','GENE3','+'],['Peaks',9500,12500,'','peak1',''],['Peaks',21000,23500,'','peak2','']]));
  return null;}

// omics の自動判定に P5 の型（cnv / circos / trajectory）を足す（元の figOmicsType を包む）
const figOmicsTypeP4=figOmicsType;
figOmicsType=function(parsed){const cols=parsed.cols;const has=re=>cols.some(c=>re.test(figLC5(c)));
  if(has(/^(chr|chrom|chromosome)$/)&&has(/^(start|loc\.start)$/)&&has(/log2|seg\.?mean|segment_mean|ratio/))return 'cnv';
  if(has(/^(from_?pos|pos1|frompos|bp1)$/)&&has(/^(to_?pos|pos2|topos|bp2)$/))return 'circos';
  if(has(/pseudotime|擬似時間/))return 'trajectory';
  return figOmicsTypeP4(parsed);};
