// BranCHAT Figure 拡張（P4: オミクス・ゲノム解析の図、要件書 F3）
// kind "omics"。type: manhattan（CHR, BP, P）、embedding（UMAP/t-SNE: x, y, cluster または連続値）、gsea（Rank, Metric, Hit）、
// enrich-bar / enrich-dot（Term, Count, P/q, GeneRatio）、dotplot（Seurat 型: Gene, Cluster, Pct, Avg）、sbs96（Type, Count）、
// oncoprint（遺伝子 × 検体の変異種類）、logo（配列 or PFM）、sankey（From, To, Value）、rank（Gene, Score）、network（From, To）、tree（Newick）。
// figure-more2.js の P4 フック（figAutoKindP4 / figBuildDataP4 / figRenderP4 / figStatsP4）から呼ばれる。
'use strict';

Object.assign(FIG_TYPES,{omics:[['auto','自動（列の見出しから判定）'],['manhattan','マンハッタン（CHR, BP, P）'],['embedding','UMAP / t-SNE（x, y, cluster）'],['gsea','GSEA エンリッチメント（Rank, Metric, Hit）'],['enrich-bar','エンリッチメント 横棒（Term, Count, q）'],['enrich-dot','エンリッチメント ドット（Term, GeneRatio, Count, q）'],['dotplot','ドットプロット Seurat 型（Gene, Cluster, Pct, Avg）'],['sbs96','変異シグネチャー SBS96（Type, Count）'],['oncoprint','オンコプリント（遺伝子 × 検体）'],['logo','配列ロゴ（配列 or PFM）'],['sankey','サンキー（From, To, Value）'],['rank','ランクプロット（Gene, Score）'],['network','ネットワーク（From, To）'],['tree','系統樹（Newick）']]});
const FIG_KINDS_P4=[['omics','オミクス（マンハッタン・UMAP・GSEA・…）']];
const FIG_DEF_P4={mhLines:true,mhLabels:5,mhY:'auto',embLabels:true,embSize:2.2,embScale:'',gseaText:true,enN:15,enSort:'q',enColor:'q',dpScale:true,sbsPct:false,opSort:true,opPct:true,logoBits:true,skVals:true,rankN:10,rankHi:'',netLabels:true,treeLen:true};
Object.assign(FIG_DEF,FIG_DEF_P4);FIG_STYLE_KEYS.push(...Object.keys(FIG_DEF_P4));
Object.assign(FIG_TOOLS_MORE,{
  manhattan:[{k:'mhLines',t:'check',l:'有意線（5×10⁻⁸・1×10⁻⁵）'},{k:'mhLabels',t:'select',l:'名前を書く上位 n',o:[['0','なし'],['3','3'],['5','5'],['10','10']]}],
  embedding:[{k:'embLabels',t:'check',l:'クラスタ名を図中に'},{k:'embSize',t:'select',l:'点の大きさ',o:[['1.5','小'],['2.2','中'],['3.5','大']]}],
  gsea:[{k:'gseaText',t:'check',l:'NES・P・FDR を書く'}],
  'enrich-bar':[{k:'enN',t:'select',l:'上位 n 件',o:[['10','10'],['15','15'],['20','20'],['30','30']]},{k:'enSort',t:'select',l:'並べ方',o:[['q','q の小さい順'],['count','遺伝子数の多い順'],['input','入力順']]}],
  'enrich-dot':[{k:'enN',t:'select',l:'上位 n 件',o:[['10','10'],['15','15'],['20','20'],['30','30']]},{k:'enSort',t:'select',l:'並べ方',o:[['q','q の小さい順'],['count','遺伝子数の多い順'],['ratio','GeneRatio の大きい順'],['input','入力順']]}],
  dotplot:[{k:'dpScale',t:'check',l:'発現を遺伝子ごとに z スコア化'}],
  sbs96:[{k:'sbsPct',t:'check',l:'縦軸を割合（%）に'}],
  oncoprint:[{k:'opSort',t:'check',l:'検体を変異の有無で並べ替え（memo sort）'},{k:'opPct',t:'check',l:'遺伝子ごとの変異率を書く'}],
  logo:[{k:'logoBits',t:'select',l:'縦軸',o:[['true','情報量（bits）'],['false','頻度']]}],
  sankey:[{k:'skVals',t:'check',l:'ノードに値を書く'}],
  rank:[{k:'rankN',t:'select',l:'名前を書く上位 n',o:[['5','5'],['10','10'],['20','20']]},{k:'rankHi',t:'text',l:'強調する遺伝子（カンマ区切り）'}],
  network:[{k:'netLabels',t:'check',l:'ノード名を書く'}],
  tree:[{k:'treeLen',t:'check',l:'枝の長さを使う'}]});
const FIG_PAL20=['#1F77B4','#FF7F0E','#2CA02C','#D62728','#9467BD','#8C564B','#E377C2','#7F7F7F','#BCBD22','#17BECF','#AEC7E8','#FFBB78','#98DF8A','#FF9896','#C5B0D5','#C49C94','#F7B6D2','#C7C7C7','#DBDB8D','#9EDAE5'];
const FIG_SBS_COLORS={'C>A':'#03BCEE','C>G':'#010101','C>T':'#E32926','T>A':'#CAC9C9','T>C':'#A1CE63','T>G':'#EBC6C4'};
const FIG_ONCO_COLORS={missense:'#2CA02C',nonsense:'#000000',frameshift:'#9467BD',splice:'#FF7F0E',inframe:'#8C564B',amp:'#D62728',del:'#1F77B4',fusion:'#E377C2',multi:'#555555',other:'#7F7F7F'};
const FIG_BASE_COLORS={A:'#109648',C:'#255C99',G:'#F7B32B',T:'#D62839',U:'#D62839'};

FIG_PROMPT+=`
kind "omics"（オミクス）の type と data の列:
manhattan: CHR, BP, P（SNP 任意）／ embedding: UMAP_1, UMAP_2（または x, y）, cluster（文字）または連続値の列（発現量）／ gsea: Rank, Metric（順位付けの指標）, Hit（1=遺伝子セットの遺伝子）。NES・P・FDR は JSON の "nes","pval","fdr" に／
enrich-bar / enrich-dot: Term, Count, P または q（padj）, GeneRatio（任意, 例 0.12 や 12/100）／ dotplot: Gene, Cluster, Pct（発現細胞 %）, Avg（平均発現）の長い形式／ sbs96: Type（例 A[C>A]G）, Count／
oncoprint: 1 列目＝遺伝子、見出し＝検体名、セルは Missense/Nonsense/Frameshift/Splice/Amp/Del/Fusion か空／ logo: 1 列の配列（同じ長さ）または pos, A, C, G, T の PFM／ sankey: From, To, Value／ rank: Gene, Score／ network: From, To（Weight 任意）／ tree: 見出し tree、2 行目に Newick 文字列。`;

/* ---------- 判定と組み立て ---------- */
function figAutoKindP4(parsed){const cols=parsed.cols;const lc=figLC;const has=re=>cols.some(c=>re.test(lc(c)));
  if(has(/^(chr|chrom|chromosome|染色体)$/)&&has(/^(bp|pos|position|base_pair|位置)$/)&&has(/^(p|pval|p_value|pvalue|p\.value)$/))return 'omics';
  if(has(/umap|tsne|t-sne|pc_?1$/))return 'omics';
  if(has(/^(term|pathway|go|description|経路|用語)$/)&&has(/count|size|遺伝子数|gene/)&&has(/^(p|q|padj|fdr|p\.adjust|pvalue|adj)/))return 'omics';
  if(cols[0]&&cols[0].raw.some(v=>/^[ACGT]\[[ACGT]>[ACGT]\][ACGT]$/i.test(v)))return 'omics';
  if(has(/^(from|source|出発)$/)&&has(/^(to|target|到着)$/))return 'omics';
  if(has(/^(rank|順位)$/)&&has(/^(hit|in_?set|member)$/))return 'omics';
  if(/^tree$|newick/.test(lc(cols[0]||{}))&&cols[0].raw.some(v=>/^\(.*\);?$/.test(v)))return 'omics';
  return null;}
function figOmicsType(parsed){const cols=parsed.cols;const lc=figLC;const has=re=>cols.some(c=>re.test(lc(c)));
  if(has(/^(chr|chrom|chromosome|染色体)$/)&&has(/^(bp|pos|position|位置)$/))return 'manhattan';if(has(/umap|tsne|t-sne|pc_?1$/))return 'embedding';if(has(/^(rank|順位)$/)&&has(/^(hit|in_?set|member)$/))return 'gsea';
  if(has(/^(term|pathway|go|description|経路|用語)$/))return has(/ratio|generatio/)?'enrich-dot':'enrich-bar';if(has(/^(cluster|群)$/)&&has(/pct|percent|%/))return 'dotplot';if(cols[0]&&cols[0].raw.some(v=>/^[ACGT]\[[ACGT]>[ACGT]\][ACGT]$/i.test(v)))return 'sbs96';
  if(has(/^(from|source)$/)&&has(/^(to|target)$/))return has(/^(value|flow|count|n|値)$/)?'sankey':'network';if(/^tree$|newick/.test(lc(cols[0]||{})))return 'tree';if(has(/^(score|stat|statistic|logfc|log2fc)$/)&&parsed.firstColText)return 'rank';
  if(cols.length===1&&cols[0].raw.every(v=>/^[ACGTUN-]+$/i.test(v)))return 'logo';if(has(/^a$/)&&has(/^c$/)&&has(/^g$/)&&has(/^t$/))return 'logo';if(parsed.firstColText&&cols.slice(1).some(c=>c.raw.some(v=>/missense|nonsense|frameshift|splice|amp|del|fusion|変異/i.test(v))))return 'oncoprint';return null;}
function figBuildDataP4(parsed,kind){if(kind!=='omics')return undefined;const cols=parsed.cols;const lc=figLC;const find=(re,ex)=>cols.find(c=>re.test(lc(c))&&!(ex||[]).includes(c))||null;const numc=c=>c&&c.vals.some(v=>v!==null);
  return {kind:'omics',parsed,groups:[],
    chr:find(/^(chr|chrom|chromosome|染色体)$/),bp:find(/^(bp|pos|position|base_pair|位置)$/),p:find(/^(p|pval|p_value|pvalue|p\.value|p値)$/),snp:find(/^(snp|rsid|id|marker|name)$/),
    x:find(/umap_?1|tsne_?1|t-sne_?1|^x$|_1$|pc_?1$/),y:find(/umap_?2|tsne_?2|t-sne_?2|^y$|_2$|pc_?2$/),cluster:find(/^(cluster|celltype|cell_type|group|群|type|label)$/),
    rank:find(/^(rank|順位)$/),metric:find(/^(metric|stat|score|statistic|指標)$/),hit:find(/^(hit|in_?set|member)$/),
    term:find(/^(term|pathway|go|description|経路|用語|name)$/),count:find(/^(count|size|gene_?count|genes|遺伝子数|n|intersection|overlap)$/),q:find(/^(q|padj|fdr|p\.adjust|adj|qvalue|q_value|p\.adj)/),pv:find(/^(p|pval|pvalue|p_value|p\.value)$/),ratio:find(/ratio|generatio|fold/),
    gene:find(/^(gene|feature|遺伝子|marker|features?)$/),pct:find(/pct|percent|%/),avg:find(/avg|mean|average|expr|平均/),
    from:find(/^(from|source|出発)$/),to:find(/^(to|target|到着)$/),value:find(/^(value|weight|count|n|flow|値)$/),score:find(/^(score|stat|statistic|logfc|log2fc|値)$/),
    first:cols[0],firstColText:parsed.firstColText,rowLabels:parsed.rowLabels,type:figOmicsType(parsed)};}

/* ---------- 描画 ---------- */
function figRenderP4(spec){const d=spec.data;if(!d||d.kind!=='omics')return null;const t=spec.type&&spec.type!=='auto'&&FIG_TYPES.omics.some(x=>x[0]===spec.type)?spec.type:(d.type||'manhattan');
  const map={manhattan:figRenderManhattan,embedding:figRenderEmbedding,gsea:figRenderGSEA,'enrich-bar':figRenderEnrich,'enrich-dot':figRenderEnrich,dotplot:figRenderDotplot,sbs96:figRenderSBS96,oncoprint:figRenderOncoprint,logo:figRenderLogo,sankey:figRenderSankey,rank:figRenderRank,network:figRenderNetwork,tree:figRenderTree};
  const r=map[t]?map[t](spec,t):null;return r||{svg:'',w:0,h:0};}
const figOmTxt=(x,y,s,o)=>figSchText(x,y,s,o);
function figOmEmpty(msg){return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="60" viewBox="0 0 300 60"><rect width="100%" height="100%" fill="#fff"/><text x="150" y="36" font-family="${FIG_DEF.font}" font-size="12" text-anchor="middle" fill="#888">${figEsc(msg)}</text></svg>`,w:300,h:60,res:{error:msg}};}

// マンハッタン
function figRenderManhattan(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});if(!d.chr||!d.bp||!d.p)return figOmEmpty('CHR, BP, P の列が必要です');
  const chrKey=v=>{const s=String(v).replace(/^chr/i,'').toUpperCase();return s==='X'?23:s==='Y'?24:s==='MT'||s==='M'?25:+s||99;};const chrLab=v=>{const s=String(v).replace(/^chr/i,'').toUpperCase();return s;};
  const pts=[];d.chr.raw.forEach((c,i)=>{const bp=d.bp.vals[i],p=d.p.vals[i];if(c===''||bp===null||!(p>0))return;pts.push({c:chrKey(c),cl:chrLab(c),bp,y:-Math.log10(p),p,id:d.snp?d.snp.raw[i]:''});});if(!pts.length)return figOmEmpty('点がありません');
  const chrs=[...new Set(pts.map(p=>p.c))].sort((a,b)=>a-b);const off={},len={};let acc=0;chrs.forEach(c=>{const m=Math.max(...pts.filter(p=>p.c===c).map(p=>p.bp));len[c]=m;off[c]=acc;acc+=m*1.02;});const total=acc;
  const ymax=Math.max(...pts.map(p=>p.y),o.mhLines?8:0)*1.08;const [ylo,yhi]=figYRange(o,0,ymax);const ys=figAxisLin(ylo,yhi,5);const xs={lo:0,hi:total,cat:true,ticks:chrs.map(c=>({v:off[c]+len[c]/2,l:chrs.length>12&&(c%2===0)&&c>9?'':pts.find(p=>p.c===c).cl}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Chromosome',yTitle:o.yTitle||'−log10(P)',wIn:(spec.opts||{}).wIn==null?5:0});const {xOf,yOf,a,fs,txt,dash,x0,plotW}=F;const r=Math.max(1,Math.min(2.5,FIG_PT*2.2*Math.sqrt(2000/Math.max(pts.length,200))));
  let body='';chrs.forEach((c,k)=>{const col=k%2?'#9ECAE1':'#1F77B4';let s='';pts.filter(p=>p.c===c).forEach(p=>{s+=`<circle cx="${xOf(off[c]+p.bp)}" cy="${yOf(Math.min(p.y,ys.hi))}" r="${r}" fill="${col}"/>`;});body+=`<g data-sel="series:${k}">${s}</g>`;});
  let lines='';if(o.mhLines){for(const [pv,col,ds] of [[5e-8,'#D62728',''],[1e-5,'#1F77B4',dash]]){const y=-Math.log10(pv);if(y<ys.hi)lines+=`<line x1="${x0}" y1="${yOf(y)}" x2="${x0+plotW}" y2="${yOf(y)}" stroke="${col}" stroke-width="${a*0.6}"${ds?` stroke-dasharray="${ds}"`:''}/>`;}}
  let labels='';const nl=+o.mhLabels||0;if(nl>0){const top=pts.filter(p=>p.id).sort((p,q)=>q.y-p.y).slice(0,nl);const placed=[];top.forEach(p=>{let x=xOf(off[p.c]+p.bp)+fs*0.4,y=yOf(Math.min(p.y,ys.hi))-fs*0.3;for(let k=0;k<10&&placed.some(q=>Math.abs(q.y-y)<fs*0.9&&Math.abs(q.x-x)<fs*4);k++)y-=fs*0.9;placed.push({x,y});labels+=txt(x,y,p.id,'start',null,null,fs*0.7);});}
  const R=F.wrap(lines+body+(labels?`<g data-sel="text">${labels}</g>`:''));R.res={n:pts.length,chrs:chrs.length,gw:pts.filter(p=>p.p<5e-8).length,sug:pts.filter(p=>p.p<1e-5).length,top:pts.slice().sort((p,q)=>q.y-p.y).slice(0,10)};return R;}

// UMAP / t-SNE
function figRenderEmbedding(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const X=d.x||cols.find(c=>c.vals.some(v=>v!==null)),Y=d.y||cols.find(c=>c!==X&&c.vals.some(v=>v!==null));if(!X||!Y)return figOmEmpty('x, y の列が必要です');
  const cl=d.cluster||cols.find(c=>c!==X&&c!==Y&&c.raw.some(v=>v!==''&&isNaN(+v)))||null;const cont=!cl?cols.find(c=>c!==X&&c!==Y&&c.vals.some(v=>v!==null)):null;
  const pts=[];X.vals.forEach((x,i)=>{const y=Y.vals[i];if(x===null||y===null)return;pts.push({x,y,g:cl?cl.raw[i]:'',v:cont?cont.vals[i]:null});});if(!pts.length)return figOmEmpty('点がありません');
  const gs=cl?[...new Set(pts.map(p=>p.g))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})):[];const vmin=cont?Math.min(...pts.map(p=>p.v).filter(v=>v!==null)):0,vmax=cont?Math.max(...pts.map(p=>p.v).filter(v=>v!==null)):1;
  const xr=[Math.min(...pts.map(p=>p.x)),Math.max(...pts.map(p=>p.x))],yr=[Math.min(...pts.map(p=>p.y)),Math.max(...pts.map(p=>p.y))];const px=(xr[1]-xr[0])*0.05||1,py=(yr[1]-yr[0])*0.05||1;const xs=figAxisLin(xr[0]-px,xr[1]+px,4),ys=figAxisLin(yr[0]-py,yr[1]+py,4);
  const nm=/tsne|t-sne/i.test(X.name)?'t-SNE':/pc/i.test(X.name)?'PC':'UMAP';const legend=cl&&!o.embLabels?gs.map((g,i)=>({name:String(g),kind:'sym',i,color:FIG_PAL20[i%20],fill:'solid',shape:'circle'})):[];
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||X.name||nm+' 1',yTitle:o.yTitle||Y.name||nm+' 2',legend,legendW:7,padR:cont?F0(o)*5:0,wIn:(spec.opts||{}).wIn==null?3:0,hIn:(spec.opts||{}).hIn==null?3:0});const {xOf,yOf,fs,a,txt,x0,plotW,padT,plotH}=F;
  const r=(+o.embSize||2.2)*FIG_PT*0.5*Math.max(0.5,Math.min(1.4,Math.sqrt(1500/Math.max(pts.length,300))));const grad=['#D9D9D9','#FCAE91','#DE2D26','#67000D'];
  let body='';if(cl){gs.forEach((g,i)=>{let s='';pts.forEach(p=>{if(p.g===g)s+=`<circle cx="${xOf(p.x)}" cy="${yOf(p.y)}" r="${r}" fill="${FIG_PAL20[i%20]}"/>`;});body+=`<g data-sel="series:${i}">${s}</g>`;});}
  else{const ord=pts.slice().sort((p,q)=>(p.v||0)-(q.v||0));let s='';ord.forEach(p=>{s+=`<circle cx="${xOf(p.x)}" cy="${yOf(p.y)}" r="${r}" fill="${p.v===null?'#ddd':figGrad(grad,(p.v-vmin)/((vmax-vmin)||1))}"/>`;});body+=`<g data-sel="series:0">${s}</g>`;}
  let labels='';if(cl&&o.embLabels)gs.forEach((g,i)=>{const ps=pts.filter(p=>p.g===g);const mx=median(ps.map(p=>p.x)),my=median(ps.map(p=>p.y));labels+=`<text x="${xOf(mx)}" y="${yOf(my)+fs*0.35}" font-family="${FIG_DEF.font}" font-size="${fs*0.95}" font-weight="bold" text-anchor="middle" fill="#000" stroke="#fff" stroke-width="${fs*0.2}" paint-order="stroke">${figEsc(g)}</text>`;});
  let bar='';if(cont){const gid='embg'+Math.random().toString(36).slice(2,6);const bx=x0+plotW+fs*1.2,bh=plotH*0.5;bar=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${grad.map((c,k)=>`<stop offset="${k/(grad.length-1)*100}%" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${bx}" y="${padT}" width="${fs*0.8}" height="${bh}" fill="url(#${gid})" stroke="#000" stroke-width="${a*0.5}"/>`+txt(bx+fs*1.1,padT+fs*0.7,figFmt(+vmax.toPrecision(3)),'start',null,null,fs*0.8)+txt(bx+fs*1.1,padT+bh,figFmt(+vmin.toPrecision(3)),'start',null,null,fs*0.8)+txt(bx,padT-fs*0.4,cont.name,'start',null,null,fs*0.8);}
  const R=F.wrap(body+labels+bar);R.res={n:pts.length,clusters:gs.map(g=>({name:g,n:pts.filter(p=>p.g===g).length})),cont:cont?cont.name:null};return R;}

// GSEA（ランニング ES、ヒット位置、ランク指標の 3 段）
function figRenderGSEA(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const H=d.hit||cols.find(c=>figIsBin(c));const M=d.metric||cols.find(c=>c!==H&&c!==d.rank&&c.vals.some(v=>v!==null));if(!H||!M)return figOmEmpty('Metric と Hit の列が必要です');
  const rows=M.vals.map((m,i)=>({m,h:/^(1|yes|true|y)$/i.test(H.raw[i]),r:d.rank?d.rank.vals[i]:i+1})).filter(x=>x.m!==null).sort((a,b)=>(a.r!=null&&b.r!=null)?a.r-b.r:b.m-a.m);const N=rows.length;if(N<3)return figOmEmpty('行が足りません');
  const nh=rows.filter(x=>x.h).length;if(!nh)return figOmEmpty('Hit=1 の行がありません');const sumHit=rows.filter(x=>x.h).reduce((s,x)=>s+Math.abs(x.m),0)||1;let es=0,esMax=0,esMin=0,iMax=0,iMin=0;const run=[];rows.forEach((x,i)=>{es+=x.h?Math.abs(x.m)/sumHit:-1/(N-nh);run.push(es);if(es>esMax){esMax=es;iMax=i;}if(es<esMin){esMin=es;iMin=i;}});const ES=Math.abs(esMax)>=Math.abs(esMin)?esMax:esMin,iES=Math.abs(esMax)>=Math.abs(esMin)?iMax:iMin;
  const st=figStyle(spec);const {fs,a,ac,txt,dash}=st;const W0=((spec.opts||{}).wIn==null?3.6:+o.wIn)*FIG_IN;const h1=fs*9,h2=fs*2,h3=fs*4;const padL=fs*4,padT=fs*(spec.title?2.4:1),padB=fs*3;const W=padL+W0+fs*1.5,Hh=padT+h1+h2+h3+padB;const X=i=>padL+i/(N-1)*W0;
  const elo=Math.min(esMin,0)-0.05,ehi=Math.max(esMax,0)+0.05;const yE=v=>padT+(ehi-v)/(ehi-elo)*h1;const col=spec.opts&&spec.opts.series&&spec.opts.series[0]&&spec.opts.series[0].color||'#2CA02C';
  let s=`<path d="${run.map((v,i)=>(i?'L':'M')+X(i)+','+yE(v)).join('')}" fill="none" stroke="${col}" stroke-width="${FIG_PT*1.5}"/><line x1="${padL}" y1="${yE(0)}" x2="${padL+W0}" y2="${yE(0)}" stroke="#888" stroke-width="${a*0.5}" stroke-dasharray="${dash}"/><line x1="${X(iES)}" y1="${yE(ES)}" x2="${X(iES)}" y2="${yE(0)}" stroke="#D62728" stroke-width="${a*0.6}" stroke-dasharray="${dash}"/>`;
  s+=`<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${padT+h1}" stroke="${ac}" stroke-width="${a}"/>`;figNiceTicks(elo,ehi,4).ticks.forEach(v=>{s+=`<line x1="${padL}" y1="${yE(v)}" x2="${padL-fs*0.4}" y2="${yE(v)}" stroke="${ac}" stroke-width="${a}"/>`+txt(padL-fs*0.6,yE(v)+fs*0.33,figFmt(v),'end',null,null,fs*0.85);});s+=txt(padL-fs*2.6,padT+h1/2,'Enrichment score','middle',`transform="rotate(-90 ${padL-fs*2.6} ${padT+h1/2})"`,null,fs*0.9);
  const y2=padT+h1+fs*0.3;rows.forEach((x,i)=>{if(x.h)s+=`<line x1="${X(i)}" y1="${y2}" x2="${X(i)}" y2="${y2+h2-fs*0.6}" stroke="#000" stroke-width="${Math.max(0.6,W0/N*0.8)}"/>`;});
  const y3=padT+h1+h2;const mmax=Math.max(...rows.map(x=>Math.abs(x.m)))||1;const y0m=y3+h3/2;const step=Math.max(1,Math.floor(N/400));let bars='';for(let i=0;i<N;i+=step){const v=rows[i].m;bars+=`<rect x="${X(i)}" y="${v>=0?y0m-v/mmax*h3/2:y0m}" width="${Math.max(0.5,W0/N*step)}" height="${Math.abs(v)/mmax*h3/2}" fill="${v>=0?'#D62728':'#1F77B4'}"/>`;}s+=bars+`<line x1="${padL}" y1="${y0m}" x2="${padL+W0}" y2="${y0m}" stroke="#888" stroke-width="${a*0.5}"/>`;
  s+=`<line x1="${padL}" y1="${y3+h3}" x2="${padL+W0}" y2="${y3+h3}" stroke="${ac}" stroke-width="${a}"/>`;figNiceTicks(0,N,5).ticks.forEach(v=>{if(v>N)return;s+=`<line x1="${X(Math.max(0,v-1))}" y1="${y3+h3}" x2="${X(Math.max(0,v-1))}" y2="${y3+h3+fs*0.4}" stroke="${ac}" stroke-width="${a}"/>`+txt(X(Math.max(0,v-1)),y3+h3+fs*1.4,figFmt(v),'middle',null,null,fs*0.85);});s+=txt(padL+W0/2,y3+h3+fs*2.6,'Rank in ordered gene list','middle',null,null,fs*0.9);s+=txt(padL-fs*2.6,y0m,'Ranked metric','middle',`transform="rotate(-90 ${padL-fs*2.6} ${y0m})"`,null,fs*0.85);
  if(o.gseaText){const ex=[`ES = ${ES.toFixed(3)}`];const xx=Object.assign({},spec.x||{},(spec.opts&&spec.opts.x)||{});if(xx.nes!=null)ex.push(`NES = ${(+xx.nes).toFixed(2)}`);if(xx.pval!=null)ex.push(`P = ${figSci(+xx.pval)}`);if(xx.fdr!=null)ex.push(`FDR q = ${figSci(+xx.fdr)}`);ex.push(`n = ${nh} / ${N}`);const tx=ES>=0?padL+W0-fs*0.3:padL+fs*0.4;ex.forEach((e,k)=>{s+=txt(tx,padT+fs*(k+1)*1.1+(ES>=0?0:h1*0.45),e,ES>=0?'end':'start',null,null,fs*0.85);});}
  const title=spec.title?txt(padL+W0/2,padT-fs*0.9,spec.title,'middle','','title'):'';
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${Hh}" viewBox="0 0 ${W} ${Hh}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="axes"></g>${s}${title}</svg>`,w:W,h:Hh,plot:{x0:padL,y0:padT,w:W0,h:h1+h2+h3},res:{es:ES,atRank:iES+1,n:N,hits:nh,leadingEdge:rows.slice(0,iES+1).filter(x=>x.h).length}};}

// エンリッチメント（横棒 / ドット）
function figRenderEnrich(spec,type){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const T=d.term||d.first;if(!T)return figOmEmpty('Term の列が必要です');const Q=d.q||d.pv;const C=d.count;const Rr=d.ratio;
  const parseRatio=v=>{const s=String(v||'').trim();const m=/^(\d+)\s*\/\s*(\d+)$/.exec(s);if(m)return +m[1]/+m[2];const n=+s;return isFinite(n)?n:null;};
  let items=T.raw.map((t,i)=>t===''?null:({term:t,q:Q?Q.vals[i]:null,n:C?C.vals[i]:null,ratio:Rr?parseRatio(Rr.raw[i]):null})).filter(Boolean);if(!items.length)return figOmEmpty('行がありません');
  const srt=o.enSort;if(srt==='q'&&Q)items.sort((a,b)=>(a.q==null?1:a.q)-(b.q==null?1:b.q));else if(srt==='count'&&C)items.sort((a,b)=>(b.n||0)-(a.n||0));else if(srt==='ratio'&&Rr)items.sort((a,b)=>(b.ratio||0)-(a.ratio||0));items=items.slice(0,+o.enN||15);const n=items.length;
  const fs0=F0(o);const labW=Math.max(...items.map(it=>figSchTW(it.term,fs0)))+fs0*0.5;const ys={lo:0,hi:n,cat:true,ticks:items.map((it,i)=>({v:n-i-0.5,l:it.term}))};const dot=type==='enrich-dot';
  const xv=dot?items.map(it=>it.ratio||0):items.map(it=>it.q>0?-Math.log10(it.q):0);const xs=dot?figAxisLin(0,Math.max(...xv)*1.15||1,4):figAxisLin(0,Math.max(...xv)*1.08||1,5);if(dot)xs.lo=Math.max(0,Math.min(...xv)-(Math.max(...xv)-Math.min(...xv))*0.15);
  const qmin=Q?Math.min(...items.map(it=>it.q).filter(v=>v>0)):0,qmax=Q?Math.max(...items.map(it=>it.q).filter(v=>v>0)):1;const cmax=C?Math.max(...items.map(it=>it.n||0)):1,cmin=C?Math.min(...items.map(it=>it.n||0)):1;
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||(dot?(Rr?Rr.name:'Gene ratio'):`−log10(${Q?Q.name:'P'})`),padL:Math.max(0,labW-fs0*1.6),padR:(dot||C)?fs0*6.5:0,hIn:(spec.opts||{}).hIn==null?Math.max(1.5,n*0.26):0});const {xOf,yOf,a,fs,txt,x0,plotW,padT}=F;const grad=['#1F77B4','#D62728'];const colQ=q=>q>0&&Q?figGrad(grad,1-(Math.log10(q)-Math.log10(qmin))/((Math.log10(qmax)-Math.log10(qmin))||1)):'#1F77B4';
  let body='';const bh=(yOf(0)-yOf(1))*0.65;items.forEach((it,i)=>{const cy=yOf(n-i-0.5);if(dot){const r=fs*0.3+fs*0.5*Math.sqrt(((it.n||cmin)-cmin)/((cmax-cmin)||1));body+=`<circle cx="${xOf(it.ratio||0)}" cy="${cy}" r="${r}" fill="${colQ(it.q)}" stroke="#333" stroke-width="${a*0.4}"/>`;}else{const v=it.q>0?-Math.log10(it.q):0;body+=`<rect x="${xOf(0)}" y="${cy-bh/2}" width="${Math.max(0.5,xOf(v)-xOf(0))}" height="${bh}" fill="${C?colQ(it.q):'#1F77B4'}" fill-opacity="${+o.fillAlpha}"/>`;if(C&&it.n!=null)body+=txt(xOf(v)+fs*0.3,cy+fs*0.33,figFmt(it.n),'start',null,null,fs*0.75);}});
  let leg='';const lx=x0+plotW+fs*1.2;let ly=padT+fs*0.4;if(Q){const gid='eng'+Math.random().toString(36).slice(2,6);leg+=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${grad.map((c,k)=>`<stop offset="${k*100}%" stop-color="${c}"/>`).join('')}</linearGradient></defs>`+txt(lx,ly+fs*0.6,Q.name,'start',null,null,fs*0.75)+`<rect x="${lx}" y="${ly+fs*1.0}" width="${fs*0.7}" height="${fs*3}" fill="url(#${gid})" stroke="#000" stroke-width="${a*0.4}"/>`+txt(lx+fs*1.0,ly+fs*1.6,figSci(qmin),'start',null,null,fs*0.7)+txt(lx+fs*1.0,ly+fs*4.0,figSci(qmax),'start',null,null,fs*0.7);ly+=fs*5;}
  if(dot&&C){leg+=txt(lx,ly+fs*0.6,'Count','start',null,null,fs*0.75);const vals=[cmin,Math.round((cmin+cmax)/2),cmax].filter((v,i,arr)=>arr.indexOf(v)===i);let cy=ly+fs*1.6;vals.forEach(v=>{const r=fs*0.3+fs*0.5*Math.sqrt((v-cmin)/((cmax-cmin)||1));leg+=`<circle cx="${lx+fs*0.8}" cy="${cy}" r="${r}" fill="#999" stroke="#333" stroke-width="${a*0.4}"/>`+txt(lx+fs*2.0,cy+fs*0.3,figFmt(v),'start',null,null,fs*0.75);cy+=fs*1.9;});}
  const R=F.wrap(`<g data-sel="series:0">${body}</g>${leg?`<g data-sel="legend2">${leg}</g>`:''}`);R.res={n,total:T.raw.filter(v=>v!=='').length,dot};return R;}

// Seurat 型ドットプロット
function figRenderDotplot(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;const G=d.gene||cols.find(c=>figTextCol(c)),Cl=d.cluster||cols.find(c=>c!==G&&figTextCol(c))||cols.find(c=>c!==G&&c.raw.every(v=>v===''||/^\d+$/.test(v)));const P=d.pct||cols.find(c=>c!==G&&c!==Cl&&c.vals.some(v=>v!==null)),A=d.avg||cols.find(c=>![G,Cl,P].includes(c)&&c.vals.some(v=>v!==null));if(!G||!Cl||!P)return figOmEmpty('Gene, Cluster, Pct（Avg）の列が必要です');
  const genes=[...new Set(G.raw.filter(v=>v!==''))],cls=[...new Set(Cl.raw.filter(v=>v!==''))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));const cell={};G.raw.forEach((g,i)=>{if(g===''||Cl.raw[i]==='')return;cell[g+'\u0001'+Cl.raw[i]]={pct:P.vals[i],avg:A?A.vals[i]:null};});
  const avgOf={};if(A&&o.dpScale)genes.forEach(g=>{const v=cls.map(c=>(cell[g+'\u0001'+c]||{}).avg).filter(x=>x!==null);const m=mean(v),s=sd(v)||1;avgOf[g]=x=>(x-m)/s;});const allA=[];genes.forEach(g=>cls.forEach(c=>{const x=cell[g+'\u0001'+c];if(x&&x.avg!==null)allA.push(avgOf[g]?avgOf[g](x.avg):x.avg);}));const amin=allA.length?Math.min(...allA):0,amax=allA.length?Math.max(...allA):1;
  const fs0=F0(o);const labW=Math.max(...genes.map(g=>figSchTW(g,fs0)))+fs0*0.5;const xs={lo:0,hi:cls.length,cat:true,ticks:cls.map((c,i)=>({v:i+0.5,l:String(c)}))},ys={lo:0,hi:genes.length,cat:true,ticks:genes.map((g,i)=>({v:genes.length-i-0.5,l:g}))};
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||Cl.name,padL:Math.max(0,labW-fs0*1.6),padR:fs0*6.5,wIn:(spec.opts||{}).wIn==null?Math.max(1.5,cls.length*0.32):0,hIn:(spec.opts||{}).hIn==null?Math.max(1.2,genes.length*0.3):0,xRot:cls.some(c=>String(c).length>3)?45:0});const {xOf,yOf,a,fs,txt,x0,plotW,padT}=F;const grad=['#D9D9D9','#FCAE91','#DE2D26','#67000D'];const cw=Math.min(xOf(1)-xOf(0),yOf(0)-yOf(1));
  let body='';genes.forEach((g,gi)=>cls.forEach((c,ci)=>{const x=cell[g+'\u0001'+c];if(!x||x.pct===null)return;const r=cw*0.45*Math.sqrt(Math.max(0,Math.min(100,x.pct))/100);const v=x.avg===null?null:(avgOf[g]?avgOf[g](x.avg):x.avg);body+=`<circle cx="${xOf(ci+0.5)}" cy="${yOf(genes.length-gi-0.5)}" r="${r}" fill="${v===null?'#999':figGrad(grad,(v-amin)/((amax-amin)||1))}" stroke="#333" stroke-width="${a*0.3}"/>`;}));
  const lx=x0+plotW+fs*1.2;let leg=txt(lx,padT+fs*0.8,A?(o.dpScale?'Avg (z)':A.name):'','start',null,null,fs*0.75);const gid='dpg'+Math.random().toString(36).slice(2,6);if(A)leg+=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${grad.map((c,k)=>`<stop offset="${k/(grad.length-1)*100}%" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${lx}" y="${padT+fs*1.2}" width="${fs*0.7}" height="${fs*3}" fill="url(#${gid})" stroke="#000" stroke-width="${a*0.4}"/>`+txt(lx+fs*1.0,padT+fs*1.8,figFmt(+amax.toPrecision(2)),'start',null,null,fs*0.7)+txt(lx+fs*1.0,padT+fs*4.2,figFmt(+amin.toPrecision(2)),'start',null,null,fs*0.7);
  let cy=padT+fs*6.2;leg+=txt(lx,cy-fs*0.3,'Pct. exp.','start',null,null,fs*0.75);[25,50,75,100].forEach(p=>{cy+=fs*1.3;leg+=`<circle cx="${lx+fs*0.6}" cy="${cy}" r="${cw*0.45*Math.sqrt(p/100)}" fill="#999" stroke="#333" stroke-width="${a*0.3}"/>`+txt(lx+fs*1.8,cy+fs*0.3,p+'%','start',null,null,fs*0.7);});
  const R=F.wrap(`<g data-sel="series:0">${body}</g><g data-sel="legend2">${leg}</g>`);R.res={genes:genes.length,clusters:cls.length,scaled:!!(A&&o.dpScale)};return R;}

// SBS96
function figRenderSBS96(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const Tc=d.first;const V=d.parsed.cols.find(c=>c!==Tc&&c.vals.some(v=>v!==null));if(!Tc||!V)return figOmEmpty('Type, Count の列が必要です');
  const subs=['C>A','C>G','C>T','T>A','T>C','T>G'],bases=['A','C','G','T'];const map={};Tc.raw.forEach((t,i)=>{const m=/^([ACGT])\[([ACGT]>[ACGT])\]([ACGT])$/i.exec(String(t).trim());if(m&&V.vals[i]!==null)map[(m[1]+'['+m[2]+']'+m[3]).toUpperCase()]=V.vals[i];});const keys=[];subs.forEach(s=>bases.forEach(l=>bases.forEach(r=>keys.push(l+'['+s+']'+r))));
  const tot=keys.reduce((s,k)=>s+(map[k]||0),0)||1;const vals=keys.map(k=>o.sbsPct?(map[k]||0)/tot*100:(map[k]||0));const st=figStyle(spec);const {fs,a,ac,txt}=st;const W0=((spec.opts||{}).wIn==null?6:+o.wIn)*FIG_IN,H0=((spec.opts||{}).hIn==null?1.6:+o.hIn)*FIG_IN;const padL=fs*3.6,padT=fs*(spec.title?3.2:0.6)+fs*1.6,padB=fs*3.2;const W=padL+W0+fs*0.6,H=padT+H0+padB;const bw=W0/96;
  const ys=figAxisLin(0,Math.max(...vals)*1.08||1,4);const yOf=v=>padT+H0-(v-ys.lo)/(ys.hi-ys.lo)*H0;let s='';subs.forEach((sub,si)=>{const x1=padL+si*16*bw,x2=padL+(si+1)*16*bw-bw*0.3;s+=`<rect x="${x1}" y="${padT-fs*1.5}" width="${x2-x1}" height="${fs*0.8}" fill="${FIG_SBS_COLORS[sub]}"/>`+txt((x1+x2)/2,padT-fs*1.75,sub,'middle',null,null,fs*0.9);});
  keys.forEach((k,i)=>{const sub=k.slice(2,5);s+=`<rect x="${padL+i*bw+bw*0.15}" y="${yOf(vals[i])}" width="${bw*0.7}" height="${yOf(0)-yOf(vals[i])}" fill="${FIG_SBS_COLORS[sub]}"/>`;});
  s+=`<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${padT+H0}" stroke="${ac}" stroke-width="${a}"/><line x1="${padL}" y1="${padT+H0}" x2="${padL+W0}" y2="${padT+H0}" stroke="${ac}" stroke-width="${a}"/>`;ys.ticks.forEach(t=>{s+=`<line x1="${padL}" y1="${yOf(t.v)}" x2="${padL-fs*0.4}" y2="${yOf(t.v)}" stroke="${ac}" stroke-width="${a}"/>`+txt(padL-fs*0.6,yOf(t.v)+fs*0.33,t.l,'end',null,null,fs*0.8);});
  if(W0/96>fs*0.45)keys.forEach((k,i)=>{s+=txt(padL+i*bw+bw/2,padT+H0+fs*0.5,k[0]+k[2]+k[6],'end',`transform="rotate(-90 ${padL+i*bw+bw/2} ${padT+H0+fs*0.5})"`,null,fs*0.5);});
  s+=txt(padL-fs*2.6,padT+H0/2,o.yTitle||(o.sbsPct?'Percentage of SBS':'Number of SBS'),'middle',`transform="rotate(-90 ${padL-fs*2.6} ${padT+H0/2})"`,null,fs*0.9);const title=spec.title?txt(padL+W0/2,fs*1.3,spec.title,'middle','','title'):'';
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="axes"></g>${s}${title}</svg>`,w:W,h:H,plot:{x0:padL,y0:padT,w:W0,h:H0},res:{total:tot,found:Object.keys(map).length,bySub:subs.map(sub=>({sub,n:keys.filter(k=>k.slice(2,5)===sub).reduce((a,k)=>a+(map[k]||0),0)}))}};}

// オンコプリント
function figRenderOncoprint(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;if(!d.firstColText||cols.length<2)return figOmEmpty('1 列目＝遺伝子、見出し＝検体名の表が必要です');
  const genes=d.rowLabels.filter(v=>v!=='');const samples=cols.slice(1);const kind=v=>{const s=String(v||'').trim().toLowerCase();if(!s||s==='0'||s==='-'||s==='wt'||s==='none')return null;if(/;|,|\//.test(s))return 'multi';if(/missense/.test(s))return 'missense';if(/nonsense|stop|trunc/.test(s))return 'nonsense';if(/frame/.test(s))return 'frameshift';if(/splice/.test(s))return 'splice';if(/inframe|in-frame|indel/.test(s))return 'inframe';if(/amp|gain/.test(s))return 'amp';if(/del|loss|hom/.test(s))return 'del';if(/fus/.test(s))return 'fusion';return 'other';};
  const M=genes.map((g,gi)=>samples.map(c=>kind(c.raw[d.rowLabels.indexOf(g)])));const gOrder=genes.map((_,i)=>i).sort((a,b)=>M[b].filter(Boolean).length-M[a].filter(Boolean).length);
  let sOrder=samples.map((_,j)=>j);if(o.opSort)sOrder.sort((a,b)=>{for(const gi of gOrder){const va=M[gi][a]?1:0,vb=M[gi][b]?1:0;if(va!==vb)return vb-va;}return a-b;});
  const fs0=F0(o);const labW=Math.max(...genes.map(g=>figSchTW(g,fs0)))+fs0*0.5;const cw=Math.max(fs0*0.25,Math.min(fs0*1.2,(((spec.opts||{}).wIn==null?4:+o.wIn)*FIG_IN)/samples.length)),ch=fs0*1.3,gap=FIG_PT*0.8;const pctW=o.opPct?fs0*3:0;const padL=labW+pctW+fs0*0.3,padT=fs0*(spec.title?2.4:0.8)+fs0*0.3;const W=padL+samples.length*cw+fs0*0.5,H=padT+genes.length*ch+fs0*0.6;
  const st=figStyle(spec);const {fs,a,txt}=st;let s='';gOrder.forEach((gi,r)=>{const y=padT+r*ch;const n=M[gi].filter(Boolean).length;s+=txt(fs*0.2,y+ch/2+fs*0.33,genes[gi],'start',null,null,fs*0.9);if(o.opPct)s+=txt(labW+pctW-fs*0.2,y+ch/2+fs*0.3,`${(n/samples.length*100).toFixed(0)}%`,'end',null,null,fs*0.75);
    sOrder.forEach((sj,c)=>{const x=padL+c*cw;const k=M[gi][sj];s+=`<rect x="${x+gap/2}" y="${y+gap/2}" width="${cw-gap}" height="${ch-gap}" fill="${k?(FIG_ONCO_COLORS[k]||FIG_ONCO_COLORS.other):'#E8E8E8'}"/>`;});});
  const used=[...new Set(M.flat().filter(Boolean))].sort();let legY=H;let lx=padL,legend='';used.forEach(k=>{legend+=`<rect x="${lx}" y="${legY+fs*0.3}" width="${fs*1.1}" height="${fs*0.8}" fill="${FIG_ONCO_COLORS[k]||FIG_ONCO_COLORS.other}"/>`+txt(lx+fs*1.4,legY+fs*1.0,k,'start',null,null,fs*0.8);lx+=fs*1.6+figSchTW(k,fs*0.8)+fs*1.2;});const Hh=H+fs*1.8;const W2=Math.max(W,lx);
  const title=spec.title?txt(padL+samples.length*cw/2,fs*1.4,spec.title,'middle','','title'):'';const altered=sOrder.filter(sj=>M.some(row=>row[sj])).length;
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W2}" height="${Hh}" viewBox="0 0 ${W2} ${Hh}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="series:0">${s}</g><g data-sel="legend">${legend}</g>${title}</svg>`,w:W2,h:Hh,plot:{x0:padL,y0:padT,w:samples.length*cw,h:genes.length*ch},res:{genes:genes.length,samples:samples.length,altered,pct:altered/samples.length*100,perGene:gOrder.map(gi=>({gene:genes[gi],n:M[gi].filter(Boolean).length}))}};}

// 配列ロゴ
function figRenderLogo(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const cols=d.parsed.cols;let pfm=null,L=0,nseq=0;
  const bA=cols.find(c=>/^a$/i.test(c.name)),bC=cols.find(c=>/^c$/i.test(c.name)),bG=cols.find(c=>/^g$/i.test(c.name)),bT=cols.find(c=>/^[tu]$/i.test(c.name));
  if(bA&&bC&&bG&&bT){L=bA.vals.filter(v=>v!==null).length;pfm=[];for(let i=0;i<L;i++){const row={A:bA.vals[i]||0,C:bC.vals[i]||0,G:bG.vals[i]||0,T:bT.vals[i]||0};const tot=row.A+row.C+row.G+row.T||1;pfm.push({A:row.A/tot,C:row.C/tot,G:row.G/tot,T:row.T/tot});}nseq=Math.round(bA.vals.slice(0,1).reduce((s,v)=>s+(v||0),0)+bC.vals[0]+bG.vals[0]+bT.vals[0]);}
  else{const seqs=cols[0].raw.concat(d.firstColText?[]:[cols[0].name]).map(v=>String(v).trim().toUpperCase().replace(/U/g,'T')).filter(v=>/^[ACGTN-]+$/.test(v));if(!seqs.length)return figOmEmpty('配列（ACGT）か PFM（A, C, G, T 列）が必要です');L=Math.min(...seqs.map(s=>s.length));nseq=seqs.length;pfm=[];for(let i=0;i<L;i++){const cnt={A:0,C:0,G:0,T:0};let n=0;seqs.forEach(s=>{if(cnt[s[i]]!==undefined){cnt[s[i]]++;n++;}});pfm.push({A:cnt.A/(n||1),C:cnt.C/(n||1),G:cnt.G/(n||1),T:cnt.T/(n||1)});}}
  const bits=o.logoBits!=='false'&&o.logoBits!==false;const st=figStyle(spec);const {fs,a,ac,txt}=st;const colW=fs*1.6,H0=((spec.opts||{}).hIn==null?1.3:+o.hIn)*FIG_IN;const padL=fs*3.2,padT=fs*(spec.title?2.4:0.8),padB=fs*2.6;const W=padL+L*colW+fs*0.5,H=padT+H0+padB;const ymax=bits?2:1;const yOf=v=>padT+H0-v/ymax*H0;
  let s='';pfm.forEach((p,i)=>{let info=0;if(bits){let hh=0;for(const b of 'ACGT'){if(p[b]>0)hh-=p[b]*Math.log2(p[b]);}info=2-hh;}const order=['A','C','G','T'].sort((x,y)=>p[x]-p[y]);let y=yOf(0);order.forEach(b=>{const hgt=(bits?info*p[b]:p[b])/ymax*H0;if(hgt<0.5)return;const cx=padL+i*colW+colW/2;s+=`<text x="0" y="0" font-family="Arial Black, Arial, Helvetica, sans-serif" font-weight="bold" font-size="${fs*1.6}" text-anchor="middle" fill="${FIG_BASE_COLORS[b]}" transform="translate(${cx} ${y}) scale(1 ${hgt/(fs*1.6*0.72)})" dominant-baseline="auto">${b}</text>`;y-=hgt;});});
  s+=`<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${padT+H0}" stroke="${ac}" stroke-width="${a}"/>`;figNiceTicks(0,ymax,bits?4:5).ticks.forEach(v=>{s+=`<line x1="${padL}" y1="${yOf(v)}" x2="${padL-fs*0.4}" y2="${yOf(v)}" stroke="${ac}" stroke-width="${a}"/>`+txt(padL-fs*0.6,yOf(v)+fs*0.33,figFmt(v),'end',null,null,fs*0.85);});for(let i=0;i<L;i++)s+=txt(padL+i*colW+colW/2,padT+H0+fs*1.2,String(i+1),'middle',null,null,fs*0.8);
  s+=txt(padL-fs*2.3,padT+H0/2,bits?'Bits':'Frequency','middle',`transform="rotate(-90 ${padL-fs*2.3} ${padT+H0/2})"`,null,fs*0.9)+txt(padL+L*colW/2,padT+H0+fs*2.3,o.xTitle||'Position','middle',null,null,fs*0.9);const title=spec.title?txt(padL+L*colW/2,fs*1.3,spec.title,'middle','','title'):'';
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="axes"></g>${s}${title}</svg>`,w:W,h:H,plot:{x0:padL,y0:padT,w:L*colW,h:H0},res:{L,nseq,bits,pfm}};}

// サンキー（段ごとのノード配置、帯は三次曲線）
function figRenderSankey(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const Fm=d.from,To=d.to;const V=d.value||d.parsed.cols.find(c=>c!==Fm&&c!==To&&c.vals.some(v=>v!==null));if(!Fm||!To)return figOmEmpty('From, To, Value の列が必要です');
  const links=[];Fm.raw.forEach((f,i)=>{const t=To.raw[i];const v=V?V.vals[i]:1;if(f===''||t===''||!(v>0)||f===t)return;links.push({s:f,t,v});});if(!links.length)return figOmEmpty('リンクがありません');
  const names=[...new Set(links.flatMap(l=>[l.s,l.t]))];const nodes={};names.forEach(n=>nodes[n]={name:n,out:0,inn:0,layer:0});links.forEach(l=>{nodes[l.s].out+=l.v;nodes[l.t].inn+=l.v;});
  for(let it=0;it<names.length;it++){let ch=false;links.forEach(l=>{if(nodes[l.t].layer<=nodes[l.s].layer&&nodes[l.t].layer<names.length){nodes[l.t].layer=nodes[l.s].layer+1;ch=true;}});if(!ch)break;}const nl=Math.max(...names.map(n=>nodes[n].layer))+1;
  const layers=[];names.forEach(n=>{(layers[nodes[n].layer]=layers[nodes[n].layer]||[]).push(nodes[n]);});for(let li=1;li<layers.length;li++){const L=layers[li]||[];const bc={};L.forEach(n=>{const src=links.filter(l=>l.t===n.name);bc[n.name]=src.length?src.reduce((s,l)=>s+(layers[nodes[l.s].layer]||[]).indexOf(nodes[l.s]),0)/src.length:999;});L.sort((a,b)=>bc[a.name]-bc[b.name]);}
  const st=figStyle(spec);const {fs,txt}=st;const W0=((spec.opts||{}).wIn==null?4:+o.wIn)*FIG_IN,H0=((spec.opts||{}).hIn==null?2.5:+o.hIn)*FIG_IN;const nw=fs*0.9,gap=fs*0.6;const padL=fs*0.5,padT=fs*(spec.title?2.4:0.8),padR=fs*0.5;const maxTot=Math.max(...layers.map(L=>L.reduce((s,n)=>s+Math.max(n.out,n.inn),0)+(L.length-1)*gap/1));const scale=(H0-gap*Math.max(0,Math.max(...layers.map(L=>L.length))-1))/Math.max(...layers.map(L=>L.reduce((s,n)=>s+Math.max(n.out,n.inn),0)));
  layers.forEach((L,li)=>{const tot=L.reduce((s,n)=>s+Math.max(n.out,n.inn)*scale,0)+(L.length-1)*gap;let y=padT+(H0-tot)/2;L.forEach(n=>{n.h=Math.max(n.out,n.inn)*scale;n.x=padL+li*((W0-nw)/Math.max(1,nl-1));n.y=y;y+=n.h+gap;n.so=0;n.si=0;});});
  const colOf={};names.forEach((n,i)=>colOf[n]=FIG_PAL20[i%20]);let paths='';links.slice().sort((a,b)=>nodes[a.s].y-nodes[b.s].y||nodes[a.t].y-nodes[b.t].y).forEach(l=>{const S=nodes[l.s],T=nodes[l.t];const h=l.v*scale;const y1=S.y+S.so,y2=T.y+T.si;S.so+=h;T.si+=h;const x1=S.x+nw,x2=T.x;const cx=(x1+x2)/2;paths+=`<path d="M${x1},${y1} C${cx},${y1} ${cx},${y2} ${x2},${y2} L${x2},${y2+h} C${cx},${y2+h} ${cx},${y1+h} ${x1},${y1+h}z" fill="${colOf[l.s]}" fill-opacity="0.4"/>`;});
  let ns='';names.forEach(n=>{const N=nodes[n];ns+=`<rect x="${N.x}" y="${N.y}" width="${nw}" height="${N.h}" fill="${colOf[n]}" stroke="#333" stroke-width="${FIG_PT*0.5}"/>`;const right=N.layer<nl-1;const lab=n+(o.skVals?` (${figFmt(+Math.max(N.out,N.inn).toPrecision(4))})`:'');ns+=txt(right?N.x+nw+fs*0.3:N.x-fs*0.3,N.y+N.h/2+fs*0.33,lab,right?'start':'end',null,null,fs*0.85);});
  const labW=Math.max(...names.map(n=>figSchTW(n+(o.skVals?' (0000)':''),fs*0.85)))+fs*0.5;const W=padL+W0+padR+labW*2,H=padT+H0+fs*0.8;const shift=labW;const title=spec.title?txt(shift+padL+W0/2,fs*1.3,spec.title,'middle','','title'):'';
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/><g transform="translate(${shift} 0)"><g data-sel="series:0">${paths}</g><g data-sel="axes">${ns}</g></g>${title}</svg>`,w:W,h:H,plot:{x0:shift+padL,y0:padT,w:W0,h:H0},res:{nodes:names.length,links:links.length,layers:nl,total:links.reduce((s,l)=>s+l.v,0)}};}

// ランクプロット
function figRenderRank(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const G=d.first;const S=d.score||d.parsed.cols.find(c=>c!==G&&c.vals.some(v=>v!==null));if(!S)return figOmEmpty('Gene, Score の列が必要です');
  const items=S.vals.map((v,i)=>v===null?null:({name:d.firstColText?G.raw[i]:String(i+1),v})).filter(Boolean).sort((a,b)=>b.v-a.v);const n=items.length;if(!n)return figOmEmpty('行がありません');
  const hi=new Set(String(o.rankHi||'').split(/[,、\s]+/).filter(Boolean));const nl=+o.rankN||0;const lab=new Set(items.slice(0,nl).map(it=>it.name));items.slice(-Math.min(nl,n)).forEach(it=>lab.add(it.name));
  const vals=items.map(it=>it.v);const yp=(Math.max(...vals)-Math.min(...vals))*0.08||1;const [ylo,yhi]=figYRange(o,Math.min(...vals)-yp,Math.max(...vals)+yp);const ys=figAxisLin(ylo,yhi,5);const xs=figAxisLin(0,n,5);xs.lo=0;
  const F=figFrame(spec,{x:xs,y:ys,xTitle:o.xTitle||'Rank',yTitle:o.yTitle||S.name});const {xOf,yOf,S:So,a,fs,txt}=F;const c=So(0).color;
  let s=`<polyline points="${items.map((it,i)=>`${xOf(i+1)},${yOf(it.v)}`).join(' ')}" fill="none" stroke="${c}" stroke-width="${So(0).lineW*FIG_PT}"/>`;if(0>ys.lo&&0<ys.hi)s+=`<line x1="${F.x0}" y1="${yOf(0)}" x2="${F.x0+F.plotW}" y2="${yOf(0)}" stroke="#aaa" stroke-width="${a*0.5}"/>`;
  let labels='';const sel=items.map((it,i)=>({it,i,H:hi.has(it.name)})).filter(x=>x.H||lab.has(x.it.name));const topL=sel.filter(x=>x.i<n/2),botL=sel.filter(x=>x.i>=n/2);
  const list=(arr,top)=>{if(!arr.length)return;const lx=top?xOf(arr[0].i+1)+fs*2.2:xOf(arr[arr.length-1].i+1)-fs*2.2;let ly=top?yOf(arr[0].it.v)+fs*0.3:yOf(arr[arr.length-1].it.v)-fs*0.3-(arr.length-1)*fs*0.9;arr.forEach(x=>{const px=xOf(x.i+1),py=yOf(x.it.v);s+=`<circle cx="${px}" cy="${py}" r="${fs*0.28}" fill="${x.H?'#D62728':c}"/>`;s+=`<line x1="${px}" y1="${py}" x2="${top?lx-fs*0.2:lx+fs*0.2}" y2="${ly-fs*0.25}" stroke="#bbb" stroke-width="${a*0.4}"/>`;labels+=txt(lx,ly,x.it.name,top?'start':'end',x.H?'fill="#D62728"':null,null,fs*0.7);ly+=fs*0.9;});};list(topL,true);list(botL,false);
  const R=F.wrap(`<g data-sel="series:0">${s}</g><g data-sel="text">${labels}</g>`);R.res={n,top:items.slice(0,5),bottom:items.slice(-5)};return R;}

// ネットワーク（Fruchterman–Reingold、固定シード）
function figRenderNetwork(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const Fm=d.from,To=d.to;if(!Fm||!To)return figOmEmpty('From, To の列が必要です');const Wc=d.value;
  const edges=[];Fm.raw.forEach((f,i)=>{const t=To.raw[i];if(f===''||t==='')return;edges.push({s:f,t,w:Wc&&Wc.vals[i]!==null?Wc.vals[i]:1});});const names=[...new Set(edges.flatMap(e=>[e.s,e.t]))];const n=names.length;if(!n)return figOmEmpty('ノードがありません');
  const idx={};names.forEach((nm,i)=>idx[nm]=i);const deg=new Array(n).fill(0);edges.forEach(e=>{deg[idx[e.s]]++;deg[idx[e.t]]++;});const R=figRng(7);const L=1;const pos=names.map((_,i)=>[Math.cos(i/n*2*Math.PI)+R.u()*0.1,Math.sin(i/n*2*Math.PI)+R.u()*0.1]);const k=Math.sqrt(1/n)*1.4;let temp=0.3;
  for(let it=0;it<300;it++){const disp=pos.map(()=>[0,0]);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const dx=pos[i][0]-pos[j][0],dy=pos[i][1]-pos[j][1];const dd=Math.max(1e-4,Math.hypot(dx,dy));const f=k*k/dd;disp[i][0]+=dx/dd*f;disp[i][1]+=dy/dd*f;disp[j][0]-=dx/dd*f;disp[j][1]-=dy/dd*f;}
    edges.forEach(e=>{const i=idx[e.s],j=idx[e.t];const dx=pos[i][0]-pos[j][0],dy=pos[i][1]-pos[j][1];const dd=Math.max(1e-4,Math.hypot(dx,dy));const f=dd*dd/k*Math.min(3,Math.max(0.3,e.w));disp[i][0]-=dx/dd*f;disp[i][1]-=dy/dd*f;disp[j][0]+=dx/dd*f;disp[j][1]+=dy/dd*f;});
    for(let i=0;i<n;i++){const dd=Math.hypot(disp[i][0],disp[i][1])||1e-9;const m=Math.min(dd,temp);pos[i][0]+=disp[i][0]/dd*m;pos[i][1]+=disp[i][1]/dd*m;}temp*=0.985;}
  const st=figStyle(spec);const {fs,txt,S}=st;const W0=((spec.opts||{}).wIn==null?3.2:+o.wIn)*FIG_IN,H0=((spec.opts||{}).hIn==null?3.2:+o.hIn)*FIG_IN;const pad=fs*2.5,padT=fs*(spec.title?2.4:0.8);const xs=pos.map(p=>p[0]),ys=pos.map(p=>p[1]);const x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys);const X=v=>pad+(v-x0)/((x1-x0)||1)*W0,Y=v=>padT+pad*0.5+(v-y0)/((y1-y0)||1)*H0;
  const maxW=Math.max(...edges.map(e=>e.w));let es='';edges.forEach(e=>{es+=`<line x1="${X(pos[idx[e.s]][0])}" y1="${Y(pos[idx[e.s]][1])}" x2="${X(pos[idx[e.t]][0])}" y2="${Y(pos[idx[e.t]][1])}" stroke="#999" stroke-width="${FIG_PT*(0.5+1.5*e.w/maxW)}" stroke-opacity="0.7"/>`;});
  const maxD=Math.max(...deg);let ns='';names.forEach((nm,i)=>{const r=fs*0.35+fs*0.45*Math.sqrt(deg[i]/maxD);const col=S(0).color;ns+=`<circle cx="${X(pos[i][0])}" cy="${Y(pos[i][1])}" r="${r}" fill="${col}" fill-opacity="0.85" stroke="#fff" stroke-width="${FIG_PT*0.6}"/>`;if(o.netLabels)ns+=`<text x="${X(pos[i][0])}" y="${Y(pos[i][1])-r-fs*0.25}" font-family="${FIG_DEF.font}" font-size="${fs*0.75}" text-anchor="middle" fill="#000" stroke="#fff" stroke-width="${fs*0.15}" paint-order="stroke">${figEsc(nm)}</text>`;});
  const W=pad*2+W0,H=padT+pad+H0;const title=spec.title?txt(W/2,fs*1.3,spec.title,'middle','','title'):'';
  return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="axes">${es}</g><g data-sel="series:0">${ns}</g>${title}</svg>`,w:W,h:H,plot:{x0:pad,y0:padT,w:W0,h:H0},res:{nodes:n,edges:edges.length,hubs:names.map((nm,i)=>({name:nm,deg:deg[i]})).sort((a,b)=>b.deg-a.deg).slice(0,5)}};}

// 系統樹（Newick → 矩形）
function figParseNewick(s){let i=0;const str=String(s).trim();const node=()=>{const nd={children:[],name:'',len:0};if(str[i]==='('){i++;for(;;){nd.children.push(node());if(str[i]===',')i++;else if(str[i]===')'){i++;break;}else break;}}let nm='';while(i<str.length&&!/[:,();]/.test(str[i]))nm+=str[i++];nd.name=nm.trim().replace(/^'|'$/g,'');if(str[i]===':'){i++;let l='';while(i<str.length&&/[0-9.eE+-]/.test(str[i]))l+=str[i++];nd.len=+l||0;}return nd;};const root=node();return root;}
function figRenderTree(spec){const d=spec.data,o=Object.assign({},FIG_DEF,spec.opts||{});const raw=[d.first.name].concat(d.first.raw).find(v=>/^\(.*\)[^()]*;?$/.test(String(v).trim()));if(!raw)return figOmEmpty('Newick 文字列（例 ((A:1,B:1):1,C:2);）が必要です');let root;try{root=figParseNewick(raw);}catch(e){return figOmEmpty('Newick を読めませんでした');}
  const leaves=[];const useLen=o.treeLen!==false;let depthMax=0;const walk=(nd,depth)=>{nd.d=depth;if(!nd.children.length){leaves.push(nd);depthMax=Math.max(depthMax,depth);return;}nd.children.forEach(c=>walk(c,depth+(useLen?c.len:1)));};walk(root,0);const nl=leaves.length;if(!nl)return figOmEmpty('葉がありません');
  const st=figStyle(spec);const {fs,a,ac,txt}=st;const W0=((spec.opts||{}).wIn==null?2.5:+o.wIn)*FIG_IN;const rowH=fs*1.4;const labW=Math.max(...leaves.map(l=>figSchTW(l.name,fs*0.9)))+fs*0.6;const padL=fs*0.5,padT=fs*(spec.title?2.4:0.8);const W=padL+W0+labW+fs*0.5,H=padT+nl*rowH+fs*2.4;const X=dp=>padL+dp/(depthMax||1)*W0;
  let yi=0;const place=nd=>{if(!nd.children.length){nd.y=padT+(yi+0.5)*rowH;yi++;return nd.y;}const ys=nd.children.map(place);nd.y=(Math.min(...ys)+Math.max(...ys))/2;return nd.y;};place(root);let s='';const draw=nd=>{if(nd.children.length){const x=X(nd.d);s+=`<line x1="${x}" y1="${Math.min(...nd.children.map(c=>c.y))}" x2="${x}" y2="${Math.max(...nd.children.map(c=>c.y))}" stroke="${ac}" stroke-width="${a}"/>`;nd.children.forEach(c=>{s+=`<line x1="${x}" y1="${c.y}" x2="${X(c.d)}" y2="${c.y}" stroke="${ac}" stroke-width="${a}"/>`;draw(c);});if(nd.name&&nd!==root)s+=txt(x-fs*0.2,nd.y-fs*0.3,nd.name,'end',null,null,fs*0.65);}else s+=txt(X(nd.d)+fs*0.3,nd.y+fs*0.33,nd.name,'start',null,null,fs*0.9);};draw(root);
  if(useLen&&depthMax>0){const t=figNiceTicks(0,depthMax,4);const y=padT+nl*rowH+fs*0.6;s+=`<line x1="${X(0)}" y1="${y}" x2="${X(t.ticks[t.ticks.length-1])}" y2="${y}" stroke="${ac}" stroke-width="${a*0.75}"/>`;t.ticks.forEach(v=>{s+=`<line x1="${X(v)}" y1="${y}" x2="${X(v)}" y2="${y+fs*0.3}" stroke="${ac}" stroke-width="${a*0.75}"/>`+txt(X(v),y+fs*1.2,figFmt(v),'middle',null,null,fs*0.7);});}
  const title=spec.title?txt(W/2,fs*1.3,spec.title,'middle','','title'):'';return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/><g data-sel="series:0">${s}</g>${title}</svg>`,w:W,h:H,plot:{x0:padL,y0:padT,w:W0,h:nl*rowH},res:{leaves:nl,depth:depthMax,useLen}};}

/* ---------- 結果表 ---------- */
function figStatsP4(data,st){if(!data||data.kind!=='omics')return null;const r=st.res||{};const esc=figEsc;if(r.error)return `<div class="hint">${esc(r.error)}</div>`;const t=st.type;
  if(t==='manhattan')return `<div class="hint">n = ${r.n}、染色体 ${r.chrs} ／ P < 5×10⁻⁸: ${r.gw} 点、P < 1×10⁻⁵: ${r.sug} 点</div>`+(r.top&&r.top.length?'<table><tr><th>上位</th><th>CHR</th><th>BP</th><th>P</th></tr>'+r.top.slice(0,5).map(p=>`<tr><td>${esc(p.id||'')}</td><td>${esc(p.cl)}</td><td>${figFmt(p.bp)}</td><td>${figSci(p.p)}</td></tr>`).join('')+'</table>':'');
  if(t==='embedding')return `<div class="hint">n = ${r.n}${r.cont?' ／ 色＝'+esc(r.cont):''}</div>`+(r.clusters&&r.clusters.length?'<table><tr><th>クラスタ</th><th>n</th></tr>'+r.clusters.map(c=>`<tr><td>${esc(c.name)}</td><td>${c.n}</td></tr>`).join('')+'</table>':'');
  if(t==='gsea')return `<div class="hint">ES = ${r.es!=null?r.es.toFixed(4):'–'}（順位 ${r.atRank} / ${r.n}）、遺伝子セットのヒット ${r.hits}、leading edge ${r.leadingEdge}。重み p = 1（|指標|）。NES・P・FDR は順列検定が要るので JSON の nes / pval / fdr に GSEA ソフトの値を入れてください。</div>`;
  if(t==='enrich-bar'||t==='enrich-dot')return `<div class="hint">${r.n} / ${r.total} 件を表示${r.dot?'（点の大きさ＝遺伝子数、色＝q）':'（棒＝−log10 q、文字＝遺伝子数）'}</div>`;
  if(t==='dotplot')return `<div class="hint">遺伝子 ${r.genes} × クラスタ ${r.clusters}。大きさ＝発現細胞の %、色＝平均発現${r.scaled?'（遺伝子ごとに z スコア化）':''}</div>`;
  if(t==='sbs96')return `<div class="hint">合計 ${figFmt(r.total)}（96 型のうち ${r.found} 型に値）</div><table><tr><th>置換</th><th>n</th><th>%</th></tr>${(r.bySub||[]).map(b=>`<tr><td>${b.sub}</td><td>${figFmt(b.n)}</td><td>${(b.n/r.total*100).toFixed(1)}</td></tr>`).join('')}</table>`;
  if(t==='oncoprint')return `<div class="hint">遺伝子 ${r.genes} × 検体 ${r.samples} ／ いずれかの変異あり ${r.altered} 検体（${r.pct.toFixed(1)}%）</div><table><tr><th>遺伝子</th><th>変異あり</th><th>%</th></tr>${(r.perGene||[]).map(g=>`<tr><td>${esc(g.gene)}</td><td>${g.n}</td><td>${(g.n/r.samples*100).toFixed(1)}</td></tr>`).join('')}</table>`;
  if(t==='logo')return `<div class="hint">位置 ${r.L}、配列 ${r.nseq}${r.bits?' ／ 縦軸＝情報量 2 − H（bits）':' ／ 縦軸＝頻度'}</div>`;
  if(t==='sankey')return `<div class="hint">ノード ${r.nodes}、リンク ${r.links}、段 ${r.layers} ／ 流量の合計 ${figFmt(r.total)}</div>`;
  if(t==='rank')return `<div class="hint">n = ${r.n}</div><table><tr><th>上位</th><th>値</th></tr>${(r.top||[]).map(it=>`<tr><td>${esc(it.name)}</td><td>${figFmt(+it.v.toPrecision(4))}</td></tr>`).join('')}</table>`;
  if(t==='network')return `<div class="hint">ノード ${r.nodes}、エッジ ${r.edges}（Fruchterman–Reingold 配置、点の大きさ＝次数）</div><table><tr><th>ハブ</th><th>次数</th></tr>${(r.hubs||[]).map(h=>`<tr><td>${esc(h.name)}</td><td>${h.deg}</td></tr>`).join('')}</table>`;
  if(t==='tree')return `<div class="hint">葉 ${r.leaves}、根からの最大距離 ${figFmt(+(+r.depth).toPrecision(4))}${r.useLen?'（枝の長さを使用）':'（枝の長さは無視）'}</div>`;
  return null;}

document.addEventListener('DOMContentLoaded',()=>{const sel=document.querySelector('#figKind');if(sel)FIG_KINDS_P4.forEach(([v,l])=>{const op=document.createElement('option');op.value=v;op.textContent=l;sel.appendChild(op);});});
