// BranCHAT Figure 拡張（画像パネル）
// 顕微鏡・IHC・動物写真などの画像グリッド（type "grid"）と、ゲル／ウェスタンブロットの短冊（type "blot"）を ```figure の JSON で描く。
// 画像そのものは本文に入れず、この端末の images/（デスクトップ版 /api/img、ブラウザ版は localStorage）に保存して id で参照する。
// 寸法（px）は conv.imgs[id]={w,h,name} に持つ。スケールバーは µm/px から長さを計算する（要件書 §8）。
// 注釈（矢印・＊・文字・ROI 枠）はセル内の割合座標 (x,y: 0–1) で持ち、ブロック上のツールでクリックして足す。
'use strict';

const FIG_IMG_DEF={cols:3,cellIn:1.2,gap:3,fontPt:10,widthIn:2.5};
const FIG_IMG_META={}; // 会話に無いときの寸法の控え
function figImgMeta(id){return (typeof conv!=='undefined'&&conv&&conv.imgs&&conv.imgs[id])||FIG_IMG_META[id]||null;}
// ブラウザ版（GitHub Pages など）の画像置き場: IndexedDB（localStorage は 5 MB で足りない）。起動時に全部をメモリに読み、figImgURL は同期で返す
const FIG_IMG_DATA={};
function figIdb(){return new Promise((res,rej)=>{if(!window.indexedDB){rej(new Error('IndexedDB なし'));return;}const q=indexedDB.open('branchat-figimg',1);q.onupgradeneeded=()=>{q.result.createObjectStore('imgs');};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
async function figImgPut(id,data){try{const db=await figIdb();await new Promise((res,rej)=>{const tx=db.transaction('imgs','readwrite');tx.objectStore('imgs').put(data,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});FIG_IMG_DATA[id]=data;}catch(e){try{localStorage.setItem('fimg:'+id,data);FIG_IMG_DATA[id]=data;}catch(e2){throw new Error('保存先がありません（容量不足）');}}}
async function figImgLoadAll(){try{const db=await figIdb();await new Promise((res,rej)=>{const tx=db.transaction('imgs','readonly');const st=tx.objectStore('imgs');const q=st.openCursor();q.onsuccess=()=>{const c=q.result;if(c){FIG_IMG_DATA[c.key]=c.value;c.continue();}else res();};q.onerror=()=>rej(q.error);});}catch(e){}
  try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('fimg:')&&!FIG_IMG_DATA[k.slice(5)])FIG_IMG_DATA[k.slice(5)]=localStorage.getItem(k);}}catch(e){}
  if(typeof renderAll==='function'&&Object.keys(FIG_IMG_DATA).length)try{renderAll();}catch(e){}}
if(typeof IS_DESKTOP==='undefined'||!IS_DESKTOP)document.addEventListener('DOMContentLoaded',figImgLoadAll);
function figImgURL(id){if(typeof IS_DESKTOP!=='undefined'&&IS_DESKTOP)return '/api/img/'+encodeURIComponent(id);return FIG_IMG_DATA[id]||'';}
function figIsImage(j){return !!(j&&j.kind==='image');}
// 画像を保存して {id,w,h,name} を返す。長辺 2000px まで縮小、PNG はそのまま、それ以外は JPEG
function figImgStore(file){return new Promise((res,rej)=>{const url=URL.createObjectURL(file);const im=new Image();im.onload=async()=>{URL.revokeObjectURL(url);const r=Math.min(1,2000/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*r));c.height=Math.max(1,Math.round(im.height*r));const g=c.getContext('2d');g.drawImage(im,0,0,c.width,c.height);
    const png=/png/i.test(file.type);const data=png?c.toDataURL('image/png'):c.toDataURL('image/jpeg',0.92);const id='im'+uid();const meta={w:c.width,h:c.height,name:String(file.name||'').replace(/\.[^.]+$/,'')};
    try{if(typeof IS_DESKTOP!=='undefined'&&IS_DESKTOP){const rr=await fetch('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,data})});if(!rr.ok)throw new Error('保存に失敗しました');}else{await figImgPut(id,data);}}catch(e){rej(new Error('画像を保存できませんでした（'+e.message+'）'));return;}
    FIG_IMG_META[id]=meta;if(typeof conv!=='undefined'&&conv){conv.imgs=conv.imgs||{};conv.imgs[id]=meta;}res({id,...meta});};im.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('画像を読めませんでした'));};im.src=url;});}
// SVG 内の画像参照を data URL に置き換える（PNG 書き出し・添付用。<img> として読む SVG は外部参照を読めない）
async function figInlineImages(svg){const ids=[...new Set([...svg.matchAll(/href="\/api\/img\/([A-Za-z0-9_-]+)"/g)].map(m=>m[1]))];for(const id of ids){try{const b=await (await fetch('/api/img/'+id)).blob();const d=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b);});svg=svg.split('href="/api/img/'+id+'"').join('href="'+d+'"');}catch(e){}}return svg;}

// バックアップへの同梱: 会話が参照する画像を {id: dataURL} で返す／読み込む
async function figImgsExport(convList){const out={};for(const c of convList)for(const id of Object.keys(c.imgs||{})){if(out[id])continue;try{const u=figImgURL(id);if(!u)continue;if(u.startsWith('data:')){out[id]=u;continue;}const b=await (await fetch(u)).blob();out[id]=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b);});}catch(e){}}return out;}
async function figImgsImport(imgs){let n=0;for(const [id,data] of Object.entries(imgs||{})){if(!/^[A-Za-z0-9_-]{1,64}$/.test(id)||!/^data:image\/(png|jpeg);base64,/.test(data))continue;try{if(typeof IS_DESKTOP!=='undefined'&&IS_DESKTOP){const rr=await fetch('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,data})});if(rr.ok)n++;}else{await figImgPut(id,data);n++;}}catch(e){}}return n;}

/* ---------- 描画 ---------- */
const figImgTxt=(x,y,s,o)=>{o=o||{};const fs=o.size||12;return `<text x="${x}" y="${y}" font-family="${FIG_DEF.font}" font-size="${fs}" font-weight="${o.weight||'bold'}" text-anchor="${o.anchor||'middle'}" fill="${o.fill||'#000'}"${o.stroke?` stroke="${o.stroke}" stroke-width="${fs*0.18}" paint-order="stroke" stroke-linejoin="round"`:''}${o.extra?' '+o.extra:''}>${figEsc(s)}</text>`;};
function figRenderImage(spec){if(spec.type==='blot')return figRenderBlot(spec);return figRenderImgGrid(spec);}
// 注釈。cell: {x,y,w,h}、a: {t:'arrow'|'star'|'text'|'roi', x,y(割合), dir, len, color, text, w,h, shape, dash}
function figImgAnnots(annots,cellOf,fs,idxOf){let s='';(annots||[]).forEach(a=>{const c=cellOf(a.cell||0);if(!c)return;const ai=idxOf?idxOf(a):1;const px=c.x+(+a.x||0)*c.w,py=c.y+(+a.y||0)*c.h;const col=a.color||'#fff';const stroke=col==='#fff'||col==='white'?'#000':'#fff';
  if(a.t==='line'){const x2=c.x+(+a.x2||0)*c.w,y2=c.y+(+a.y2||0)*c.h;s+=`<g data-annot="${ai}"><line x1="${px}" y1="${py}" x2="${x2}" y2="${y2}" stroke="${col}" stroke-width="${FIG_PT*1.2}"/><circle cx="${px}" cy="${py}" r="${FIG_PT*1.5}" fill="${col}"/><circle cx="${x2}" cy="${y2}" r="${FIG_PT*1.5}" fill="${col}"/></g>`;return;}
  if(a.t==='inset'){s+=figImgInset(a,c,fs,ai);return;}
  if(a.t==='arrow'){const len=(+a.len||0.18)*Math.min(c.w,c.h);const dir=((a.dir==null?225:+a.dir)*Math.PI/180);const tx=px+Math.cos(dir)*len,ty=py+Math.sin(dir)*len;const hl=len*0.4,hw=len*0.2;const ang=Math.atan2(py-ty,px-tx);const bx=px-Math.cos(ang)*hl,by=py-Math.sin(ang)*hl;
    s+=`<g data-annot="${ai}"><line x1="${tx}" y1="${ty}" x2="${bx}" y2="${by}" stroke="${col}" stroke-width="${FIG_PT*1.5}" stroke-linecap="round"/><polygon points="${px},${py} ${bx+Math.sin(ang)*hw},${by-Math.cos(ang)*hw} ${bx-Math.sin(ang)*hw},${by+Math.cos(ang)*hw}" fill="${col}" stroke="${stroke}" stroke-width="${FIG_PT*0.3}"/></g>`;}
  else if(a.t==='head'){const len=(+a.len||0.1)*Math.min(c.w,c.h);const dir=((a.dir==null?225:+a.dir)*Math.PI/180);const ang=dir+Math.PI;const bx=px-Math.cos(ang)*len,by=py-Math.sin(ang)*len;s+=`<polygon data-annot="${ai}" points="${px},${py} ${bx+Math.sin(ang)*len*0.45},${by-Math.cos(ang)*len*0.45} ${bx-Math.sin(ang)*len*0.45},${by+Math.cos(ang)*len*0.45}" fill="${col}" stroke="${stroke}" stroke-width="${FIG_PT*0.3}"/>`;}
  else if(a.t==='star')s+=figImgTxt(px,py+fs*0.6,'*',{size:fs*1.8,fill:col,stroke,extra:`data-annot="${ai}"`});
  else if(a.t==='text')s+=figImgTxt(px,py+fs*0.35,a.text||'',{size:fs*(+a.size||1),fill:col,stroke,anchor:a.anchor||'middle',extra:`data-annot="${ai}"`});
  else if(a.t==='roi'){const w=(+a.w||0.25)*c.w,h=(+a.h||0.25)*c.h;const dash=a.dash===false?'':` stroke-dasharray="${FIG_PT*3} ${FIG_PT*2}"`;s+=a.shape==='circle'?`<ellipse data-annot="${ai}" cx="${px}" cy="${py}" rx="${w/2}" ry="${h/2}" fill="none" stroke="${col}" stroke-width="${FIG_PT}"${dash}/>`:`<rect data-annot="${ai}" x="${px-w/2}" y="${py-h/2}" width="${w}" height="${h}" fill="none" stroke="${col}" stroke-width="${FIG_PT}"${dash}/>`;}});return s;}
// スケールバー。sb: {umPerPx,len,unit,pos:'br'|'bl'|'tr'|'tl',color,thick,labelOn:'first'|'all'|'none'}
function figScaleBar(sb,c,imgW,k,fs){if(!sb||!(+sb.len>0)||!(+sb.umPerPx>0)||!imgW)return '';const s=c.scalePx!=null?c.scalePx:c.w/imgW*(c.sliceScale||1);const len=+sb.len/+sb.umPerPx*s;if(!(len>0)||len>c.w*0.9)return '';const th=(+sb.thick||2)*FIG_PT;const col=sb.color==='black'?'#000':'#fff';const pad=fs*0.6;const pos=sb.pos||'br';
  const x=/l/.test(pos)?c.x+pad:c.x+c.w-pad-len;const y=/t/.test(pos)?c.y+pad+(sb.labelOn!=='none'?fs*1.1:0):c.y+c.h-pad-th;let out=`<rect x="${x}" y="${y}" width="${len}" height="${th}" fill="${col}" data-scalebar="1"/>`;
  const on=sb.labelOn||'first';if(on==='all'||(on==='first'&&k===0))out+=figImgTxt(/l/.test(pos)?x:x+len,/t/.test(pos)?y-fs*0.3:y-fs*0.35,`${figFmt(+sb.len)} ${sb.unit||'µm'}`,{size:fs*0.9,fill:col,stroke:col==='#fff'?'#000':'#fff',anchor:/l/.test(pos)?'start':'end'});return out;}
// 画像セルの表示: 疑似カラー（channel）・表示範囲（range 0–1）・ガンマ・LUT・合成（merge: screen）・切り抜き（crop 割合）・回転・反転
const FIG_CH_COLORS={gray:[1,1,1],white:[1,1,1],red:[1,0,0],green:[0,1,0],blue:[0,0,1],cyan:[0,1,1],magenta:[1,0,1],yellow:[1,1,0]};
const FIG_LUTS={fire:['#000000','#3A0088','#B00070','#FF3000','#FFA000','#FFFF40','#FFFFFF'],viridis:['#440154','#3B528B','#21918C','#5EC962','#FDE725'],inferno:['#000004','#420A68','#932667','#DD513A','#FCA50A','#FCFFA4'],jet:['#00007F','#0000FF','#00FFFF','#7FFF00','#FFFF00','#FF0000','#7F0000'],grays:['#000000','#FFFFFF']};
function figImgFilter(L,id){const rng=Array.isArray(L.range)&&L.range.length===2?[+L.range[0],+L.range[1]]:null;const gm=+L.gamma>0?+L.gamma:1;const ch=L.channel&&FIG_CH_COLORS[String(L.channel).toLowerCase()];const lut=L.lut&&FIG_LUTS[String(L.lut).toLowerCase()];const hex=L.channel&&!ch&&/^#[0-9a-f]{6}$/i.test(L.channel)?[1,3,5].map(k=>parseInt(L.channel.slice(k,k+2),16)/255):null;const tint=ch||hex;
  if(!rng&&gm===1&&!tint&&!lut)return '';let f='';
  if(rng&&rng[1]>rng[0]){const sl=1/(rng[1]-rng[0]),ic=-rng[0]*sl;f+=`<feComponentTransfer>${['R','G','B'].map(k=>`<feFunc${k} type="linear" slope="${sl}" intercept="${ic}"/>`).join('')}</feComponentTransfer>`;}
  if(gm!==1)f+=`<feComponentTransfer>${['R','G','B'].map(k=>`<feFunc${k} type="gamma" amplitude="1" exponent="${1/gm}" offset="0"/>`).join('')}</feComponentTransfer>`;
  if(tint||lut){f+=`<feColorMatrix type="matrix" values="0.299 0.587 0.114 0 0  0.299 0.587 0.114 0 0  0.299 0.587 0.114 0 0  0 0 0 1 0"/>`; // 輝度にそろえる
    if(lut){const N=24;const tab=k=>Array.from({length:N},(_,i)=>{const c=figGrad(lut,i/(N-1));return (parseInt(c.slice(k,k+2),16)/255).toFixed(3);}).join(' ');f+=`<feComponentTransfer><feFuncR type="table" tableValues="${tab(1)}"/><feFuncG type="table" tableValues="${tab(3)}"/><feFuncB type="table" tableValues="${tab(5)}"/></feComponentTransfer>`;}
    else f+=`<feColorMatrix type="matrix" values="${tint[0]} 0 0 0 0  0 ${tint[1]} 0 0 0  0 0 ${tint[2]} 0 0  0 0 0 1 0"/>`;}
  return `<filter id="${id}" color-interpolation-filters="sRGB">${f}</filter>`;}
// 画像指定の実効範囲（回転・切り抜き後の viewBox、画像 px）。セルの縦横比はこれから決める
function figImgViewBox(im){const L=(Array.isArray(im.merge)&&im.merge.length?im.merge[0]:im);const meta=L&&L.img?figImgMeta(L.img):null;if(!meta)return null;const iw=meta.w,ih=meta.h;const rot=((+im.rot||0)%360+360)%360;const swap=rot===90||rot===270;const bw=swap?ih:iw,bh=swap?iw:ih;let vb={x:(iw-bw)/2,y:(ih-bh)/2,w:bw,h:bh};
  if(Array.isArray(im.crop)&&im.crop.length===4){const [cx,cy,cw,ch]=im.crop.map(Number);vb={x:vb.x+cx*vb.w,y:vb.y+cy*vb.h,w:Math.max(1,cw*vb.w),h:Math.max(1,ch*vb.h)};}return vb;}
// セルの画像（入れ子 svg の viewBox で切り抜きと slice）。戻り値 {svg, view:{x,y,w,h}（画像 px で表示している範囲）, scalePx（画像 px → セル px）, layers}
function figImgCellSVG(im,x,y,w,h,k){const layers=(Array.isArray(im.merge)&&im.merge.length?im.merge:[im]).filter(L=>L&&L.img);if(!layers.length)return null;const meta=figImgMeta(layers[0].img);const iw=meta?meta.w:1000,ih=meta?meta.h:Math.round(1000*h/w);
  const rot=((+im.rot||0)%360+360)%360;const swap=rot===90||rot===270;const bw=swap?ih:iw,bh=swap?iw:ih;let vb={x:(iw-bw)/2,y:(ih-bh)/2,w:bw,h:bh};
  if(Array.isArray(im.crop)&&im.crop.length===4){const [cx,cy,cw,ch]=im.crop.map(Number);vb={x:vb.x+cx*vb.w,y:vb.y+cy*vb.h,w:Math.max(1,cw*vb.w),h:Math.max(1,ch*vb.h)};}
  let tr='';if(rot)tr+=`rotate(${rot} ${iw/2} ${ih/2}) `;if(im.flip==='h'||im.flip==='both')tr+=`translate(${iw} 0) scale(-1 1) `;if(im.flip==='v'||im.flip==='both')tr+=`translate(0 ${ih}) scale(1 -1) `;
  let defs='',inner='';layers.forEach((L,li)=>{const fid=`imf${k}_${li}_${Math.random().toString(36).slice(2,6)}`;const f=figImgFilter(L,fid);if(f)defs+=f;inner+=`<image href="${figImgURL(L.img)}" x="0" y="0" width="${iw}" height="${ih}" preserveAspectRatio="none"${tr?` transform="${tr.trim()}"`:''}${f?` filter="url(#${fid})"`:''}${li?' style="mix-blend-mode:screen"':''}/>`;});
  const contain=(im.fit||figImgCellSVG.fit)==='contain';const sc=contain?Math.min(w/vb.w,h/vb.h):Math.max(w/vb.w,h/vb.h);const view={x:vb.x+(vb.w-w/sc)/2,y:vb.y+(vb.h-h/sc)/2,w:w/sc,h:h/sc};const bg=im.bg||figImgCellSVG.bg||'#000';const mk=(X,Y,W,H,V)=>`<svg x="${X}" y="${Y}" width="${W}" height="${H}" viewBox="${V.x} ${V.y} ${V.w} ${V.h}" preserveAspectRatio="xMidYMid ${contain?'meet':'slice'}">${defs}<rect x="${V.x-1e6}" y="${V.y-1e6}" width="2e6" height="2e6" fill="${bg}"/>${inner}</svg>`;
  return {svg:mk(x,y,w,h,vb),view,scalePx:sc,mk,layers,meta};}
// 拡大挿入図: ROI（割合 x,y,w,h）を四隅のどこか（at）に size（セル幅に対する割合）で拡大表示し、引き出し線でつなぐ
function figImgInset(a,c,fs,ai){const w=(+a.w||0.25)*c.w,h=(+a.h||0.25)*c.h;const px=c.x+(+a.x||0.5)*c.w,py=c.y+(+a.y||0.5)*c.h;const col=a.color||'#fff';let s=`<rect x="${px-w/2}" y="${py-h/2}" width="${w}" height="${h}" fill="none" stroke="${col}" stroke-width="${FIG_PT}"/>`;
  if(!c.cellSVG)return `<g data-annot="${ai}">${s}</g>`;const v=c.view;const roi={x:v.x+((+a.x||0.5)-(+a.w||0.25)/2)*v.w,y:v.y+((+a.y||0.5)-(+a.h||0.25)/2)*v.h,w:(+a.w||0.25)*v.w,h:(+a.h||0.25)*v.h};const size=(+a.size||0.42)*c.w;const iw=size,ih=size*(roi.h/roi.w);const at=a.at||'br';const pad=fs*0.3;
  const ix=/l/.test(at)?c.x+pad:c.x+c.w-pad-iw,iy=/t/.test(at)?c.y+pad:c.y+c.h-pad-ih;s+=c.cellSVG.mk(ix,iy,iw,ih,roi)+`<rect x="${ix}" y="${iy}" width="${iw}" height="${ih}" fill="none" stroke="${col}" stroke-width="${FIG_PT*1.2}"/>`;
  const rx=/l/.test(at)?px+w/2:px-w/2,ry=/t/.test(at)?py+h/2:py-h/2;const tx=/l/.test(at)?ix+iw:ix,ty=/t/.test(at)?iy+ih:iy;s+=`<line x1="${rx}" y1="${ry}" x2="${tx}" y2="${ty}" stroke="${col}" stroke-width="${FIG_PT*0.6}"/>`;return `<g data-annot="${ai}">${s}</g>`;}
function figRenderImgGrid(spec){const imgs=(spec.images||[]).filter(Boolean);const n=imgs.length;if(!n)return null;const cols=Math.max(1,Math.min(8,+spec.cols||Math.min(n,FIG_IMG_DEF.cols)));const rows=Math.ceil(n/cols);
  const fs=(+spec.fontPt||FIG_IMG_DEF.fontPt)*FIG_PT;const cellW=(+spec.cellIn||FIG_IMG_DEF.cellIn)*FIG_IN;const vb0=figImgViewBox(imgs[0]);const asp=+spec.aspect>0?+spec.aspect:(vb0?vb0.h/vb0.w:1);const cellH=cellW*asp;const gap=(spec.gap==null?FIG_IMG_DEF.gap:+spec.gap)*FIG_PT;
  const rl=spec.rowLabels||[],cl=spec.colLabels||[];const rowLabW=rl.length?(spec.rowVert?fs*1.5:Math.max(...rl.map(s=>String(s).length))*fs*0.6+fs*0.6):0;const colLabH=cl.length?fs*1.5:0;const titleH=spec.title?fs*2:0;
  const x0=rowLabW,y0=titleH+colLabH;const W=x0+cols*cellW+(cols-1)*gap,H=y0+rows*cellH+(rows-1)*gap;const cells=[];
  figImgCellSVG.fit=spec.fit||'cover';figImgCellSVG.bg=spec.bg||'#000';
  let body='',labels='';imgs.forEach((im,k)=>{const r=Math.floor(k/cols),c=k%cols;const x=x0+c*(cellW+gap),y=y0+r*(cellH+gap);const meta=figImgMeta(im.img);const cell={x,y,w:cellW,h:cellH,sliceScale:meta?Math.max(cellW/meta.w,cellH/meta.h)/(cellW/meta.w):1};cells.push(cell);
    const cs=figImgCellSVG(im,x,y,cellW,cellH,k);if(cs){cell.view=cs.view;cell.scalePx=cs.scalePx;cell.cellSVG=cs;}body+=`<g data-cell="${k}"><rect x="${x}" y="${y}" width="${cellW}" height="${cellH}" fill="${cs?'#000':'#e5e5e5'}"/>${cs?cs.svg:figImgTxt(x+cellW/2,y+cellH/2,'画像なし',{size:fs,fill:'#888',weight:'normal'})}`;
    if(im.label){const lw=figSchTW(im.label,fs);const lfs=lw>cellW*0.9?fs*cellW*0.9/lw:fs;const lc=im.labelColor||'#fff';body+=figImgTxt(x+fs*0.5,y+fs*0.3+lfs*0.9,im.label,{size:lfs,fill:lc,stroke:figDark(lc)?'#fff':'#000',anchor:'start'});}
    if(spec.scale&&im.scaleBar!==false)body+=figScaleBar(spec.scale,cell,meta?meta.w:0,k,fs);
    body+=`<rect data-cellbox="${k}" x="${x}" y="${y}" width="${cellW}" height="${cellH}" fill="none" pointer-events="all"/>`+figImgAnnots((spec.annots||[]).filter(a=>(a.cell||0)===k),()=>cell,fs,a=>(spec.annots||[]).indexOf(a))+`</g>`;});
  cl.forEach((s,c)=>{if(c>=cols)return;labels+=figImgTxt(x0+c*(cellW+gap)+cellW/2,titleH+fs*1.05,s,{size:fs,fill:(spec.colColors||[])[c]||'#000'});});
  rl.forEach((s,r)=>{if(r>=rows)return;const cy=y0+r*(cellH+gap)+cellH/2;labels+=spec.rowVert?figImgTxt(fs*1.0,cy,s,{size:fs,extra:`transform="rotate(-90 ${fs*1.0} ${cy})"`}):figImgTxt(rowLabW-fs*0.5,cy+fs*0.35,s,{size:fs,anchor:'end'});});
  let bar='',W2=W;const lutIm=imgs.find(im=>im.lut&&FIG_LUTS[String(im.lut).toLowerCase()]);if(lutIm){const lut=FIG_LUTS[String(lutIm.lut).toLowerCase()];const gid='lutg'+Math.random().toString(36).slice(2,6);const bx=W+fs*0.8,bh=Math.min(rows*cellH,cellH*1.6);bar=`<defs><linearGradient id="${gid}" x1="0" y1="1" x2="0" y2="0">${lut.map((c,k)=>`<stop offset="${k/(lut.length-1)*100}%" stop-color="${c}"/>`).join('')}</linearGradient></defs><rect x="${bx}" y="${y0}" width="${fs*0.8}" height="${bh}" fill="url(#${gid})" stroke="#000" stroke-width="${FIG_PT*0.5}"/>`;const rng=Array.isArray(lutIm.range)?lutIm.range:[0,1];const unit=lutIm.unit||'';bar+=figImgTxt(bx+fs*1.1,y0+fs*0.5,`${figFmt(+rng[1])}${unit?' '+unit:''}`,{size:fs*0.8,anchor:'start',weight:'normal'})+figImgTxt(bx+fs*1.1,y0+bh,`${figFmt(+rng[0])}`,{size:fs*0.8,anchor:'start',weight:'normal'});if(lutIm.lutLabel)bar+=figImgTxt(bx,y0-fs*0.4,lutIm.lutLabel,{size:fs*0.8,anchor:'start'});W2=bx+fs*5;}
  const title=spec.title?figImgTxt(x0+(W-x0)/2,fs*1.3,spec.title,{size:fs*1.2}):'';
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W2}" height="${H}" viewBox="0 0 ${W2} ${H}"><rect width="100%" height="100%" fill="#fff"/>${title}<g data-sel="axes">${labels}</g>${body}${bar}</svg>`;
  return {svg,w:W2,h:H,plot:{x0,y0,w:W-x0,h:H-y0},image:true,cells,n,cols,rows,adjust:imgs.flatMap((im,k)=>(Array.isArray(im.merge)?im.merge:[im]).filter(L=>L&&(L.range||L.gamma||L.channel||L.lut)).map(L=>({cell:k,img:L.img,channel:L.channel,range:L.range,gamma:L.gamma,lut:L.lut})))};}
// ブロット: bands=[{img,name,kda}]（上から順の短冊）、lanes=['1','2',…]、conds=[{name,vals:['−','+',…],wedge:true}]、groups=[{name,from,to}]（0 始まりのレーン）
function figRenderBlot(spec){figImgCellSVG.fit='cover';figImgCellSVG.bg='#fff';const bands=(spec.bands||[]).filter(Boolean);if(!bands.length)return null;const fs=(+spec.fontPt||FIG_IMG_DEF.fontPt)*FIG_PT;const W0=(+spec.widthIn||FIG_IMG_DEF.widthIn)*FIG_IN;const gap=(spec.gap==null?4:+spec.gap)*FIG_PT;
  const conds=spec.conds||[],lanes=spec.lanes||[],groups=spec.groups||[];const nl=Math.max(lanes.length,...conds.map(c=>(c.vals||[]).length),1);const laneW=W0/nl;
  const condNameW=conds.length?Math.max(...conds.map(c=>String(c.name||'').length))*fs*0.6+fs*0.6:0;const kdaW=bands.some(b=>b.kda!=null&&b.kda!=='')?fs*3.2:0;const nameW=bands.some(b=>b.name)?Math.max(...bands.map(b=>figTW(b.name||'',fs)))+fs*1.2:0;const leftSide=spec.nameSide==='left';const leftW=Math.max(condNameW,kdaW+(leftSide?nameW:0));const rightW=leftSide?fs*0.3:nameW+fs*0.4;
  const titleH=spec.title?fs*2:0;const groupH=groups.length?fs*1.6:0;const condH=conds.length*fs*1.3;const laneH=lanes.length?(spec.laneRot?fs*2.6:fs*1.3):0;const x0=leftW,y0=titleH+groupH+condH+laneH+fs*0.3;
  let body='',labels='',y=y0;const cells=[];const left=spec.nameSide==='left';bands.forEach((b,k)=>{const vb=figImgViewBox(b);const h=+b.heightIn>0?+b.heightIn*FIG_IN:(vb?Math.min(W0*0.6,W0*vb.h/vb.w):W0*0.16);const cs=figImgCellSVG(b,x0,y,W0,h,k);const cell={x:x0,y,w:W0,h,sliceScale:1};if(cs){cell.view=cs.view;cell.scalePx=cs.scalePx;cell.cellSVG=cs;}cells.push(cell);
    body+=`<g data-cell="${k}"><rect x="${x0}" y="${y}" width="${W0}" height="${h}" fill="${cs?'#fff':'#eee'}" stroke="${b.frame===false?'none':'#000'}" stroke-width="${FIG_PT*0.5}"/>${cs?cs.svg:figImgTxt(x0+W0/2,y+h/2+fs*0.35,'画像なし',{size:fs,fill:'#888',weight:'normal'})}`;
    if(b.kda!=null&&b.kda!=='')labels+=`<line x1="${x0-fs*0.5}" y1="${y+h/2}" x2="${x0-fs*0.1}" y2="${y+h/2}" stroke="#000" stroke-width="${FIG_PT*0.75}"/>`+figImgTxt(x0-fs*0.6,y+h/2+fs*0.35,`${b.kda}${/kda|kd/i.test(String(b.kda))?'':' kDa'}`,{size:fs*0.9,anchor:'end',weight:'normal'});
    if(b.name)labels+=leftSide?figImgTxt(x0-kdaW-fs*0.5,y+h/2+fs*0.35,b.name,{size:fs,anchor:'end'}):figImgTxt(x0+W0+fs*0.5,y+h/2+fs*0.35,b.name,{size:fs,anchor:'start'});
    body+=`<rect data-cellbox="${k}" x="${x0}" y="${y}" width="${W0}" height="${h}" fill="none" pointer-events="all"/>`+figImgAnnots((spec.annots||[]).filter(a=>(a.cell||0)===k),()=>cell,fs,a=>(spec.annots||[]).indexOf(a))+`</g>`;y+=h+gap;});
  const H=y-gap+fs*0.5;let ty=titleH;const lx=i=>x0+(i+0.5)*laneW;
  groups.forEach(g=>{const a=Math.max(0,+g.from||0),bb=Math.min(nl-1,g.to==null?nl-1:+g.to);const xa=x0+a*laneW+fs*0.2,xb=x0+(bb+1)*laneW-fs*0.2;labels+=`<line x1="${xa}" y1="${ty+fs*1.4}" x2="${xb}" y2="${ty+fs*1.4}" stroke="#000" stroke-width="${FIG_PT*0.75}"/>`+figImgTxt((xa+xb)/2,ty+fs*1.05,g.name||'',{size:fs});});ty+=groupH;
  conds.forEach(c=>{labels+=figImgTxt(x0-fs*0.5,ty+fs*1.0,c.name||'',{size:fs,anchor:'end'});if(c.wedge){labels+=`<polygon points="${x0+fs*0.2},${ty+fs*1.05} ${x0+W0-fs*0.2},${ty+fs*1.05} ${x0+W0-fs*0.2},${ty+fs*0.25}" fill="#000"/>`;}else (c.vals||[]).forEach((v,i)=>{labels+=figImgTxt(lx(i),ty+fs*1.0,v,{size:fs,weight:'normal'});});ty+=fs*1.3;});
  lanes.forEach((l,i)=>{if(i>=nl)return;labels+=spec.laneRot?figImgTxt(lx(i)+fs*0.3,ty+fs*2.2,l,{size:fs,anchor:'start',extra:`transform="rotate(-45 ${lx(i)+fs*0.3} ${ty+fs*2.2})"`,weight:'normal'}):figImgTxt(lx(i),ty+fs*1.0,l,{size:fs,weight:'normal'});});
  const title=spec.title?figImgTxt(x0+W0/2,fs*1.3,spec.title,{size:fs*1.2}):'';const W=x0+W0+rightW;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/>${title}<g data-sel="axes">${labels}</g>${body}</svg>`;
  return {svg,w:W,h:H,plot:{x0,y0,w:W0,h:H-y0},image:true,cells,n:bands.length,blot:true};}

/* ---------- チャットのブロック ---------- */
function figImageBlockHTML(j,r,nodeId,index){const sel=(key,opts,cur)=>`<select class="small" data-figimg="${key}" data-tip="画像パネルの設定（回答に書き戻します）">${opts.map(([v,l])=>`<option value="${v}"${String(cur)===String(v)?' selected':''}>${l}</option>`).join('')}</select>`;const sb=j.scale||{};
  const tools=`<span class="ui" style="margin-left:6px">注釈</span>${[['arrow','矢印'],['head','矢頭'],['star','＊'],['text','文字'],['roi','ROI 枠'],['inset','拡大図'],['line','プロファイル']].map(([t,l])=>`<button class="small" data-figtool="${t}" data-tip="押してから画像の場所をクリック">${l}</button>`).join('')}<button class="small" data-figimg="undo" data-tip="最後の注釈を消す">⌫</button>`;
  const grid=!r.blot;const ctl=grid?`<span class="ui" style="margin-left:6px">列</span>${sel('cols',[1,2,3,4,5,6].map(v=>[v,v]),r.cols)}<span class="ui">セル幅</span>${sel('cellIn',[[0.8,'0.8 in'],[1,'1.0 in'],[1.2,'1.2 in'],[1.5,'1.5 in'],[2,'2.0 in']],j.cellIn||FIG_IMG_DEF.cellIn)}<span class="ui">収め方</span>${sel('fit',[['cover','枠いっぱい（はみ出しは切る）'],['contain','全体を収める（余白）']],j.fit||'cover')}<span class="ui">縦横比</span>${sel('aspect',[['','1 枚目に合わせる'],['1','1:1'],['0.75','4:3'],['0.6667','3:2'],['0.5625','16:9']],j.aspect||'')}<span class="ui">スケールバー</span><input class="small" data-figimg="umPerPx" type="number" step="any" min="0" placeholder="µm/px" value="${sb.umPerPx||''}" style="width:64px" data-tip="1 画素あたりの長さ（µm/px）"><input class="small" data-figimg="len" type="number" step="any" min="0" placeholder="長さ" value="${sb.len||''}" style="width:52px" data-tip="バーの長さ">${sel('unit',[['µm','µm'],['nm','nm'],['mm','mm']],sb.unit||'µm')}${sel('labelOn',[['first','表示: 1 枚目'],['all','表示: 全部'],['none','表示: なし']],sb.labelOn||'first')}${sel('color',[['white','白'],['black','黒']],sb.color||'white')}${sel('pos',[['br','右下'],['bl','左下'],['tr','右上'],['tl','左上']],sb.pos||'br')}`:`<span class="ui" style="margin-left:6px">幅</span>${sel('widthIn',[[2,'2.0 in'],[2.5,'2.5 in'],[3,'3.0 in'],[4,'4.0 in']],j.widthIn||FIG_IMG_DEF.widthIn)}<span class="ui">レーン名</span>${sel('laneRot',[['0','横'],['1','45°']],j.laneRot?1:0)}<span class="ui">抗体名</span>${sel('nameSide',[['right','右'],['left','左']],j.nameSide||'right')}`;
  return `<div class="figblock image" data-fignode="${figEsc(nodeId||'')}" data-figidx="${index}">${r.svg}<div class="figbtns"><button class="small" data-figedit data-tip="この画像パネルを作成画面で編集する">✎ 編集</button><button class="small" data-figjson data-tip="指定（JSON）を直して回答に書き戻す">{}</button><button class="small" data-figpng data-tip="PNG（300 dpi）で保存">PNG</button><button class="small" data-figsvg data-tip="SVG で保存">SVG</button><button class="small" data-figcopy data-tip="画像をコピー">⧉</button>${ctl}${tools}</div></div>`;}
function figImageSet(fb,key,val){const nid=fb.dataset.fignode,idx=+fb.dataset.figidx;const n=N(nid);if(!n)return;const b=figFindBlocks(n.content)[idx];if(!b)return;let j;try{j=JSON.parse(b.json);}catch(e){return;}if(!figIsImage(j))return;
  if(key==='undo'){if(j.annots&&j.annots.length)j.annots.pop();else{toast('消す注釈がありません');return;}}
  else if(['umPerPx','len','unit','labelOn','color','pos'].includes(key)){j.scale=j.scale||{};if(key==='umPerPx'||key==='len')j.scale[key]=+val||0;else j.scale[key]=val;}
  else if(key==='cols')j.cols=+val;else if(key==='cellIn'||key==='widthIn')j[key]=+val;else if(key==='aspect'){if(+val>0)j.aspect=+val;else delete j.aspect;}else if(key==='laneRot')j.laneRot=val==='1';else j[key]=val;
  n.content=n.content.slice(0,b.start)+'```figure\n'+JSON.stringify(j)+'\n```'+n.content.slice(b.end);persist();renderAll();}
let figImgTool=null; // 選択中の注釈ツール {fb,t}
function figImageToolClick(fb,t){if(figImgTool&&figImgTool.t===t&&figImgTool.fb===fb){figImgTool=null;fb.querySelectorAll('[data-figtool]').forEach(b=>b.classList.remove('on'));return;}figImgTool={fb,t,pts:[]};fb.querySelectorAll('[data-figtool]').forEach(b=>b.classList.toggle('on',b.dataset.figtool===t));toast(t==='line'?'画像の中で、線の始点と終点を順にクリックしてください（輝度プロファイルを下に作ります）':t==='inset'?'拡大したい場所をクリックしてください（ROI の中心）':'画像の中で、注釈を置く場所をクリックしてください');}
// 画像のセルをクリック → 割合座標で注釈を足して書き戻す
function figImageCellClick(fb,cellEl,ev){if(!figImgTool||figImgTool.fb!==fb)return false;const t=figImgTool.t;const box=cellEl.getBoundingClientRect();const x=+((ev.clientX-box.left)/box.width).toFixed(3),y=+((ev.clientY-box.top)/box.height).toFixed(3);const k=+cellEl.dataset.cellbox;
  if(t==='line'){figImgTool.pts.push({k,x,y});if(figImgTool.pts.length<2||figImgTool.pts[0].k!==k){if(figImgTool.pts[0].k!==k){figImgTool.pts=[{k,x,y}];toast('同じ画像の中で終点をクリックしてください');}return true;}const [p1,p2]=figImgTool.pts;figImgTool=null;figImageProfile(fb,k,p1,p2);return true;}
  const a={t,cell:k,x,y};if(t==='roi'){a.w=0.25;a.h=0.25;}if(t==='inset'){a.w=0.25;a.h=0.25;a.size=0.42;a.at=(y<0.5?'b':'t')+(x<0.5?'r':'l');}figImgTool=null;
  const push=()=>{const nid=fb.dataset.fignode,idx=+fb.dataset.figidx;const n=N(nid);if(!n)return;const b=figFindBlocks(n.content)[idx];if(!b)return;let j;try{j=JSON.parse(b.json);}catch(e){return;}(j.annots=j.annots||[]).push(a);n.content=n.content.slice(0,b.start)+'```figure\n'+JSON.stringify(j)+'\n```'+n.content.slice(b.end);persist();renderAll();};
  if(t==='text'){figPrompt('書く文字','').then(s=>{if(!s)return;a.text=s;push();});return true;}push();return true;}
// 注釈のドラッグ終了: 割合座標を動かして書き戻す
function figImgDragEnd(fb,ai,dx,dy){const nid=fb.dataset.fignode,idx=+fb.dataset.figidx;const n=N(nid);if(!n)return;const b=figFindBlocks(n.content)[idx];if(!b)return;let j;try{j=JSON.parse(b.json);}catch(e){return;}if(!figIsImage(j))return;const a=(j.annots||[])[ai];if(!a)return;
  const r=figRenderSpec(j);const c=r&&r.cells&&r.cells[a.cell||0];if(!c)return;const fx=dx/c.w,fy=dy/c.h;const cl=v=>+Math.max(0,Math.min(1,v)).toFixed(3);a.x=cl((+a.x||0)+fx);a.y=cl((+a.y||0)+fy);if(a.t==='line'){a.x2=cl((+a.x2||0)+fx);a.y2=cl((+a.y2||0)+fy);}
  n.content=n.content.slice(0,b.start)+'```figure\n'+JSON.stringify(j)+'\n```'+n.content.slice(b.end);persist();renderAll();}
// ＋メニュー「画像パネルを作る」: 画像を保存し、入力欄に ```figure を入れる（AI に見せるため縮小版も添付）
async function figImportImages(files){const list=[...files].filter(f=>/^image\/(png|jpeg|jpg|webp|gif|bmp|tiff?)$/i.test(f.type)||/\.tiff?$/i.test(f.name)).slice(0,12);if(!list.length){toast('画像ファイルを選んでください');return;}const imgs=[];for(const f of list){try{imgs.push(...await figImgStoreAny(f));}catch(e){toast(f.name+': '+e.message);}}if(!imgs.length)return;
  const spec={kind:'image',type:'grid',cols:Math.min(imgs.length,3),images:imgs.map(m=>({img:m.id,label:m.name})),scale:{umPerPx:0,len:20,unit:'µm',labelOn:'first'}};persist();
  const t=document.querySelector('#input');t.value=(t.value?t.value+'\n':'')+'```figure\n'+JSON.stringify(spec)+'\n```\n';if(typeof fitInput==='function')fitInput();t.focus();
  if(typeof addImages==='function'&&typeof pendingImgs!=='undefined'&&pendingImgs.length<4){try{await addImages(list.slice(0,4-pendingImgs.length));}catch(e){}}
  toast(`画像 ${imgs.length} 枚を保存し、画像パネルの指定を入力欄に入れました。並べ方やスケールバー（µm/px）の指示を添えて送信するか、そのまま送って下のツールで整えてください`);}

// 輝度プロファイル: 画像の 2 点間を 200 点でサンプリング（最近傍）し、線の注釈と xy の ```figure を回答に足す
async function figImageProfile(fb,k,p1,p2){const nid=fb.dataset.fignode,idx=+fb.dataset.figidx;const n=N(nid);if(!n)return;const b=figFindBlocks(n.content)[idx];if(!b)return;let j;try{j=JSON.parse(b.json);}catch(e){return;}if(!figIsImage(j))return;
  const r=figRenderSpec(j);const cell=r&&r.cells&&r.cells[k];if(!cell||!cell.view||!cell.cellSVG){toast('この画像ではプロファイルを取れません');return;}const L=cell.cellSVG.layers[0];const meta=cell.cellSVG.meta;const col=['#FFD500','#00E5FF','#FF4DD2','#7CFF4D'][((j.annots||[]).filter(a=>a.t==='line').length)%4];
  try{const im=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('画像を読めませんでした'));i.src=figImgURL(L.img);});const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);
    const v=cell.view;const X=p=>v.x+p.x*v.w,Y=p=>v.y+p.y*v.h;const x1=X(p1),y1=Y(p1),x2=X(p2),y2=Y(p2);const Lpx=Math.hypot(x2-x1,y2-y1);const N=200;const um=j.scale&&+j.scale.umPerPx>0?+j.scale.umPerPx:0;const rows=[];
    for(let i=0;i<=N;i++){const t=i/N;const px=Math.max(0,Math.min(im.width-1,Math.round(x1+(x2-x1)*t))),py=Math.max(0,Math.min(im.height-1,Math.round(y1+(y2-y1)*t)));const d=g.getImageData(px,py,1,1).data;const lum=0.299*d[0]+0.587*d[1]+0.114*d[2];rows.push([um?(Lpx*t*um).toFixed(2):Math.round(Lpx*t),lum.toFixed(1)]);}
    (j.annots=j.annots||[]).push({t:'line',cell:k,x:p1.x,y:p1.y,x2:p2.x,y2:p2.y,color:col});const name=(j.images&&j.images[k]&&j.images[k].label)||meta&&meta.name||'画像';
    const prof={title:`${name} の輝度プロファイル`,kind:'xy',type:'xy-line',xtitle:um?'Distance (µm)':'Distance (px)',ytitle:'Intensity (a.u.)',data:['Distance\tIntensity'].concat(rows.map(r=>r.join('\t'))).join('\n'),style:{series:[{color:col,symPt:0.1}],wIn:2.5,hIn:1.5}};
    n.content=n.content.slice(0,b.start)+'```figure\n'+JSON.stringify(j)+'\n```\n\n```figure\n'+JSON.stringify(prof)+'\n```'+n.content.slice(b.end);persist();renderAll();toast('線の注釈と輝度プロファイルの図を足しました');}
  catch(e){toast(e.message||'プロファイルを取れませんでした');}}

// TIFF の読み込み（非圧縮・LZW・PackBits、8/16 bit・float、グレー/RGB、複数ページ）。16 bit は 0.05–99.95 パーセンタイルで 8 bit に写像し、範囲を meta に残す
function figTiffDecode(buf){const dv=new DataView(buf);const le=dv.getUint16(0)===0x4949;const u16=o=>dv.getUint16(o,le),u32=o=>dv.getUint32(o,le);if(u16(2)!==42)throw new Error('TIFF ではありません');const pages=[];let ifd=u32(4);let guard=0;
  while(ifd&&guard++<64){const n=u16(ifd);const tags={};for(let i=0;i<n;i++){const o=ifd+2+i*12;const tag=u16(o),type=u16(o+2),cnt=u32(o+4);const sz={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8}[type]||1;const off=cnt*sz<=4?o+8:u32(o+8);const vals=[];for(let k=0;k<Math.min(cnt,1<<20);k++){vals.push(type===3?u16(off+k*2):type===4?u32(off+k*4):type===1||type===7?dv.getUint8(off+k):type===11?dv.getFloat32(off+k*4,le):type===12?dv.getFloat64(off+k*8,le):u32(off+k*4));}tags[tag]=vals;}
    pages.push(tags);ifd=u32(ifd+2+n*12);}
  const out=[];for(const t of pages){const W=t[256]&&t[256][0],H=t[257]&&t[257][0];if(!W||!H)continue;const bps=(t[258]||[8])[0],spp=(t[277]||[1])[0],comp=(t[259]||[1])[0],photo=(t[262]||[1])[0],fmt=(t[339]||[1])[0],pred=(t[317]||[1])[0];if(t[324])throw new Error('タイル形式の TIFF には未対応です');if(![1,5,32773].includes(comp))throw new Error('この圧縮（'+comp+'）の TIFF には未対応です');
    const offs=t[273]||[],cnts=t[279]||[];const rps=(t[278]||[H])[0];const bytesPerSample=bps/8;const rowBytes=W*spp*bytesPerSample;const total=new Uint8Array(H*rowBytes);let pos=0;
    for(let s=0;s<offs.length;s++){let chunk=new Uint8Array(buf,offs[s],cnts[s]);if(comp===5)chunk=figLZW(chunk);else if(comp===32773)chunk=figPackBits(chunk);const need=Math.min(chunk.length,total.length-pos);total.set(chunk.subarray(0,need),pos);pos+=need;}
    if(pred===2){for(let y=0;y<H;y++){const base=y*rowBytes;if(bps===8){for(let x=spp;x<rowBytes;x++)total[base+x]=(total[base+x]+total[base+x-spp])&255;}else if(bps===16){const v=new DataView(total.buffer);for(let x=spp;x<W*spp;x++){const o=base+x*2,p=base+(x-spp)*2;const val=(le?v.getUint16(o,true):v.getUint16(o,false))+(le?v.getUint16(p,true):v.getUint16(p,false));if(le)v.setUint16(o,val&65535,true);else v.setUint16(o,val&65535,false);}}}}
    const npx=W*H;const lum=new Float32Array(npx*spp);const v=new DataView(total.buffer);for(let i=0;i<npx*spp;i++){lum[i]=bps===8?total[i]:bps===16?(fmt===2?v.getInt16(i*2,le):v.getUint16(i*2,le)):bps===32?(fmt===3?v.getFloat32(i*4,le):v.getUint32(i*4,le)):total[i];}
    let lo=0,hi=255;if(bps!==8){const sample=[];const step=Math.max(1,Math.floor(lum.length/200000));for(let i=0;i<lum.length;i+=step)sample.push(lum[i]);sample.sort((a,b)=>a-b);lo=sample[Math.floor(sample.length*0.0005)];hi=sample[Math.min(sample.length-1,Math.floor(sample.length*0.9995))];if(!(hi>lo)){lo=sample[0];hi=sample[sample.length-1]||lo+1;}}
    const c=document.createElement('canvas');c.width=W;c.height=H;const g=c.getContext('2d');const id=g.createImageData(W,H);const d=id.data;const map=x=>Math.max(0,Math.min(255,Math.round((x-lo)/(hi-lo)*255)));
    for(let i=0;i<npx;i++){if(spp>=3){d[i*4]=map(lum[i*spp]);d[i*4+1]=map(lum[i*spp+1]);d[i*4+2]=map(lum[i*spp+2]);}else{let gv=map(lum[i*spp]);if(photo===0)gv=255-gv;d[i*4]=d[i*4+1]=d[i*4+2]=gv;}d[i*4+3]=255;}g.putImageData(id,0,0);
    out.push({canvas:c,bits:bps,range:[lo,hi],spp,W,H});}
  if(!out.length)throw new Error('画像ページがありません');return out;}
function figLZW(src){const out=[];let dict=[],bitPos=0,codeLen=9;const read=()=>{let v=0;for(let i=0;i<codeLen;i++){const byte=src[bitPos>>3];const bit=byte===undefined?0:(byte>>(7-(bitPos&7)))&1;v=(v<<1)|bit;bitPos++;}return v;};const reset=()=>{dict=[];for(let i=0;i<256;i++)dict.push([i]);dict.push([]);dict.push([]);codeLen=9;};reset();let prev=null;
  while(bitPos+codeLen<=src.length*8){const code=read();if(code===257)break;if(code===256){reset();prev=null;continue;}let entry;if(code<dict.length)entry=dict[code];else if(prev)entry=prev.concat([prev[0]]);else break;for(const b of entry)out.push(b);if(prev)dict.push(prev.concat([entry[0]]));prev=entry;if(dict.length+1>=(1<<codeLen)&&codeLen<12)codeLen++;}
  return Uint8Array.from(out);}
function figPackBits(src){const out=[];let i=0;while(i<src.length){const n=(src[i++]<<24)>>24;if(n>=0){for(let k=0;k<=n;k++)out.push(src[i++]);}else if(n!==-128){const b=src[i++];for(let k=0;k<1-n;k++)out.push(b);}}return Uint8Array.from(out);}
// canvas を保存（TIFF から）
function figImgStoreCanvas(c,name,extra){return new Promise(async(res,rej)=>{const data=c.toDataURL('image/png');const id='im'+uid();const meta=Object.assign({w:c.width,h:c.height,name},extra||{});try{if(typeof IS_DESKTOP!=='undefined'&&IS_DESKTOP){const rr=await fetch('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,data})});if(!rr.ok)throw new Error('保存に失敗しました');}else{await figImgPut(id,data);}}catch(e){rej(new Error('画像を保存できませんでした（'+e.message+'）'));return;}FIG_IMG_META[id]=meta;if(typeof conv!=='undefined'&&conv){conv.imgs=conv.imgs||{};conv.imgs[id]=meta;}res({id,...meta});});}
async function figImgStoreAny(f){if(/tiff?$/i.test(f.name)||/tiff/i.test(f.type)){const buf=await f.arrayBuffer();const pages=figTiffDecode(buf);const base=String(f.name||'').replace(/\.[^.]+$/,'');const out=[];const big=Math.max(...pages.map(pg=>pg.W*pg.H));const keep=pages.filter(pg=>pg.W*pg.H>=big/8);for(let i=0;i<Math.min(keep.length,8);i++){const pg=keep[i];let c=pg.canvas;if(Math.max(c.width,c.height)>2000){const r=2000/Math.max(c.width,c.height);const c2=document.createElement('canvas');c2.width=Math.round(c.width*r);c2.height=Math.round(c.height*r);c2.getContext('2d').drawImage(c,0,0,c2.width,c2.height);c=c2;}out.push(await figImgStoreCanvas(c,keep.length>1?`${base}_p${i+1}`:base,{bits:pg.bits,srcRange:pg.range,pages:keep.length}));}return out;}return [await figImgStore(f)];}


/* ---------- 画像パネル作成の画面（#figImgDlg。Figure 作成と同じ構成: 左＝設定、右＝プレビュー） ---------- */
let figImgState=null; // {spec, src:{nodeId,index}|null, tool, pts, profiles:[]}
const figImgDefSpec=()=>({kind:'image',type:'grid',cols:3,images:[],scale:{umPerPx:0,len:20,unit:'µm',labelOn:'first'}});
function figImgOpen(spec,src){const $=s=>document.querySelector(s);figImgState={spec:JSON.parse(JSON.stringify(spec||figImgDefSpec())),src:src||null,tool:null,pts:[],profiles:[]};figImgTool=null;
  $('#figImgUpdate').style.display=src?'':'none';figImgFillForm();figImgSync();$('#figImgDlg').showModal();requestAnimationFrame(()=>{figImgFitPreview();setTimeout(figImgFitPreview,150);});}
async function figImgOpenWithFiles(files){const all=[...files].filter(f=>/^image\//i.test(f.type)||/\.tiff?$/i.test(f.name));const list=all.slice(0,60);if(!list.length){toast('画像ファイルを選んでください');return;}if(all.length>60)toast('一度に取り込めるのは 60 枚までです（残りは「＋ 画像を追加」で）');const imgs=[];for(const f of list){try{imgs.push(...await figImgStoreAny(f));}catch(e){toast(f.name+': '+e.message);}}if(!imgs.length)return;persist();
  const spec=figImgDefSpec();spec.cols=Math.min(imgs.length,3);spec.images=imgs.map(m=>({img:m.id}));figImgOpen(spec,null);toast(`画像 ${imgs.length} 枚を取り込みました。左の一覧で並べ替え・文字・色を決めてください`);}
function figImgFillForm(){const $=s=>document.querySelector(s);const j=figImgState.spec;const sb=j.scale||{};$('#figImgType').value=j.type==='blot'?'blot':'grid';$('#figImgTitle').value=j.title||'';$('#figImgCols').value=String(j.cols||3);$('#figImgCell').value=String(j.cellIn||1.2);$('#figImgFit').value=j.fit||'cover';$('#figImgAspect').value=j.aspect?String(j.aspect):'';
  $('#figImgRows').value=(j.rowLabels||[]).join(', ');$('#figImgColsLab').value=(j.colLabels||[]).join(', ');figImgFillColColors();$('#figImgUm').value=sb.umPerPx||'';$('#figImgLen').value=sb.len||'';$('#figImgUnit').value=sb.unit||'µm';$('#figImgLabelOn').value=sb.labelOn||'first';$('#figImgSbPos').value=sb.pos||'br';
  $('#figImgWidth').value=String(j.widthIn||2.5);$('#figImgLaneRot').value=j.laneRot?'1':'0';$('#figImgNameSide').value=j.nameSide||'right';$('#figImgLanes').value=(j.lanes||[]).join(', ');$('#figImgConds').value=(j.conds||[]).map(c=>c.wedge?`${c.name}: wedge`:`${c.name}: ${(c.vals||[]).join(', ')}`).join('\n');$('#figImgGroups').value=(j.groups||[]).map(g=>`${g.name}: ${(+g.from||0)+1}-${(g.to==null?+g.from||0:+g.to)+1}`).join(', ');
  figImgFillList();}
// 色のパレット（丸い見本をクリックで選ぶ。カスタム色は色の入力）。ik: data-ik、i: 行番号、cur: 現在値、o: {none:'（色なし）の見本を出す', names:true で channel 名を値にする}
const FIG_PAL=[['white','#FFFFFF'],['black','#000000'],['gray','#9E9E9E'],['red','#FF2A2A'],['green','#20D020'],['blue','#3050FF'],['cyan','#00E5FF'],['magenta','#FF40FF'],['yellow','#FFE000'],['orange','#FF8C00']];
function figSwatches(ik,i,cur,o){o=o||{};const val=v=>o.names?v[0]:v[1];const curS=String(cur||'').toLowerCase();const isOn=v=>curS===val(v).toLowerCase()||(curS===v[0]&&!o.names)||(o.names&&curS===v[1].toLowerCase());
  let h=`<span class="sws" data-ik="${ik}" data-i="${i}">`;if(o.none)h+=`<button type="button" class="sw none${!curS?' on':''}" data-v="" title="なし"></button>`;h+=FIG_PAL.map(v=>`<button type="button" class="sw${isOn(v)?' on':''}" data-v="${val(v)}" style="background:${v[1]}" title="${v[0]}"></button>`).join('');
  const custom=/^#[0-9a-f]{6}$/i.test(curS)&&!FIG_PAL.some(v=>v[1].toLowerCase()===curS);h+=`<input type="color" class="swc${custom?' on':''}" value="${custom?curS:'#ffffff'}" title="好きな色">`;return h+'</span>';}
function figImgFillColColors(){const $=s=>document.querySelector(s);const j=figImgState.spec;const cl=j.colLabels||[];const box=$('#figImgColColorsUI');if(!box)return;box.innerHTML=cl.length?cl.map((c,i)=>`<div class="r"><span class="hint" style="min-width:60px">${figEsc(c)}</span>${figSwatches('colColor',i,(j.colColors||[])[i]||'#000000')}</div>`).join(''):'<span class="hint">列見出しを入れると、列ごとの色を選べます</span>';
  const sb=$('#figImgSbColorUI');if(sb)sb.innerHTML=figSwatches('sbColor',0,(j.scale&&j.scale.color)||'white',{names:true});const ac=$('#figImgAnnotColorUI');if(ac)ac.innerHTML=figSwatches('annotColor',0,figImgState.annotColor||'#ffffff');}
function figImgFillList(){const $=s=>document.querySelector(s);const j=figImgState.spec;const blot=j.type==='blot';const items=blot?(j.bands||[]):(j.images||[]);const chs=[['','（色なし）'],['gray','白'],['blue','青'],['green','緑'],['red','赤'],['cyan','シアン'],['magenta','マゼンタ'],['yellow','黄']],luts=[['','LUT なし'],['fire','Fire'],['viridis','Viridis'],['inferno','Inferno'],['jet','Jet'],['grays','Grays']];
  const sel=(k,i,opts,cur)=>`<select data-ik="${k}" data-i="${i}">${opts.map(([v,l])=>`<option value="${v}"${String(cur==null?'':cur)===String(v)?' selected':''}>${l}</option>`).join('')}</select>`;
  $('#figImgList').innerHTML=items.map((im,i)=>{const L=Array.isArray(im.merge)?im.merge[0]:im;const url=L&&L.img?figImgURL(L.img):'';const meta=L&&L.img?figImgMeta(L.img):null;const merged=Array.isArray(im.merge);
    return `<div class="imgItem" data-i="${i}">${url?`<img src="${url}" alt="">`:'<div class="thumb">画像なし</div>'}<div class="rows">
      <div class="r"><input type="checkbox" data-ik="chk" data-i="${i}" title="合成に含める"><input type="text" data-ik="${blot?'name':'label'}" data-i="${i}" value="${figEsc(blot?(im.name||''):(im.label||''))}" placeholder="${blot?'抗体名':'セルの文字（任意）'}" style="width:110px" title="${figEsc(meta&&meta.name||'')}">${blot?`<input type="text" data-ik="kda" data-i="${i}" value="${figEsc(im.kda||'')}" placeholder="kDa" style="width:46px">`:''}<span class="hint" title="${figEsc(meta&&meta.name||'')}">${merged?'合成 '+im.merge.length+' 枚':meta?`${figEsc((meta.name||'').slice(0,14))} ${meta.w}×${meta.h}${meta.bits?' '+meta.bits+'bit':''}`:''}</span><span class="spacer"></span><button class="ib" data-ik="up" data-i="${i}" title="上へ">▲</button><button class="ib" data-ik="down" data-i="${i}" title="下へ">▼</button><button class="ib" data-ik="del" data-i="${i}" title="外す">✕</button></div>${blot?'':`<div class="r"><span class="hint">文字の色</span>${figSwatches('labelColor',i,im.labelColor||'#ffffff')}</div>`}
      ${merged?im.merge.map((M,mi)=>`<div class="r"><span class="hint">層 ${mi+1}</span>${figSwatches('m.channel.'+mi,i,M.channel,{none:true,names:true})}<input type="number" step="0.01" min="0" max="1" data-ik="m.range0.${mi}" data-i="${i}" value="${M.range?M.range[0]:''}" placeholder="min" style="width:52px"><input type="number" step="0.01" min="0" max="1" data-ik="m.range1.${mi}" data-i="${i}" value="${M.range?M.range[1]:''}" placeholder="max" style="width:52px"></div>`).join(''):`<div class="r"><span class="hint">色</span>${figSwatches('channel',i,im.channel,{none:true,names:true})}</div><div class="r">${sel('lut',i,luts,im.lut)}<input type="number" step="0.01" min="0" max="1" data-ik="range0" data-i="${i}" value="${im.range?im.range[0]:''}" placeholder="min" style="width:52px" title="表示範囲 0–1"><input type="number" step="0.01" min="0" max="1" data-ik="range1" data-i="${i}" value="${im.range?im.range[1]:''}" placeholder="max" style="width:52px"><input type="number" step="0.1" min="0.1" max="5" data-ik="gamma" data-i="${i}" value="${im.gamma||''}" placeholder="γ" style="width:44px" title="ガンマ"></div>`}
      <div class="r">${sel('rot',i,[['0','回転なし'],['90','90°'],['180','180°'],['270','270°']],im.rot||0)}${sel('flip',i,[['','反転なし'],['h','左右反転'],['v','上下反転'],['both','両方']],im.flip||'')}<input type="text" data-ik="crop" data-i="${i}" value="${im.crop?im.crop.join(', '):''}" placeholder="切り抜き x,y,w,h（割合）" style="width:150px"></div></div></div>`;}).join('')||'<div class="hint">「＋ 画像を追加」で画像を入れてください</div>';}
function figImgReadForm(){const $=s=>document.querySelector(s);const j=figImgState.spec;const list=v=>String(v||'').split(/[,、]/).map(x=>x.trim()).filter(Boolean);j.type=$('#figImgType').value;j.title=$('#figImgTitle').value.trim();
  if(j.type==='grid'){j.cols=+$('#figImgCols').value;j.cellIn=+$('#figImgCell').value;j.fit=$('#figImgFit').value;if(j.fit==='cover')delete j.fit;const asp=+$('#figImgAspect').value;if(asp>0)j.aspect=asp;else delete j.aspect;const rl=list($('#figImgRows').value),cl=list($('#figImgColsLab').value);if(rl.length)j.rowLabels=rl;else delete j.rowLabels;if(cl.length)j.colLabels=cl;else delete j.colLabels;if(j.colColors&&!j.colColors.some(Boolean))delete j.colColors;
    j.scale={umPerPx:+$('#figImgUm').value||0,len:+$('#figImgLen').value||0,unit:$('#figImgUnit').value,labelOn:$('#figImgLabelOn').value,color:(j.scale&&j.scale.color)||'white',pos:$('#figImgSbPos').value};if(!j.images&&j.bands)j.images=j.bands.map(b=>({img:b.img,label:b.name}));}
  else{j.widthIn=+$('#figImgWidth').value;j.laneRot=$('#figImgLaneRot').value==='1';j.nameSide=$('#figImgNameSide').value;const ln=list($('#figImgLanes').value);if(ln.length)j.lanes=ln;else delete j.lanes;
    const conds=String($('#figImgConds').value||'').split('\n').map(l=>l.trim()).filter(Boolean).map(l=>{const m=/^([^:：]+)[:：]\s*(.*)$/.exec(l);if(!m)return {name:l,vals:[]};return /^wedge$/i.test(m[2].trim())?{name:m[1].trim(),wedge:true}:{name:m[1].trim(),vals:list(m[2])};});if(conds.length)j.conds=conds;else delete j.conds;
    const groups=list($('#figImgGroups').value).map(g=>{const m=/^(.+?)[:：]\s*(\d+)\s*[-–]\s*(\d+)$/.exec(g);return m?{name:m[1].trim(),from:+m[2]-1,to:+m[3]-1}:null;}).filter(Boolean);if(groups.length)j.groups=groups;else delete j.groups;if(!j.bands&&j.images)j.bands=j.images.map(im=>({img:(im.merge?im.merge[0]:im).img,name:im.label||''}));}
  $('#figImgGridOpts').style.display=j.type==='grid'?'':'none';$('#figImgBlotOpts').style.display=j.type==='blot'?'':'none';}
function figImgSync(){const $=s=>document.querySelector(s);const j=figImgState.spec;let r=null;try{r=figRenderSpec(j);}catch(e){r=null;}figImgState.r=r;$('#figImgPreview').innerHTML=r&&r.svg?r.svg:'<div class="hint" style="color:#555">画像を追加すると、ここに表示されます</div>';figImgFitPreview();
  const n=(j.type==='blot'?(j.bands||[]):(j.images||[])).length;$('#figImgHint').textContent=n?`${n} セル ／ ${j.type==='blot'?'ブロット':'グリッド'}`:'';
  let st='';if(r&&r.adjust&&r.adjust.length)st+=`<div class="hint">表示調整（一様な線形調整のみ。元画像は変えず、内容は図の指定に残ります）: ${r.adjust.map(a=>`セル${a.cell+1} ${[a.channel,a.lut?'LUT '+a.lut:'',a.range?'範囲 '+a.range.join('–'):'',a.gamma?'γ '+a.gamma:''].filter(Boolean).join(' ')}`).join('、')}</div>`;
  if(figImgState.profiles.length)st+=figImgState.profiles.map((p,i)=>`<div class="hint">プロファイル ${i+1}: ${figEsc(p.title)}（添付・更新時に一緒に出します）</div>`).join('');$('#figImgStats').innerHTML=st||'<div class="hint">注釈はツール（上の行）を押してからプレビューの画像をクリック。置いた注釈はドラッグで動かせます。</div>';
  $('#figImgTools').innerHTML=`<span class="hint">注釈</span>${[['arrow','矢印'],['head','矢頭'],['star','＊'],['text','文字'],['roi','ROI 枠'],['inset','拡大図'],['line','プロファイル']].map(([t,l])=>`<button class="small${figImgState.tool===t?' on':''}" data-figdtool="${t}">${l}</button>`).join('')}<button class="small" data-figdtool="undo" title="最後の注釈を消す">⌫</button><span class="sep"></span><span class="hint">注釈の色</span><span id="figImgAnnotColorUI">${figSwatches('annotColor',0,figImgState.annotColor||'#ffffff')}</span><span class="sep"></span><span class="hint">${j.type==='blot'?'短冊':'セル'}をクリックで置く</span>`;}
// プレビューを枠に収める（幅と高さの小さい方に合わせる）
function figImgFitPreview(){const box=document.querySelector('#figImgPreview');const svg=box&&box.querySelector(':scope > svg');if(!svg)return;const W=+svg.getAttribute('width'),H=+svg.getAttribute('height');if(!(W>0&&H>0))return;const bw=box.clientWidth-32,bh=box.clientHeight-32;if(bw<80||bh<80){svg.style.width='100%';svg.style.height='auto';return;}const sc=Math.min(bw/W,bh/H,3);svg.style.width=Math.max(120,W*sc)+'px';svg.style.height='auto';}
window.addEventListener('resize',()=>{if(document.querySelector('#figImgDlg')&&document.querySelector('#figImgDlg').open)figImgFitPreview();});
function figImgSpecOut(){figImgReadForm();const j=JSON.parse(JSON.stringify(figImgState.spec));return j;}
// 画面のクリック（セル→注釈、ツール、画像リスト）
function figImgDlgInit(){const $=s=>document.querySelector(s);const dlg=$('#figImgDlg');if(!dlg)return;
  $('#figImgClose').onclick=()=>dlg.close();$('#figImgAdd').onclick=()=>$('#figImgAddFile').click();
  $('#figImgAddFile').onchange=async()=>{const list=[...$('#figImgAddFile').files];$('#figImgAddFile').value='';for(const f of list){try{for(const m of await figImgStoreAny(f)){figImgReadForm();const j=figImgState.spec;if(j.type==='blot')(j.bands=j.bands||[]).push({img:m.id});else (j.images=j.images||[]).push({img:m.id});}}catch(e){toast(f.name+': '+e.message);}}persist();figImgFillList();figImgSync();};
  ['#figImgType','#figImgTitle','#figImgCols','#figImgCell','#figImgFit','#figImgAspect','#figImgRows','#figImgColsLab','#figImgUm','#figImgLen','#figImgUnit','#figImgLabelOn','#figImgSbPos','#figImgWidth','#figImgLaneRot','#figImgNameSide','#figImgLanes','#figImgConds','#figImgGroups'].forEach(sl=>{const el=$(sl);const h=()=>{figImgReadForm();if(sl==='#figImgType')figImgFillList();if(sl==='#figImgColsLab')figImgFillColColors();figImgSync();};el.addEventListener('change',h);el.addEventListener('input',h);});
  $('#figImgList').addEventListener('change',e=>{const el=e.target.closest('[data-ik]');if(!el)return;const k=el.dataset.ik,i=+el.dataset.i;const j=figImgState.spec;const items=j.type==='blot'?j.bands:j.images;const im=items&&items[i];if(!im||k==='chk')return;
    const setRange=(o,idx,v)=>{o.range=o.range||[0,1];o.range[idx]=v===''?(idx?1:0):+v;if(o.range[0]===0&&o.range[1]===1)delete o.range;};
    if(k==='label'||k==='name'||k==='kda'){im[k]=el.value;if(!el.value)delete im[k];}else if(k==='channel'||k==='lut'||k==='flip'){if(el.value)im[k]=el.value;else delete im[k];}else if(k==='rot'){if(+el.value)im.rot=+el.value;else delete im.rot;}else if(k==='gamma'){if(+el.value&&+el.value!==1)im.gamma=+el.value;else delete im.gamma;}
    else if(k==='range0'||k==='range1')setRange(im,k==='range0'?0:1,el.value);else if(k==='crop'){const v=String(el.value).split(/[,、\s]+/).map(Number).filter(x=>isFinite(x));if(v.length===4)im.crop=v;else delete im.crop;}
    else if(k.startsWith('m.')){const [,kk,mi]=k.split('.');const M=im.merge&&im.merge[+mi];if(!M)return;if(kk==='channel'){if(el.value)M.channel=el.value;else delete M.channel;}else setRange(M,kk==='range0'?0:1,el.value);}
    figImgSync();});
  const swPick=(root,onPick)=>{root.addEventListener('click',e=>{const b=e.target.closest('.sw');if(!b)return;const wrap=b.closest('.sws');onPick(wrap.dataset.ik,+wrap.dataset.i,b.dataset.v);});root.addEventListener('input',e=>{const c=e.target.closest('.swc');if(!c)return;const wrap=c.closest('.sws');onPick(wrap.dataset.ik,+wrap.dataset.i,c.value);});};
  swPick($('#figImgList'),(k,i,v)=>{const j=figImgState.spec;const items=j.type==='blot'?j.bands:j.images;const im=items&&items[i];if(!im)return;if(k==='labelColor'){if(v&&v.toLowerCase()!=='#ffffff')im.labelColor=v;else delete im.labelColor;}else if(k==='channel'){if(v)im.channel=v;else delete im.channel;}else if(k.startsWith('m.channel.')){const M=im.merge&&im.merge[+k.split('.')[2]];if(!M)return;if(v)M.channel=v;else delete M.channel;}figImgFillList();figImgSync();});
  $('#figImgList').addEventListener('click',e=>{const el=e.target.closest('button[data-ik]');if(!el)return;const k=el.dataset.ik,i=+el.dataset.i;const j=figImgState.spec;const items=j.type==='blot'?j.bands:j.images;if(!items)return;
    if(k==='del')items.splice(i,1);else if(k==='up'&&i>0)[items[i-1],items[i]]=[items[i],items[i-1]];else if(k==='down'&&i<items.length-1)[items[i+1],items[i]]=[items[i],items[i+1]];
    if(j.annots)j.annots=j.annots.filter(a=>(a.cell||0)<items.length);figImgFillList();figImgSync();});
  swPick($('#figImgDlg .figLeft'),(k,i,v)=>{const j=figImgState.spec;if(k==='colColor'){j.colColors=j.colColors||[];while(j.colColors.length<=i)j.colColors.push('');j.colColors[i]=v&&v.toLowerCase()!=='#000000'?v:'';figImgFillColColors();figImgSync();}else if(k==='sbColor'){j.scale=j.scale||{};j.scale.color=v||'white';figImgFillColColors();figImgSync();}});
  swPick($('#figImgTools'),(k,i,v)=>{if(k==='annotColor'){figImgState.annotColor=v||'#ffffff';figImgSync();}});
  $('#figImgMerge').onclick=()=>{const j=figImgState.spec;if(j.type==='blot'){toast('合成はグリッドで使えます');return;}const ks=[...document.querySelectorAll('#figImgList [data-ik="chk"]:checked')].map(c=>+c.dataset.i);if(ks.length<2){toast('合成する画像を 2 つ以上チェックしてください');return;}
    const cols=['blue','green','red','cyan','magenta','yellow'];const layers=ks.map((k,n)=>{const im=j.images[k];const L=im.merge?im.merge[0]:im;return {img:L.img,channel:L.channel||cols[n%cols.length],...(L.range?{range:L.range}:{})};});j.images.push({merge:layers,label:'Merge'});figImgFillList();figImgSync();toast('合成セルを末尾に足しました（色は各層のチャンネルで変えられます）');};
  $('#figImgTools').addEventListener('click',e=>{const b=e.target.closest('[data-figdtool]');if(!b)return;const t=b.dataset.figdtool;const j=figImgState.spec;if(t==='undo'){if(j.annots&&j.annots.length){j.annots.pop();figImgSync();}else toast('消す注釈がありません');return;}figImgState.tool=figImgState.tool===t?null:t;figImgState.pts=[];figImgSync();if(figImgState.tool)toast(t==='line'?'始点と終点を順にクリック':'画像の中をクリック');});
  $('#figImgPreview').addEventListener('click',e=>{const cb=e.target.closest('[data-cellbox]');if(!cb||!figImgState.tool)return;const t=figImgState.tool;const box=cb.getBoundingClientRect();const x=+((e.clientX-box.left)/box.width).toFixed(3),y=+((e.clientY-box.top)/box.height).toFixed(3);const k=+cb.dataset.cellbox;const j=figImgState.spec;
    if(t==='line'){figImgState.pts.push({k,x,y});if(figImgState.pts.length<2)return;if(figImgState.pts[0].k!==k){figImgState.pts=[{k,x,y}];toast('同じ画像の中で終点をクリックしてください');return;}const [p1,p2]=figImgState.pts;figImgState.pts=[];figImgState.tool=null;figImgDlgProfile(k,p1,p2);return;}
    const a={t,cell:k,x,y};const ac=figImgState.annotColor;if(ac&&ac.toLowerCase()!=='#ffffff')a.color=ac;if(t==='roi'){a.w=0.25;a.h=0.25;}if(t==='inset'){a.w=0.25;a.h=0.25;a.size=0.42;a.at=(y<0.5?'b':'t')+(x<0.5?'r':'l');}figImgState.tool=null;const fin=()=>{(j.annots=j.annots||[]).push(a);figImgSync();};if(t==='text'){figPrompt('書く文字','').then(s=>{if(!s){figImgSync();return;}a.text=s;fin();});figImgSync();return;}fin();});
  $('#figImgJson').onclick=async()=>{const j=figImgSpecOut();const txt=await figPrompt('図の指定（JSON）。直して OK で反映',JSON.stringify(j,null,1),{multiline:true});if(txt==null)return;try{const jj=JSON.parse(txt);if(!figIsImage(jj))throw new Error('kind が image ではありません');figImgState.spec=jj;figImgFillForm();figImgSync();}catch(e){toast('JSON の誤り: '+e.message);}};
  const png=async()=>{const r=figImgState.r;if(!r||!r.svg)return null;return figToPng(r.svg,r.w,r.h,300);};
  $('#figImgPng').onclick=async()=>{const c=await png();if(!c)return;const a=document.createElement('a');a.href=figPngDataURL(c,300);a.download=`panel_${Date.now()}.png`;a.click();toast('PNG（300 dpi）を保存しました');};
  $('#figImgSvg').onclick=async()=>{const r=figImgState.r;if(!r)return;saveTextFile(`panel_${Date.now()}.svg`,await figInlineImages(r.svg));};
  $('#figImgCopy').onclick=async()=>{const c=await png();if(!c)return;try{const blob=await new Promise(r=>c.toBlob(r,'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('画像をコピーしました');}catch(e){toast('コピーできませんでした');}};
  $('#figImgAttach').onclick=async()=>{const j=figImgSpecOut();const r=figImgState.r;if(!r||!r.svg){toast('画像がありません');return;}const blocks=['```figure\n'+JSON.stringify(j)+'\n```'].concat(figImgState.profiles.map(p=>'```figure\n'+JSON.stringify(p)+'\n```'));
    try{if(imagesSupported&&pendingImgs.length<4){const c=await figToPng(r.svg,r.w,r.h,150);const full=c.toDataURL('image/jpeg',.9);const tc=document.createElement('canvas');const sc=256/Math.max(c.width,c.height);tc.width=Math.round(c.width*sc);tc.height=Math.round(c.height*sc);tc.getContext('2d').drawImage(c,0,0,tc.width,tc.height);pendingImgs.push({full:{media_type:'image/jpeg',data:full.split(',')[1]},thumb:tc.toDataURL('image/jpeg',.8)});renderPlus();}}catch(e){}
    persist();dlg.close();const t=$('#input');t.value=(t.value?t.value+'\n':'')+blocks.join('\n\n')+'\n';if(typeof fitInput==='function')fitInput();t.focus();toast('パネルを添付し、指定を入力欄に入れました。並べ方や見出しの指示を添えて送信してください');};
  $('#figImgUpdate').onclick=()=>{const src=figImgState.src;if(!src)return;const n=N(src.nodeId);if(!n)return;const b=figFindBlocks(n.content)[src.index];if(!b){toast('元の図が見つかりません');return;}const j=figImgSpecOut();let out='```figure\n'+JSON.stringify(j)+'\n```';figImgState.profiles.forEach(p=>{out+='\n\n```figure\n'+JSON.stringify(p)+'\n```';});
    if(src.panel!=null){let lay;try{lay=JSON.parse(b.json);}catch(e){return;}if(!lay.panels||!lay.panels[src.panel])return;lay.panels[src.panel]=j;out='```figure\n'+JSON.stringify(lay)+'\n```';}
    n.content=n.content.slice(0,b.start)+out+n.content.slice(b.end);persist();renderAll();dlg.close();toast('回答の図を更新しました');};}
// 画面内のプロファイル: 線の注釈を足し、xy の図を profiles に積む（添付・更新時に一緒に出す）
async function figImgDlgProfile(k,p1,p2){const j=figImgState.spec;const r=figImgState.r;const cell=r&&r.cells&&r.cells[k];if(!cell||!cell.view||!cell.cellSVG){toast('この画像ではプロファイルを取れません');return;}const L=cell.cellSVG.layers[0];const meta=cell.cellSVG.meta;const col=['#FFD500','#00E5FF','#FF4DD2','#7CFF4D'][((j.annots||[]).filter(a=>a.t==='line').length)%4];
  try{const im=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('画像を読めませんでした'));i.src=figImgURL(L.img);});const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const v=cell.view;const X=p=>v.x+p.x*v.w,Y=p=>v.y+p.y*v.h;const x1=X(p1),y1=Y(p1),x2=X(p2),y2=Y(p2);const Lpx=Math.hypot(x2-x1,y2-y1);const um=j.scale&&+j.scale.umPerPx>0?+j.scale.umPerPx:0;const rows=[];
    for(let i=0;i<=200;i++){const t=i/200;const px=Math.max(0,Math.min(im.width-1,Math.round(x1+(x2-x1)*t))),py=Math.max(0,Math.min(im.height-1,Math.round(y1+(y2-y1)*t)));const d=g.getImageData(px,py,1,1).data;rows.push([um?(Lpx*t*um).toFixed(2):Math.round(Lpx*t),(0.299*d[0]+0.587*d[1]+0.114*d[2]).toFixed(1)]);}
    (j.annots=j.annots||[]).push({t:'line',cell:k,x:p1.x,y:p1.y,x2:p2.x,y2:p2.y,color:col});const name=(j.type==='blot'?(j.bands[k]&&j.bands[k].name):(j.images[k]&&j.images[k].label))||(meta&&meta.name)||'画像';
    figImgState.profiles.push({title:`${name} の輝度プロファイル`,kind:'xy',type:'xy-line',xtitle:um?'Distance (µm)':'Distance (px)',ytitle:'Intensity (a.u.)',data:['Distance\tIntensity'].concat(rows.map(x=>x.join('\t'))).join('\n'),style:{series:[{color:col,symPt:0.1}],wIn:2.5,hIn:1.5}});figImgSync();toast('計測線を置き、輝度プロファイルの図を用意しました（添付・更新時に一緒に出ます）');}
  catch(e){toast(e.message||'プロファイルを取れませんでした');}}
function figImgDlgDragEnd(ai,dx,dy){const j=figImgState&&figImgState.spec;const a=j&&(j.annots||[])[ai];const r=figImgState&&figImgState.r;const c=r&&r.cells&&r.cells[a?a.cell||0:0];if(!a||!c)return;const fx=dx/c.w,fy=dy/c.h;const cl=v=>+Math.max(0,Math.min(1,v)).toFixed(3);a.x=cl((+a.x||0)+fx);a.y=cl((+a.y||0)+fy);if(a.t==='line'){a.x2=cl((+a.x2||0)+fx);a.y2=cl((+a.y2||0)+fy);}figImgSync();}
document.addEventListener('DOMContentLoaded',figImgDlgInit);

FIG_PROMPT+=`
画像パネル（顕微鏡・IHC・ブロット）は kind "image"。画像は利用者が添付・保存したもので、id（"im…"）でだけ参照できる（新しい画像は作れない。利用者の指定にある id をそのまま使う）。
type "grid": {"kind":"image","type":"grid","cols":3,"cellIn":1.2,"rowLabels":["Control","Zolmin"],"colLabels":["DAPI","GFP","Merge"],"colColors":["#4040FF","#00C000",""],"images":[{"img":"id","label":"左上の文字"},…],"scale":{"umPerPx":0.65,"len":20,"unit":"µm","pos":"br","color":"white","labelOn":"first"},"annots":[{"t":"arrow|head|star|text|roi","cell":0,"x":0.5,"y":0.5,"dir":225,"text":"","color":"white"}]}（x,y はセル内の割合 0–1）。
type "blot": {"kind":"image","type":"blot","widthIn":2.5,"lanes":["1","2","3","4"],"conds":[{"name":"Zolmin","vals":["−","+","−","+"]},{"name":"濃度","wedge":true}],"groups":[{"name":"Raji","from":0,"to":1}],"bands":[{"img":"id","name":"CD20","kda":"35"},{"img":"id","name":"β-actin","kda":"42"}]}。
グリッドの "fit":"cover|contain"（cover＝枠いっぱいで切る、contain＝画像全体を余白付きで収める。比率の違う画像を並べるときは contain）、"aspect"（セルの縦横比 h/w、省略で 1 枚目に合わせる）、"bg"（余白の色）。blot の "nameSide":"left|right"（抗体名の位置）。
画像の表示調整（全体に一様な線形調整だけ。JSON に残る）: 各 image に "channel":"blue|green|red|cyan|magenta|yellow|gray|#RRGGBB"（グレー画像の疑似カラー）、"range":[0.02,0.8]（表示範囲 0–1）、"gamma":1.0、"lut":"fire|viridis|inferno|jet|grays"、"rot":90、"flip":"h|v"、"crop":[x,y,w,h]（割合）。合成は {"merge":[{"img":"id1","channel":"blue"},{"img":"id2","channel":"green"}],"label":"Merge"}（screen 合成）。
注釈の追加: {"t":"inset","cell":0,"x":0.3,"y":0.4,"w":0.25,"h":0.25,"at":"br","size":0.42}（ROI の拡大挿入図）、{"t":"line","cell":0,"x":0.1,"y":0.5,"x2":0.9,"y2":0.5}（計測線）。
画像パネルは layout の panels にも入れられる。`;
